### ISSUE TITLE
BUG - Strange horizontal gap in table when exporting to PDF

### ISSUE THREAD

**Issue by jplevene** [qtwebkit/qtwebkit#1000]
Command line loaded an HTML document into the browser, exported it as a PDF and there is a strange large unaccountable horizontal gap in the bottom table.

I am using webkit via the command line on an AWS Linux machine, so it's a command line headerless load with a command line export to PDF.

I have attached the HTML file and exported PDF.  I have tested it on Chrome headerless and FireFox and all is fine

I am using webkit 5.6.1

[bug docs.zip](https://github.com/qtwebkit/qtwebkit/files/4807110/bug.docs.zip)

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello @jplevene so I tried creating a simple eg to reproduce the issue, but I couldn't reproduce the bug it renders fine for me. Check out this repo for the [code](https://github.com/RAJAGOPALAN-GANGADHARAN/pdf_bug_qt) and the [output pdf](https://github.com/RAJAGOPALAN-GANGADHARAN/pdf_bug_qt/blob/master/result.pdf)
