### ISSUE TITLE
conan build on windows not installing?

### ISSUE THREAD

**Issue by Zedsquared** [qtwebkit/qtwebkit#1009]
Hi Folks,
       on building the latest qtwebkit from git on windows 10, msvc2019,  with the command line: 

Tools\qt\build-qtwebkit-conan.py --compiler=msvc --qt=C:\Qt\Qt5.9.9\5.9.9\msvc2017_64 --install

All appears to go well, but the install phase does not result in qtwebkit dlls in my qt installation, is this to be expected?

final output from build is:

`-- Install configuration: "Release"
-- Importing dependencies from conan to C:/qtwebkit/build/package
Using lockfile: 'C:\qtwebkit\build/conan.lock'
Using cached profile from lockfile
conanfile.txt imports(): Copied 5 '.dll' files
-- conan imports result: 0
-- Removed conan install manifest: C:/qtwebkit/build/package/conan_imports_manifest.txt
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKit/Qt5WebKitConfig.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKit/Qt5WebKitConfigVersion.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfigVersion.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKit/WebKitTargets.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKit/WebKitTargets-release.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsTargets.cmake
-- Installing: C:/qtwebkit/build/package/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsTargets-release.cmake
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebkitglobal.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebdatabase.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebelement.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebfullscreenrequest.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebhistory.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebhistoryinterface.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebkitplatformplugin.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebpluginfactory.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebsecurityorigin.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qwebsettings.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebDatabase
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebElement
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebElementCollection
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebFullScreenRequest
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebHistory
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebHistoryItem
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebHistoryInterface
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebKitPlatformPlugin
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebHapticFeedbackPlayer
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebFullScreenVideoHandler
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebNotificationData
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebNotificationPresenter
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebSelectData
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebSelectMethod
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebSpellChecker
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebTouchModifier
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebPluginFactory
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebSecurityOrigin
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QWebSettings
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QtWebKit
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/qtwebkitversion.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QtWebKitVersion
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/QtWebKitDepends
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qhttpheader_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebdatabase_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebelement_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebhistory_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebplugindatabase_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebscriptworld_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKit/5.212.0/QtWebKit/private/qwebsecurityorigin_p.h
-- Installing: C:/qtwebkit/build/package/lib/pkgconfig/Qt5WebKit.pc
-- Installing: C:/qtwebkit/build/package/mkspecs/modules/qt_lib_webkit.pri
-- Installing: C:/qtwebkit/build/package/mkspecs/modules/qt_lib_webkit_private.pri
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qgraphicswebview.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qwebframe.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qwebinspector.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qwebpage.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qwebview.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QGraphicsWebView
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QWebFrame
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QWebHitTestResult
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QWebInspector
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QWebPage
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QWebView
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QtWebKitWidgets
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/qtwebkitwidgetsversion.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QtWebKitWidgetsVersion
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/QtWebKitWidgetsDepends
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/5.212.0/QtWebKitWidgets/private/qwebframe_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/5.212.0/QtWebKitWidgets/private/qwebinspector_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/5.212.0/QtWebKitWidgets/private/qwebpage_p.h
-- Installing: C:/qtwebkit/build/package/include/QtWebKitWidgets/5.212.0/QtWebKitWidgets/private/qwebviewaccessible_p.h
-- Installing: C:/qtwebkit/build/package/lib/pkgconfig/Qt5WebKitWidgets.pc
-- Installing: C:/qtwebkit/build/package/mkspecs/modules/qt_lib_webkitwidgets.pri
-- Installing: C:/qtwebkit/build/package/mkspecs/modules/qt_lib_webkitwidgets_private.pri
-- Installing: C:/qtwebkit/build/package/lib/Qt5WebKitWidgets.lib
-- Installing: C:/qtwebkit/build/package/bin/Qt5WebKitWidgets.dll
-- Installing: C:/qtwebkit/build/package/lib/Qt5WebKit.lib
-- Installing: C:/qtwebkit/build/package/bin/Qt5WebKit.dll
Exit code: 0`
``

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey thanks for pointing it out, this has been fixed  in #1018

**Comment by annulen** [comment]
Should be fixed now.
