### ISSUE TITLE
build-webkit script doesn't generate the include directory

### ISSUE THREAD

**Issue by XankurX** [qtwebkit/qtwebkit#1010]
Hello team,

I am using the build script Tools/Scripts/build-webkit to build QtWebKit-5.212 taken from here on Windows:
http://code.qt.io/cgit/qt/qtwebkit.git/

When the build completes(that happens without an error) I get the build artifacts, though the build artifacts don't have the include directory available with it which I need to use the generates bins/libs.

What am I missing?

Regards,
Ankur

**Comment by annulen** [comment]
You need to install it. BTW, build-webkit is deprecated, use new Windows instruction from wiki.

**Comment by XankurX** [comment]
Thanks annulen. 
What do I do to install it? Do i need to pass an additional flag for installation?

Unfortunately the build infrastructure I am using doesn't allow me to use python-pip for now.

**Comment by annulen** [comment]
If you cannot install pip, you should be able to install Conan from .exe installer https://conan.io/downloads.html
build-webkit has --install argument

**Comment by XankurX** [comment]
Thanks Annulen,

--install works! though I intend to install it outside of Qt's installed dir.
Is there a way I can pass it an install directory where I need to install it?

**Comment by annulen** [comment]
It has --help which documents all options. One you are looking for is --prefix=

**Comment by annulen** [comment]
But note that if you install outside of Qt it may be harder to use in your projects
