### ISSUE TITLE
Failed to build on Windows with CONAN profiles

### ISSUE THREAD

**Issue by narcdev** [qtwebkit/qtwebkit#1033]
Hi, 

I'm currently trying to build on my Windows with specifics CONAN profile. Here are the command line :

Default (QT 5.15 for MSVC2019 x86_64)
`python Tools\qt\build-qtwebkit-conan.py --qt=C:\.conan\d0cebf3\1 --cmakeargs "-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF" --build_directory=C:\.conan\d0cebf3\1\qtwebkit`

This one works. No problems

With my profile (QT 5.15 with MSVC2017 x86_64) 
`python Tools\qt\build-qtwebkit-conan.py --qt=C:\.conan\e6957d\1 --cmakeargs "-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF" --build_directory=C:\.conan\e6957d\1\qtwebkit --profile=VS2017 `

This one failed with the following output :
`-- The C compiler identification is unknown
-- The CXX compiler identification is unknown`

Thanks in advance.

**Comment by annulen** [comment]
Does your profile work with other conan packages? What cmake command is run by conan (it's printed in build log after "----Running------")?

**Comment by annulen** [comment]
Also, building against Qt from conan is completely untested and requires modifications in conanfile to work properly (in particular, there are common dependencies which need to be aligned)

**Comment by narcdev** [comment]
> 
> 
> Does your profile work with other conan packages? What cmake command is run by conan (it's printed in build log after "----Running------")?

Yes my profile works with others conan package. I've build all my dependencies with it.

And here is the failing cmake command :
`cd C:\.conan\e6957d\1\qtwebkit && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP12" -DCONAN_C_FLAGS="/MP12" -DCMAKE_INSTALL_PREFIX="C:\.conan\e6957d\1" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="OFF" -DQT_CONAN_DIR="C:\.conan\e6957d\1\qtwebkit" -DQT_CONAN_FILE="G:\CONAN\qtwebkit\Tools\qt\conanfile.py" -DQt5_DIR="C:\.conan\e6957d\1\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -Wno-dev -DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF G:\CONAN\qtwebkit`

**Comment by narcdev** [comment]
> 
> 
> Also, building against Qt from conan is completely untested and requires modifications in conanfile to work properly (in particular, there are common dependencies which need to be aligned). Patches are welcome.

If I use the python script without the parameters "--profile", the build is OK. And QT is from conan (qt/5.15.0@bincrafters/stable).
It's just when the param "--profile" is added, something append and it seems to loose link with C / Cxx Compiler

I've made another test :
- Without the param "--profile" : BUILD OK.
- With the param "--profile=default", so same thing as no param "--profile"  : BUILD NOT OK.

**Comment by annulen** [comment]
>If I use the python script without the parameters "--profile", the build is OK. And QT is from conan (qt/5.15.0@bincrafters/stable).

If it builds it doesn't mean it will work correctly. For example if QtGui and QtWebKit are built with different versions of libjpeg, run-time crashes or visual artifacts in jpeg files may happen. Same with libpng and maybe sqlite (if application uses QtSql). Also, existing conanfile.py links zlib statically, while when Qt is used from conan it should be same as what Qt uses. And of course it should not require setting --qt manually in this case as location is internal to conan.

>It's just when the param "--profile" is added, something append and it seems to loose link with C / Cxx Compiler

When build-qtwebkit-conan.py is run without options it creates "internal" profile name "qtwebkit_{compiler}_{arch}". If profile is set explicitly it's passed to conan via `--profile` otherwise "internal" profile is passed. It might help if you compare generated profile with yours

**Comment by narcdev** [comment]
Please find here somme others informations :

**VS2019 X86_64 - qt/5.15.0@bincrafters/stable**

`python Tools\qt\build-qtwebkit-conan.py --qt=C:\.conan\d0cebf3\1 --cmakeargs="-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF" --profile=default`
or
`python Tools\qt\build-qtwebkit-conan.py --qt=C:\.conan\d0cebf3\1 --cmakeargs="-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF"`

CMake command line :
`cd G:\CONAN\qtwebkit\build && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP12" -DCONAN_C_FLAGS="/MP12" -DCMAKE_INSTALL_PREFIX="C:\.conan\d0cebf3\1" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="OFF" -DQT_CONAN_DIR="G:\CONAN\qtwebkit\build" -DQT_CONAN_FILE="G:\CONAN\qtwebkit\Tools\qt\conanfile.py" -DQt5_DIR="C:\.conan\d0cebf3\1\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -Wno-dev -DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF G:\CONAN\qtwebkit`

Build OK

**VS2017 X86_64 - qt/5.15.0@bincrafters/stable**

`python Tools\qt\build-qtwebkit-conan.py --qt=C:\.conan\e6957d\1 --cmakeargs="-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF" --profile=VS2017`

CMake command line :
`
cd G:\CONAN\qtwebkit\build && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP12" -DCONAN_C_FLAGS="/MP12" -DCMAKE_INSTALL_PREFIX="C:\.conan\e6957d\1" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="OFF" -DQT_CONAN_DIR="G:\CONAN\qtwebkit\build" -DQT_CONAN_FILE="G:\CONAN\qtwebkit\Tools\qt\conanfile.py" -DQt5_DIR="C:\.conan\e6957d\1\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -Wno-dev -DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF G:\CONAN\qtwebkit
`

Build failed

The VS2017 Conan profile 
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by annulen** [comment]
There is one thing which may be relevant. When generating our profiles we've found that we have to set CC and CXX environment variables, otherwise compilation fails, see https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-5.212/Tools/qt/build-qtwebkit-conan.py#L56-L86. I have no slightest idea why "native" conan builds work without them and here they are required, cmake with ninja generator definitely require them so they must be set somewhere else.

**Comment by annulen** [comment]
Actually if CC and CXX are left empty cmake -G Ninja picks up gcc/g++ pair if they are found in PATH. No idea what happens when they aren't, would be reasonable to try out cl but maybe what really happens is your case.

**Comment by annulen** [comment]
In short, I'm proposing you to try
```
set CC=cl
set CXX=cl
python Tools\qt\build-qtwebkit-conan.py ...
```

**Comment by narcdev** [comment]
> 
> 
> In short, I'm proposing you to try
> 
> ```
> set CC=cl
> set CXX=cl
> python Tools\qt\build-qtwebkit-conan.py ...
> ```

Ok it seems to work for the moment. I'll let you know if the build goes well. 

But, I think I've found something interesting 

The modification work on a computer where only one MSVC installed.
On the other one, where MSVC 2017 and 2019 are installed, it's more complicated.. 
It only works if the build is with the "default system" MSVC (2019 in this case). 

So I've tried this :
- Add the following code : `profile.update('compiler.version','16')` on this line https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-5.212/Tools/qt/build-qtwebkit-conan.py#L93
- `python Tools\qt\build-qtwebkit-conan.py ...` whithout profile, only defaut and let the profiles be generated.

If I set it to 16 (MSVC 2019 number) it works. 
If I set it to 15 (MSVC 2017 number), it fails..

**Comment by annulen** [comment]
Does conan work fine if used with other packages in "normal" way (e.g. `conan build`)

**Comment by narcdev** [comment]
> 
> 
> Does conan work fine if used with other packages in "normal" way (e.g. `conan build`)

Yes, no problem for "cross MSVC build" the others package.

**Comment by annulen** [comment]
It seems to me that you are experienced Conan user (or at least more experienced than me). If this is the case I think you can debug this issue and find solution faster than me, and then share your findings. You should probably start from reproducing conan commands which are executed by script, and then start removing custom hacks from Tools/qt/conanfile.py until it works

**Comment by annulen** [comment]
Could you try building recipe with `cmake.generator = "Ninja"` in `build`? By default Conan uses cmake generators like "Visual Sudio 19" and so on, and it may be a generic Conan bug that ninja doesn't work with multiple VS installations and requires setting environment variables

**Comment by annulen** [comment]
If this is the case, please report bug to Conan, and try removing `cmake.generator = "Ninja"` from conanfile.py. Note that such workaround will likely result in longer build times.

**Comment by annulen** [comment]
@narcdev ping

**Comment by narcdev** [comment]
For the moment, it seems to work. But we have done it with another solutions. 

We have embeded the call of your python script inside our conan file, here is the code :

```
        with tools.environment_append({"CC": cc, "CXX": cxx }):
            self.run('python ' + self.source_folder + '/qtwebkit/Tools/qt/build-qtwebkit-conan.py '
                '--qt=' + self.build_folder + '/qt '
                '--cmakeargs "-DUSE_GSTREAMER=OFF -DENABLE_X11_TARGET=OFF -DENABLE_WEBKIT2=OFF -DENABLE_API_TESTS=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF" '
                '--build_directory=' + self.build_folder + '/qtwebkit '
                '--profile=' + profile_name + ' '
                '--install', run_environment=True
            )
```
Where `profile_name` is the profile used to launch our conanfile.

With the setting of the env var CC / CXX with `with tools.environment_append({"CC": cc, "CXX": cxx }):`, it seems to build with the good profiles.

We are currently building for every profile, and we'll test them afterward..

I'll let you know the results, but it will take some times, builds are really long..

**Comment by annulen** [comment]
Do I understand correctly that you confirm this is generic Conan bug that ninja generator doesn't work correctly with Visual Studio?

**Comment by narcdev** [comment]
> 
> 
> Do I understand correctly that you confirm this is generic Conan bug that ninja generator doesn't work correctly with Visual Studio?

We have not tested this for the moment. Ninja is still doing the build. We have not touch your conanfile.

**Comment by narcdev** [comment]
When the builds are done, I'll try to remove Ninja and check what append.

**Comment by annulen** [comment]
You could do the opposite, add `cmake.generator = "Ninja"` to any small project and check if it requires setting CC/CXX variables and fails on machine with two Visual Studio versions

**Comment by annulen** [comment]
Also, in `with tools.environment_append({"CC": cc, "CXX": cxx })` where do you get cc and cxx?

**Comment by narcdev** [comment]
> 
> 
> Do I understand correctly that you confirm this is generic Conan bug that ninja generator doesn't work correctly with Visual Studio?

Ok so I just finished the tests

As before :
- Add the following code : `profile.update('compiler.version','16')` on this line https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-5.212/Tools/qt/build-qtwebkit-conan.py#L93
- `python Tools\qt\build-qtwebkit-conan.py ...` whithout profile, only defaut and let the profiles be generated.

If I set it to 16 (MSVC 2019 number) it works. 
If I set it to 15 (MSVC 2017 number), it fails..

THEN I have removed everything about Ninja in your conanfile.py and relaunch the tests :

If I set it to 16 (MSVC 2019 number) it works. 
If I set it to 15 (MSVC 2017 number), it works. 

So it seems Ninja is the issue if you have several MSVC installed on your system.

**Comment by narcdev** [comment]
> 
> 
> Also, in `with tools.environment_append({"CC": cc, "CXX": cxx })` where do you get cc and cxx?

We have done the same things as you do :

```
  compiler_preset = {
            "msvc": ["cl", "cl"],
            "clang": ["clang", "clang++"],
            "gcc": ["gcc", "g++"]
        }
        if platform.system() == "Windows":
            compiler = "msvc"
        elif platform.system() == "Darwin":
            compiler = "clang"
        elif platform.system() == "Linux":
            compiler = "gcc"

        if not compiler in compiler_preset:
            sys.exit("Error: Unknown Compiler " + compiler + " specified")

        cc, cxx = compiler_preset[compiler]
```

**Comment by annulen** [comment]
Could you report Ninja bug to Conan upstream, or help with it?

**Comment by narcdev** [comment]
> 
> 
> Could you report Ninja bug to Conan upstream, or help with it?

I'll try to reproduce it with another little project and then send it to Conan

**Comment by annulen** [comment]
Thank you!

**Comment by narcdev** [comment]
Hi,

I've made a little test repo : https://github.com/narcdev/vorb_test

I've taken the libvorbis recipes from the official CONAN recipes and made some tests with CMake / Ninja.
For the moment, everything is OK and I can't reproduce the issue with this project. 

If you want to have a look.

**Comment by annulen** [comment]
I see that both profiles use `compiler.version=15`, which is wrong for testing case with 2 VS installations

**Comment by annulen** [comment]
I also would like to see cmake invocation commands for vs2017 and vs2019 with different profiles (set CONAN_PRINT_RUN_COMMANDS=1)

**Comment by narcdev** [comment]
> 
> 
> I see that both profiles use `compiler.version=15`, which is wrong for testing case with 2 VS installations

Exact, the copy-paste was wrong. have set the correct one

**Comment by narcdev** [comment]
> set CONAN_PRINT_RUN_COMMANDS=1

Here they are : 

python build-libvorbis-conan.py --profile VS2017 : 
`
cd G:\CONAN\vorb_test\all\build_subfolder && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP12" -DCONAN_C_FLAGS="/MP12" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="G:\CONAN\vorb_test\all\package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="ON" -Wno-dev G:\CONAN\vorb_test\all
`

python build-libvorbis-conan.py --profile default : 
`
cd G:\CONAN\vorb_test\all\build_subfolder && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP12" -DCONAN_C_FLAGS="/MP12" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="G:\CONAN\vorb_test\all\package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="ON" -Wno-dev G:\CONAN\vorb_test\all
`

**Comment by annulen** [comment]
I'm getting error like
```
CMake Error at CMakeLists.txt:7 (add_subdirectory):

  add_subdirectory given source "source_subfolder" which is not an existing directory.
```
any idea how to fix this?

**Comment by annulen** [comment]
I've set up build in travis (which has 2017 preinstalled) and issue is reproducing there: with VS2017 profile VS2019 is picked by cmake, resulting in 

```
CMake Error at conanbuildinfo.cmake:729 (message):

  Detected a mismatch for the compiler version between your conan profile

  settings and CMake:

  Compiler version specified in your conan profile: 15

  Compiler version detected in CMake: 19.27
```

https://github.com/annulen/travis-vs2019-test

**Comment by narcdev** [comment]
If you do it without the python script, does it works ? 
conan create . 1.3.7@dev/test
conan create . 1.3.7@dev/test --profile VS2017

**Comment by annulen** [comment]
Without script `conan create` just picks gcc with Ninja, and works fine with default generator. I think it has nothing to do with 2 VS installations, Conan just lets CMake to choose compiler according to its internal fallback order, and compiler settings from profile are ignored. With script we force CC and CXX to be cl, so gcc is ignored and first cl.exe from PATH is picked up.

**Comment by annulen** [comment]
https://github.com/conan-io/conan/issues/6447
https://github.com/conan-io/conan/issues/6477

**Comment by annulen** [comment]
OK, I thing I've fogured this out
* `conan create` with Ninja generator requires setting CC/CXX to choose right compiler. This is a known issue of Conan which isn't yet addressed (https://github.com/conan-io/conan/issues/6447)
* `build-qtwebkit-conan.py` sets CC and CXX for generated profiles, but not for profiles specified via `--profile` option.

Could you try a patch from https://github.com/qtwebkit/qtwebkit/pull/1034?

**Comment by narcdev** [comment]
I've done some tests with your patch and it seems to work fine !

**Comment by annulen** [comment]
I assume this is fixed now
