### ISSUE TITLE
QWebView setHtml() without baseUrl takes 10seconds to load for the first time

### ISSUE THREAD

**Issue by RKesireddy2** [qtwebkit/qtwebkit#1039]
Am using Qt WebKit 5.212 Alpha4 release through yocto build on top of Qt 5.6.3 binaries and found good with respect to security bugs and fixes as recommended and QtTestBrowser works fine on target.

Below are the sample codes in our UiApp to set scrollbar stylesheet:-
webView = new QWebView();
webView->setContextMenuPolicy( Qt::NoContextMenu );
webView->settings()->setUserStyleSheetUrl( QUrl::fromLocalFile(<stylesheetpath.css> ) );
webView->settings()->setDefaultTextEncoding( "utf-8");
webView->setHtml( <htmldata>);//htmldata in QString

On profiling the QtWebkit source code, it is found that new QWebPage() takes 8 secs with lot of initializations.
and the execution time of setHtml doesnot depends on page or stylesheet trying to load as it is the same delay.

The same UiApp codes works faster without any delay incase of Qt4.8.4 based QtWebkit. The Qt thread is created as a worker thread(using pthread) where QApplication instance is created. QWebView and QWebSettings are created in the same thread.
The usecase of UIApp is HTML rendering in non-browser applications with HTML data readily available and not running any javascript programs but only webkit scrollbar css to scroll the html content. The usecases 1),2) and 3) in https://github.com/qtwebkit/qtwebkit/wiki/Use-cases-of-QtWebKit#use-case-1-embedded-systems satisfy our requirements.

Looks like most likely the delay is due to the yocto webkit build recipe issue/any of the patches which is pasted here if it lacks any optimized build like disabling any of cmake options like -DENABLE_JIT=OFF. Attached is the qtwebkit bb file and patch if it could cause any issue.
[recipes-qt_qt5_qtwebkit_0002-generate-bytecode-files-Add-support-for-Python-2.7.zip](https://github.com/qtwebkit/qtwebkit/files/5680321/recipes-qt_qt5_qtwebkit_0002-generate-bytecode-files-Add-support-for-Python-2.7.zip)

[qtwebkit_git.zip](https://github.com/qtwebkit/qtwebkit/files/5678866/qtwebkit_git.zip)

Please suggest if any that would be the cause of delay in page creation as it happens only for the first time.

**Comment by annulen** [comment]
Closing, as it was discovered that delay was cause by initialization of QFontDatabase
