### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by OrdinaryGamer564** [qtwebkit/qtwebkit#1044]
I am compilng QT Webkit Python 3.7.9 and Visual Studio 2017 `error: failed retrieving file 'libgdbm-1.18.1-2-i686.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'libgdbm-1.18.1-2-i686.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'libgdbm-1.18.1-2-i686.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'libgdbm-1.18.1-2-i686.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'gdbm-1.18.1-2-i686.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
assertion "httpc->drain_total >= data->state.drain" failed: file "http2.c", line 496, function: drain_this
      1 [main] pacman 191 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
msys2/20190524:
msys2/20190524: ERROR: Package '02335dedca0a2cdcde89828f81194929ef12d610' build failed
msys2/20190524: WARN: Build folder C:\.conan\1182a3\1
ERROR: msys2/20190524: Error in build() method, line 60
        self.run('bash -l -c "pacman -S %s --noconfirm"' % package)
        ConanException: Error 34304 while executing bash -l -c "pacman -S base-devel --noconfirm"
Exit code: 1` I am unsure as to why I am getting this error.

**Comment by annulen** [comment]
I don't understand what are you trying to do, but pacman and msys2 have nothing to do with Visual Studio.

**Comment by OrdinaryGamer564** [comment]
I am running this `py Tools\qt\build-qtwebkit-conan.py --qt=C:\qt5\win_msvc2017x86 --arch=x86 --install` and it errors there. That is what I meant.

**Comment by narcdev** [comment]
> 
> 
> I am running this `py Tools\qt\build-qtwebkit-conan.py --qt=C:\qt5\win_msvc2017x86 --arch=x86 --install` and it errors there. That is what I meant.

Did you run this command in msys or cygwin ? Or in the windows command prompt ?

**Comment by OrdinaryGamer564** [comment]
I used x86 Native Tools Command Prompt for VS 2017

**Comment by annulen** [comment]
Could you redirect output of build-qtwebkit-conan.py into file and attach it here?

**Comment by OrdinaryGamer564** [comment]
> Could you redirect output of build-qtwebkit-conan.py into file and attach it here?
Here is the build output 
[build.log](https://github.com/qtwebkit/qtwebkit/files/5870475/build.log)

**Comment by victorqhong** [comment]
I ran into this issue. I figured out the problem was that the bison and flex dependencies[0] pull in an old version of msys2 which cannot be used due to missing (i.e. outdated) packages.

I worked around the issue by commenting out the dependencies and installing bison and flex separately[1].

[0] - https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/Tools/qt/conanfile.py#L81-L84
[1] - https://github.com/lexxmark/winflexbison
