### ISSUE TITLE
fail to build qtwebkit QT5.14.2 mingw 64: ICU issue?

### ISSUE THREAD

**Issue by ThpMop** [qtwebkit/qtwebkit#1048]
Hello 
I'm trying to build qtwebkit on windows 10 with mingw 64 bits and QT 5.14.2. (I'm obliged to use mingw for my project)
I followed the instructions found on https://github.com/qtwebkit/qtwebkit/wiki

I run the following command: 
py Tools\qt\build-qtwebkit-conan.py --qt=C:\Qt\5.14.2\mingw73_64 --install --cmakeargs "MinGW Makefiles -DCMAKE_C_COMPILER=C:/Qt/Tools/mingw730_64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Qt/Tools/mingw730_64/bin/g++.exe" --profile "tp_qtwebkit_gcc_x86_64.txt" --arch=x86_64

I also tried without the cmake arg "MinGW Makefiles"  with the same result.

The buils fails on ICU with the following message at the beginning of build:

icu/65.1@qtproject/stable: WARN: Package binary is corrupted, removing: 251ea494cf518faa004e6917c321733c6f6bbfae
conanfile.py (qtwebkit/5.212.0-alpha4): Installing package

then, at the end of the build process : 

Unpacking ../../source/data/in/icudt65l.dat and generating out/tmp/icudata.lst (list of data files)
make[1]: *** [Makefile:257: out/tmp/icudata.lst] Error 127
make[1]: *** Attente des tâches non terminées....
make: *** [Makefile:153: all-recursive] Error 2
icu/65.1@qtproject/stable:
icu/65.1@qtproject/stable: ERROR: Package '251ea494cf518faa004e6917c321733c6f6bbfae' build failed
icu/65.1@qtproject/stable: WARN: Build folder C:\.conan\6428a1\1
ERROR:
        ConanException: Error 2 while executing make --silent -j 8

I also tried this simple command: conan install icu/65.1@qtproject/stable --build=icu
the result is 
beginning:
icu/65.1@qtproject/stable: Forced build from source
Installing package: icu/65.1@qtproject/stable
Requirements
    icu/65.1@qtproject/stable from 'qtproject' - Cache
Packages
    icu/65.1@qtproject/stable:60545ce1272b5d820af27669624c83f3e604888d - Build
Build requirements
    msys2_installer/20161025@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    msys2_installer/20161025@bincrafters/stable:3cbd862cb7a3ea47ed1220dc027f344262d5224f - Cache

Installing (downloading, building) binaries...
msys2_installer/20161025@bincrafters/stable: Already installed!
msys2_installer/20161025@bincrafters/stable: Creating MSYS_ROOT env var : C:\.conan\ec0916\1
msys2_installer/20161025@bincrafters/stable: Creating MSYS_BIN env var : C:\.conan\ec0916\1\usr\bin
msys2_installer/20161025@bincrafters/stable: Appending PATH env var with : C:\.conan\ec0916\1\usr\bin
icu/65.1@qtproject/stable: Applying build-requirement: msys2_installer/20161025@bincrafters/stable
icu/65.1@qtproject/stable: WARN: Build folder is dirty, removing it: C:\.conan\b9f6bd\1
icu/65.1@qtproject/stable: Copying sources to build folder
icu/65.1@qtproject/stable: Building your package in C:\.conan\b9f6bd\1
icu/65.1@qtproject/stable: Generator txt created conanbuildinfo.txt
icu/65.1@qtproject/stable: Calling build()
.................................................................end
Detected MSYS version: 2
mkdir ./out/build
mkdir ./out/build/icudt65l
Unpacking ../../source/data/in/icudt65l.dat and generating out/tmp/icudata.lst (list of data files)
make[1]: *** [Makefile:257: out/tmp/icudata.lst] Error 127
make[1]: *** Attente des tâches non terminées....
make: *** [Makefile:153: all-recursive] Error 2
icu/65.1@qtproject/stable:
icu/65.1@qtproject/stable: ERROR: Package '60545ce1272b5d820af27669624c83f3e604888d' build failed
icu/65.1@qtproject/stable: WARN: Build folder C:\.conan\b9f6bd\1
ERROR:
        ConanException: Error 2 while executing make --silent -j 8

Is there something I'm missing in the process ?

Thank you very much for your help
Thierry

The profiles is: 
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release
[options]
[build_requires]
[env]

**Comment by ThpMop** [comment]
Hello
it seems that the problem is with the copy of icudt65l.dat that are well created but not copied in out/tmp/icudata.lst that I don't find. 

Any suggestion is welcome.
Thank you 
Thierry
Unpacking ../../source/data/in/icudt65l.dat and generating out/tmp/icudata.lst (list of data files)
make[1]: *** [Makefile:257: out/tmp/icudata.lst] Error 127

**Comment by annulen** [comment]
I think main issue here is "icu/65.1@qtproject/stable: WARN: Package binary is corrupted, removing: 251ea494cf518faa004e6917c321733c6f6bbfae" - it is supposed that binary package should be used, as building packages can result in various build issues depending on your system configuration which I'd prefer not to solve. What Conan version are you using? Does this error reproduce if you remove `.conan` directory in your home and retry?

**Comment by ThpMop** [comment]
Thank you for your suggestion,
the Conan version I use is 1.33.1

Before using Conan I tried the "easy way" to copy in C:\Qt\5.14.2\mingw73_64 the binaries and files found on QT downloads  (qtwebkit-Windows-Windows_10-Mingw-Windows-Windows_10-X86_64). I was able to build my Qt5 project but the application crashes when I call Webview.

Then I decided to use the Conan to install qtwebkit in QT5.
Is it possible to force Conan to use binaries instead of building?
It seems that the problem I had with ICU was that Conan found the file dirty before deciding to build.

here is the message:  icu/65.1@qtproject/stable: WARN: Package binary is corrupted, removing: 665a93ab231549848b3eb213201f15f18790f418
conanfile.py (qtwebkit/5.212.0-alpha4): Installing package

I looked for icu binaries for mingw73_64 without success. It seems there is no binary package available for icu in Conan:
https://conan.io/center/icu?version=65.1&os=Windows&tab=configuration

this being said other libraries such as libxslt, sqlite3... are apparently properly downloaded/build.

The same error reproduce after removing .conan directory from my home directory.
Thank you very much for your help.
Thierry

mkdir ./out/build
mkdir ./out/build/icudt65l
Unpacking ../../source/data/in/icudt65l.dat and generating out/tmp/icudata.lst (list of data files)
make[1]: *** [Makefile:257: out/tmp/icudata.lst] Error 127
make[1]: *** Attente des tâches non terminées....
make: *** [Makefile:153: all-recursive] Error 2
icu/65.1@qtproject/stable:
icu/65.1@qtproject/stable: ERROR: Package '665a93ab231549848b3eb213201f15f18790f418' build failed
icu/65.1@qtproject/stable: WARN: Build folder C:\.conan\fd046f\1
ERROR:
        ConanException: Error 2 while executing make --silent -j 8

command line used:
py Tools\qt\build-qtwebkit-conan.py --qt "C:/Qt/5.14.2/mingw73_64" --install --cmakeargs "MinGW Makefiles -DCMAKE_C_COMPILER=C:/Qt/Tools/mingw730_64/bin/gcc.exe  -DCMAKE_CXX_COMPILER=C:/Qt/Tools/mingw730_64/bin/g++.exe" --profile "qtwebkit_gcc_x86_64.txt"

profile used:
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.3
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release
[options]
[build_requires]
[env]

![ConanCenter_icu65 1](https://user-images.githubusercontent.com/79049829/108041567-025f9080-703f-11eb-9443-80710f42197b.png)

**Comment by annulen** [comment]
Conan Center has nothing to do with this, recipes and binaries are downloaded from https://bintray.com/beta/#/qtproject/

**Comment by annulen** [comment]
>I was able to build my Qt5 project but the application crashes when I call Webview

It should work fine with Qt 5.14.1

**Comment by ThpMop** [comment]
Thank you very much I'll give a try with Qt 5.14.1 I'll let you know.
Thx

**Comment by ThpMop** [comment]
I'm installing 5.14.1

Do you recommend qtwebkit-Windows-Windows_10-Mingw-Windows-Windows_10-X86_64 from Qt downloads 
https://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/

or another source of binaries ?
Thx

**Comment by annulen** [comment]
https://github.com/qtwebkit/qtwebkit/releases/tag/qtwebkit-5.212.0-alpha4

**Comment by ThpMop** [comment]
Hello,
bad news, the project I'm using does not build with QT 5.14.1. So I cannot try the qtwebkit binaries with it.
I have to come back on Qt 5.14.2.

Do you have any suggestion to to the job with Conan and how to fix the ICU issue?

Thank you again for your help.
Thierry

**Comment by annulen** [comment]
Please try Qt 5.15.1 and http://download.qt.io/snapshots/ci/qtwebkit/5.212/1600797502/

**Comment by ThpMop** [comment]
OK let's go and try with Qt 5.15.1
Thx

**Comment by ThpMop** [comment]
Qt 5.15.1 supports mingw8.1 compiler is this OK with qtwebkit snapshot you suggest ?
Thx

**Comment by annulen** [comment]
Yes, snapshot is built with mingw 8.1

**Comment by ThpMop** [comment]
Thank you very much, your solution build properly and the app does not crash.

Qt 5.15.1 and http://download.qt.io/snapshots/ci/qtwebkit/5.212/1600797502/

Now I can code and see if it works well...

I have now to fix some issues with my first test
    QWebView *view = new QWebView(parent);
    view->load(QUrl("http://127.0.0.1:1880/ui"));
    view->resize(this->width(), this->height() );
    view->show();

The view is opened but the page is not displayed... I have now to learn how to make good use of qtwebkit

Thank you again for your effective help
Thierry
