### ISSUE TITLE
QtWebKit build on new apple silicon.

### ISSUE THREAD

**Issue by XankurX** [qtwebkit/qtwebkit#1052]
Hello @annulen ,

I am just wondering does the QtWebKit-reloaded's build system already equipped for building the project with the new apple silicon chipset?
If not, is there a task that is tracking this activity?

Regards,
Ankur

**Comment by annulen** [comment]
Please try #1047

**Comment by wrobelda** [comment]
@XankurX have you tried the #1047 patch?

**Comment by XankurX** [comment]
> @XankurX have you tried the #1047 patch?

Sorry, Didn't see this question.
Yes, I could build it with the patch.

I think I had to make 1 tiny extra modification in Source/JavaScriptCore/jsc.cpp
where I had to specify the namespace on one of the template function on line 192 with this:
bool isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, SlotVisitor& visitor) override

Are you facing difficulty building it?
