### ISSUE TITLE
[Question]: KDE's libkgapi with QtWebKit instead of QtWebEngine

### ISSUE THREAD

**Issue by RJVB** [qtwebkit/qtwebkit#1064]
(Excuse the initial misfire; a cat jumped on my keyboard causing the issue to be created in the midst of typing the title...)

I just discovered that despite old, QtWebKit-based browsers can still log into GMail, GDrive etc while a priori much more recent versions of QtWebEngine are being rejected.

That begs the question if libkgapi's authentication widget couldn't be made compatible with QtWebKit, and how feasible/frustrating such an endeavour would be for someone who has basically zero knowledge of either framework.
I'm asking here because I know the KDE PIM developers' complete desinterest of anything other than QtWebEngine... :(

FWIW, the web engine stuff (of the version I am currently using) is in
https://invent.kde.org/pim/libkgapi/-/blob/68145be73f23e2f33dcbc8b2d3b510083fd1669d/src/core/ui/authwidget_p.cpp
https://invent.kde.org/pim/libkgapi/-/blob/68145be73f23e2f33dcbc8b2d3b510083fd1669d/src/core/ui/authwidget_p.h

**Comment by annulen** [comment]
I think KDE PIM used to use QtWebKit in the past, so looking through git log may help you to restore relevant code

**Comment by RJVB** [comment]
>I think KDE PIM used to use QtWebKit in the past, so looking through git log may help you to restore relevant code

Indeed, and with a bit of luck the code is preserved enough to do a more or less straight "reversed backport".

I also noticed that this particular library ditched QWE too very recently, handing off the authentication request to the browser instead. Not the most elegant either, probably the most future-proof one...

**Comment by RJVB** [comment]
So... getting a much more recent version to compile that uses the browser didn't help much as the Akonadi service is not sanctioned to access the GDrive anymore. As a result, I did spend a bit of time to port the older version to QtWebkit which was relatively straightforward but evidently just as futile.
(FWIW, I do get a `loadFinished` with failure indication at the end, but for no clear reason and apparently without hampering the authentication procedure.)
