### ISSUE TITLE
Building broken on branch qtwebkit-stable

### ISSUE THREAD

**Issue by infinitesnow** [qtwebkit/qtwebkit#1065]
Trying to build with c++/g++ 7 on Ubuntu 18 with custom built Qt5.14, build fails with multiple errors which seem to point to missing includes (for example, `function` is not a member of `std`). `5.212` builds fine.

**Comment by annulen** [comment]
Please use qtwebkit-5.212 branch instead, qtwebkit-stable is internal branch
