### ISSUE TITLE
Font not found by qtwebkit when duplicate font family files exist

### ISSUE THREAD

**Issue by mnutt** [qtwebkit/qtwebkit#1066]
I'm seeing an issue where I (unfortunately) have multiple fonts installed that have the same font family name but differ based on their `foundry` attribute. This manifests in qt as `QFontDatabase::families()` returning each family with the foundry appended:

> If the font family is available from two or more foundries the foundry name is included in the family name; for example: "Helvetica [Adobe]" and "Helvetica [Cronyx]". When you specify a family, you can either use the old hyphenated "foundry-family" format or the bracketed "family [foundry]" format; for example: "Cronyx-Helvetica" or "Helvetica [Cronyx]". If the family has a foundry it is always returned using the bracketed format, as is the case with the value returned by families().

(from [QFontDatabase docs](https://doc.qt.io/qt-5/qfontdatabase.html))

When I try to use the font in qtwebkit, it calls [`QFontDatabase::hasFamily`](https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/Source/WebCore/platform/graphics/qt/FontCacheQt.cpp#L99) which does some alias resolution but doesn't seem to match non-foundry-appended families to foundry-appended families.

The result seems to be that if my webpage specifies `font-family: Helvetica` and I have a single Helvetica font installed it'll work fine, but if I have two Helvetica fonts installed, it'll never match `Helvetica [Adobe]` or `Helvetica [Cronyx]`. But I'm not sure where the issue resides. It feels like qt should register the first duplicate with the non-foundry-prepended-name _also_?

**Comment by annulen** [comment]
So you suppose that QFontDatabase::hasFamily doesn't work correctly, right? If so, it should be possible to reproduce it without qtwebkit and create bug report for QtGui.

**Comment by mnutt** [comment]
It looks like it's this: https://bugreports.qt.io/browse/QTBUG-89068

While they seem unconcerned since it's an internal method, it looks like qt is probably the right place for a fix, right?

**Comment by annulen** [comment]
Sure. Also it would be great to make QFontDatabase::hasFamily public when it's fixed ;)

Though it's probably worthwhile to add workaround to QtWebKit as well for unfixed Qt versions, but code should be the same in both places.

**Comment by mnutt** [comment]
Thanks, I'll close this out and see if there's some way to fix it on the qt side.
