### ISSUE TITLE
==> ERROR: A failure occurred in build().

### ISSUE THREAD

**Issue by overtube** [qtwebkit/qtwebkit#1091]
collect2: error: ld returned 1 exit status
make[2]: *** [Source/WebKit/CMakeFiles/WebKit.dir/build.make:2030: lib/libQt5WebKit.so.5.212.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1522: Source/WebKit/CMakeFiles/WebKit.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by annulen** [comment]
This is not an actual linking error. The latter is located higher in build log.
