### ISSUE TITLE
Error during compiling FileSystemPOSIX.cpp

### ISSUE THREAD

**Issue by TCH68k** [qtwebkit/qtwebkit#1093]
This is a bugreport for [https://github.com/movableink/webkit](https://github.com/movableink/webkit), where i cannot open issues.

During compiling, i get this error message:
```
 23%] Built target WebCoreTestSupportBindings
/opt/webkit/Source/WTF/wtf/posix/FileSystemPOSIX.cpp: In function ‘std::optional<WTF::CString> WTF::FileSystemImpl::fileID(WTF::FileSystemImpl::PlatformFileHandle)’:
/opt/webkit/Source/WTF/wtf/posix/FileSystemPOSIX.cpp:199:21: error: could not convert ‘fileInfo.stat::st_ino’ from ‘__ino_t’ {aka ‘long unsigned int’} to ‘std::optional<WTF::CString>’
  199 |     return fileInfo.st_ino;
      |            ~~~~~~~~~^~~~~~
      |                     |
      |                     __ino_t {aka long unsigned int}
make[2]: *** [Source/WTF/wtf/CMakeFiles/WTF.dir/build.make:1981: Source/WTF/wtf/CMakeFiles/WTF.dir/posix/FileSystemPOSIX.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:749: Source/WTF/wtf/CMakeFiles/WTF.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

OS is Debian 11, AMD64. Compiler is GCC 10. Qt is 5.15.2.

I've made a patch for it: [http://oscomp.hu/depot/FileSystemPOSIX.patch](http://oscomp.hu/depot/FileSystemPOSIX.patch)

**Comment by annulen** [comment]
Do you know how to make PRs? There should be a tutorial somewhere I guess.

Anyway, if you still resort to patches, please make them fully formatted (in `git format-patch` sense) so they contain author information and could be `git am`'ed.

**Comment by TCH68k** [comment]
I don't even understand what you are saying. I am totally unfamiliar with `git`; all i know is `git clone` and `git pull`.
If the patch is not usable, then it's one line to change in `Source/WTF/wtf/posix/FileSystemPOSIX.cpp` at line 199, from
```
return fileInfo.st_ino;
```
to
```
return WTF::CString(std::to_string(fileInfo.st_ino).c_str());
```

**Comment by TCH68k** [comment]
Fixed in the other repo's test branch during IRC session.
