### ISSUE TITLE
Error during final linking.

### ISSUE THREAD

**Issue by TCH68k** [qtwebkit/qtwebkit#1095]
This is a bugreport for [https://github.com/movableink/webkit](https://github.com/movableink/webkit), where i cannot open issues.

During the final linking, i get this error message:
```
/usr/bin/ld: CMakeFiles/WebKitLegacy.dir/qt/Api/qwebelement.cpp.o:(.data.rel.ro._ZTIN7WebCore26CachedScriptSourceProviderE[_ZTIN7WebCore26CachedScriptSourceProviderE]+0x18): undefined reference to `typeinfo for JSC::SourceProvider'
/usr/bin/ld: ../../lib/../Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/ImageDecoderGStreamer.cpp.o: in function `WebCore::ImageDecoderGStreamer::pushEncodedData(WebCore::FragmentedSharedBuffer const&)':
/opt/webkit/Source/WebCore/platform/graphics/gstreamer/ImageDecoderGStreamer.cpp:259: undefined reference to `WebCore::SharedBuffer::createGBytes() const'
collect2: error: ld returned 1 exit status
make[2]: *** [Source/WebKitLegacy/CMakeFiles/WebKitLegacy.dir/build.make:1016: lib/libQt5WebKit.so.5.212.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1537: Source/WebKitLegacy/CMakeFiles/WebKitLegacy.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```
OS is Debian 11, AMD64. Compiler is GCC 10. Qt is 5.15.2.

**Comment by annulen** [comment]
It's the same issue as #1094

**Comment by TCH68k** [comment]
The second error message can be the same, but the first?
```
/usr/bin/ld: CMakeFiles/WebKitLegacy.dir/qt/Api/qwebelement.cpp.o:(.data.rel.ro._ZTIN7WebCore26CachedScriptSourceProviderE[_ZTIN7WebCore26CachedScriptSourceProviderE]+0x18): undefined reference to `typeinfo for JSC::SourceProvider'
```
JSC is the JavaSriptCore, that has nothing to do with GStreamer. Please reopen this issue, as it is definetely not a duplicate.

**Comment by annulen** [comment]
First error should have been fixed by b71da9737d7237803d2b90cb16a5e1d2be07f1e5, if it's in place then I have no idea

**Comment by TCH68k** [comment]
That fix is from last year. I've cloned the repo in the last few days.

Which repository is that? This, or the other one: [https://github.com/movableink/webkit](https://github.com/movableink/webkit) ? Because i've used the one i've linked.
Both at [https://github.com/qtwebkit/qtwebkit](https://github.com/qtwebkit/qtwebkit) and [https://github.com/annulen/webkit](https://github.com/annulen/webkit) there is a warning, that the repo is obsolete and users should use [https://github.com/movableink/webkit](https://github.com/movableink/webkit) and i did that.

**Comment by annulen** [comment]
If commit hash is the same it doesn't really matter which repository is it from. Git repos can easily share commits between clones/forks of each other.

**Comment by TCH68k** [comment]
How can i check this if i have this commit?

**Comment by annulen** [comment]
In `Source/JavaScriptCore/parser/SourceProvider.cpp` there should be lines
```c++
#if PLATFORM(QT)
StringSourceProvider::~StringSourceProvider() = default;
#endif
```

**Comment by TCH68k** [comment]
Yes, you are right, it is there. But, then why it can't find the reference? If the macro `PLATFORM(QT)` gives back false, then a lot of errors should occur, right?

**Comment by TCH68k** [comment]
It does not help, if i comment out the macro and leave just the declaration.

**Comment by TCH68k** [comment]
Fixed in the other repo's test branch during IRC session.
