### ISSUE TITLE
Static linking of QtWebKit on MINGW and other questions

### ISSUE THREAD

**Issue by quarcko** [qtwebkit/qtwebkit#1104]
Hi,

So my MINGW build of webkit is quite a success and as a last step i wanted to try is to statically link it with external dependencies, so final release is much nicer and tidier.

So i looked into your released binaries, and there is not that much dll's as in mine.

i tried in CMAKE changing linking from *****.dll.a to *****.a versions of libraries,
but linking fails with too many errors, where dynamic linking is working all right and no complains during runtime.
What am i missing? What you did to statically link it with other libs (harfbuzz, etc...)

also - your builds contains some *.exe files that are not produced by my build:
QtWebNetworkProcess.exe
QtWebProcess.exe
QtWebStorageProcess.exe

Shoud i be concerned abotu these?

**Comment by annulen** [comment]
I was using [Conan](https://github.com/qtwebkit/qtwebkit/wiki/Conan) to build and link all dependencies on Windows. But there was no harfbuzz yet in 5.212.

>also - your builds contains some *.exe files that are not produced by my build

Those are only needed for multiprocess mode so you don't need them.

**Comment by quarcko** [comment]
Ok, clear. I managed to get rid of some dll's but not all of them,
because, if i want to link to static libharfbuzz.a, then i also have to pass to linker 
all other *.a libraries that harfbuzz depends on. So probably not worth it.

Closing, and thank you for all support on this and other questions!
