### ISSUE TITLE
fails to compile against icu4c 75.1 

### ISSUE THREAD

**Issue by oneforall2** [qtwebkit/qtwebkit#1105]
[  4%] Built target WebKit2-forwarding-headers
In file included from /usr/include/unicode/uset.h:36,
                 from /usr/include/unicode/unorm2.h:35,
                 from /usr/include/unicode/unorm.h:25,
                 from /usr/include/unicode/ucol.h:17,
                 from /tmp/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/unicode/icu/CollatorICU.cpp:37:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
  573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
  583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {

**Comment by oneforall2** [comment]
Why us it closed when there is no fix yet ?

**Comment by annulen** [comment]
It's not closed

**Comment by mozo78** [comment]
I can't compile it on Arch:

`:: unable to satisfy dependency 'libicuuc.so=74-64' required by qt5-webkit`

`:: unable to satisfy dependency 'libicui18n.so=74-64' required by qt5-webkit`

**Comment by FabioLolix** [comment]
```
I can't compile it on Arch:

:: unable to satisfy dependency 'libicuuc.so=74-64' required by qt5-webkit

:: unable to satisfy dependency 'libicui18n.so=74-64' required by qt5-webkit
```

That is not a compiling problem, it is the typical error when you install an old build which depends on versioned .so in in depends=()

**Comment by mozo78** [comment]
I don't know if it's old - I'm using AUR and there's no newer package.

**Comment by FabioLolix** [comment]
> I'm using AUR and there's no newer package.

You are either re-installing an old build or using a repo with pre-builds packages (old too since it don't build with icu 75), the problem you posted is from an old package; not for compiling from source

I have introduced the depends on `libicuuc.so` explicity so people don't keep a broken package which lead to other runtime and packaging issues

> I don't know if it's old

It is old because it want a library that is no longer present

**Comment by mozo78** [comment]
> > I'm using AUR and there's no newer package.
> 
> You are either re-installing an old build or using a repo with pre-builds packages (old too since it don't build with icu 75), the problem you posted is from an old package; not for compiling from source
> 
> I have introduced the depends on `libicuuc.so` explicity so people don't keep a broken package which lead to other runtime and packaging issues
> 
> > I don't know if it's old
> 
> It is old because it want a library that is no longer present

I'm installing it from here:
https://aur.archlinux.org/packages/qt5-webkit

`trizen -S qt5-webkit`

Where should I install it from?

I uninstalled the older version for I couldn't update my system. Now, after I updated, I'm trying to install qt5-webkit again but I can't.

**Comment by FabioLolix** [comment]
> I'm installing it from here:
https://aur.archlinux.org/packages/qt5-webkit
trizen -S qt5-webkit

Likely trizen prompt for re-installing the old package build

> I'm trying to install qt5-webkit again but I can't.

I know, there is this issue and and have been posted ad nauseam on the AURWeb page

If you have some patience I'm in the process of uploading a pre-build package of https://aur.archlinux.org/packages/qt5-webkit-movableink-git on my sourceforge; check comments on https://aur.archlinux.org/packages/qt5-webkit for more

**Comment by mozo78** [comment]
I checked the comments but I can't understand anything for my English is relatively bad. I tried some suggested fixes and I gave up.
A pre-build package should be great. I'm not in a hurry at all so I'll wait, thank you very much :)

**Comment by HLFH** [comment]
@FabioLolix It'd be great to have `qt5-webkit-movableink` (without the -git) on the AUR.

**Comment by FabioLolix** [comment]
@HLFH AFAIK there isn't a buildable fixed release yet; I already have a local pkgbuild for that when is ready

**Comment by oneforall2** [comment]
so any word on when this will be updated to compile against icu4c 75.1 ?

**Comment by annulen** [comment]
Fixed in 756e1c8f23dc2720471298281c421c0076d02df8

**Comment by annulen** [comment]
Also, it seems like 756e1c8 makes [`icu68.patch`](https://aur.archlinux.org/cgit/aur.git/tree/icu68.patch?h=qt5-webkit) unnecessary.

**Comment by Universebenzene** [comment]
> Also, it seems like [756e1c8](https://github.com/qtwebkit/qtwebkit/commit/756e1c8f23dc2720471298281c421c0076d02df8) makes [`icu68.patch`](https://aur.archlinux.org/cgit/aur.git/tree/icu68.patch?h=qt5-webkit) unnecessary.

As [this comment](https://aur.archlinux.org/packages/qt5-webkit#comment-975351) says, `icu68.patch` is still needed.

**Comment by annulen** [comment]
Comment for people in AUR (I'm too lazy to register there):

AFAIU there can be only one installed version of ICU in Arch at any moment of time, so I guess it would make more sense to build base system ICU with disabled version suffices (`--disable-renaming`). In that case most of software, including any WebKit ports, would just continue to work after ICU updates without rebuilding.
