### ISSUE TITLE
Prepare Linux buildbot image

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#130]
We need to construct (reasonably) minimal system image which can build QtWebKit and run layout tests according to instruction https://github.com/annulen/webkit/wiki/Running-Layout-Tests.
* Best candidate for base system is Debian 10
* Script `Tools/qt/install-dependencies` installs some necessary packages (may be a bit incomplete/outdated)
* When running `Tools/Scripts/update-qtwebkit-libs` there may be compilation issues, and bits from https://github.com/annulen/my-webkit-hacks/commit/a3dc60f070c3fcd66b6354d0a2aaf716bb18c8e7 may help
* If everything is done right, most tests will pass, and remaining failures will be fixed by updating test expectations

**Comment by ariya** [comment]
What's the status of the .deb package? How can I help?

**Comment by annulen** [comment]
@ariya Sorry, I'm not planning to work on deb package for build product (it's actually trivial to make .deb out of installed binaries, but I don't know much about Debian's policies and don't want to deal with bureaucracy).

This task is about reproducible build environment only.

**Comment by annulen** [comment]
But I can make ebuild for Gentoo if you like :)

**Comment by annulen** [comment]
https://github.com/qtwebkit/qbat2 provides suitable Docker image (pre-built version can be pulled from https://github.com/orgs/qtwebkit/packages/container/package/qbat2-base)
