### ISSUE TITLE
Support for MediaSource Extensions on Windows

### ISSUE THREAD

**Issue by Phoenox** [qtwebkit/qtwebkit#334]
I've built WebKit for Qt on Windows and tried it out by creating a simple QWebView.
When I try to view HTML5 videos using the Media Source Extensions, the application crashes reproducibly.
Also, the [YouTube HTML5 test page](https://www.youtube.com/html5) lists "Media Source Extensions", "MSE & H.264" and "MSE & WebM VP9" as **not supported**.

In the table "Comparison with QtWebKit 5.6", MediaSource is listed as "Experimental with GStreamer".
I am now wondering what the current state of the MediaSource support is. Will this be improved in the near future?

**Comment by annulen** [comment]
You need to enable `QWebSettings::MediaSourceEnabled` via `QWebSettings::setAttribute`

**Comment by annulen** [comment]
Oops, sorry. MSE is currently supported only with GStreamer player, and Windows build uses QtMultimedia by default. It may be possible that you can just rebuild the whole thing with GStreamer and it will work out of the box, but I'm not aware if anyone tried that so far.

**Comment by annulen** [comment]
In case you are interested in overall situation with options for video playback on Windows, here they are:
* QtMultimedia (used now).
   * Pros: part of Qt, supports native codecs, small library size (as system APIs are used)
   * Cons: API is too limited to support MSE, module does not receive a lot of development and has many bugs, MediaFoundation backend (non-deprecated native API) is unfinished and does not receive much development
* MediaFoundation player in WebKit - implemented directly on top of MediaFoundation without Qt involved, maintained by WebKit developers.
    * Pros: only system libraries are used, supports native codecs, probably fastest as there are no intermediate layers
    * Cons: MSE is not implemented and I'm not aware of any ongoing work on this, however it can be that there are interested parties outside of Qt world which may be interested in getting this available in WebKit, e.g. for use in WinCairo port
* GStreamer
    * Pros: the most advanced backend of three, supports not only MSE, but EME (draft), WebAudio, MediaStream/WebRTC (work in progress)
    * Cons: adds a lot of library dependencies, may be hard to set up building all this stuff on Windows, support only obsolete DirectShow API for video rendering, don't know if it uses system codecs or requires repective gstreamer plugin to be installed. In general, Windows is far from being primary target platform for GStreamer developers, they mostly focus on Linux

**Comment by Phoenox** [comment]
Thank you for this information.

I tried building WebKit with GStreamer as suggested. I installed [this GStreamer package](https://gstreamer.freedesktop.org/data/pkg/windows/1.9.90/gstreamer-1.0-devel-x86-1.9.90.msi) and got CMake to use it. Also, I set USE_GSTREAMER=On and USE_QT_MULTIMEDIA=Off.
With these changes, the build process completed and I got a version of WebKit that requires the GStreamer DLLs to work.

However, when I now try the [Youtube HTML test page](https://www.youtube.com/html5), none of the codecs (not even HTMLVideoElement) is supported. Accordingly, I am not able to watch any video, they are always just black boxes.

The fact that even HTMLVideoElement is not supported with the GStreamer version of WebKit suggests that something went wrong in using GStreamer, however, I cannot figure out what that could be.

Do you have any suggestions how I could debug this?

**Comment by annulen** [comment]
Could you post cmakeconfig.h file from the root of build directory?

**Comment by annulen** [comment]
Also it can be that GStreamer cannot load required plugin(s), on Linux they are taken from system locations, or when it's compiled with jhbuild there is some environment variable magic

**Comment by Phoenox** [comment]
Here is the cmakeconfig.h (I renamed it with a .txt extension so I could upload it):
[cmakeconfig.h.txt](https://github.com/annulen/webkit/files/527448/cmakeconfig.h.txt)

**Comment by annulen** [comment]
cmakeconfig.h looks good, please check if gstreamer can find and load its plugins

**Comment by annulen** [comment]
You can also try video on other pages, e.g. http://camendesign.com/code/video_for_everybody/test.html

**Comment by annulen** [comment]
Could you post results of opening this HTML file?
```html
<!DOCTYPE html>
<html>
    <head>
        <title>canPlayType test page</title>
        <script type="text/javascript">

function fillTable()
{
    var vid = document.createElement('video');
    var tbl = document.getElementById('canPlayTable');

    function isSupported(mime, codecs)
    {
        if (!codecs) {
            return vid.canPlayType(mime);
        }
        return vid.canPlayType(mime + ';codecs="' + codecs + '"');
    }

    function addCell(row, col, text)
    {
        var cell = row.insertCell(col);
        cell.appendChild(document.createTextNode(text));
    }

    function addRow(mime, codecs)
    {
        var row = tbl.insertRow(tbl.rows.length);
        addCell(row, 0, mime);
        addCell(row, 1, codecs || "");
        addCell(row, 2, isSupported(mime, codecs) || "no");
    }

    addRow('video/mp4');
    addRow('video/mp4', 'avc1.42E01E, mp4a.40.2');
    addRow('application/x-mpegurl');
    addRow('application/vnd.apple.mpegurl');
    addRow('application/x-mpegurl', 'avc1.42E01E, mp4a.40.2');
    addRow('video/webm');
    addRow('video/webm', 'vp8, vorbis');
    addRow('video/mpeg');
    addRow('audio/mpeg');
    addRow('audio/wave');
    addRow('audio/ogg');
    addRow('audio/ogg', 'vorbis');
    addRow('audio/ogg', 'flac');
    addRow('audio/flac');
}
        </script>
    </head>
    <body onload="fillTable()">
        <table id="canPlayTable" width="700px" border="1" cellpadding="2">
            <tr>
                <th>Type</th>
                <th>Codecs</th>
                <th>Supported</th>
            </tr>
        </table>
    </body>
</html>
```

**Comment by Phoenox** [comment]
The results of the html page is:

![canplaytable](https://cloud.githubusercontent.com/assets/3393556/19432794/4d7f7af6-945e-11e6-9023-ce4e62d9b7d6.png)

In my normal browser (Chrome) the table is created as expected (=with multiple entries, not just one line).

**Comment by annulen** [comment]
Could you post console output from loading this page? It looks like exception is thrown when `canPlayType` is invoked for the first time, I'd like to know what it says

**Comment by Phoenox** [comment]
It says:
> TypeError: vid.canPlayType is not a function. (In 'vid.canPlayType(mime)', 'vid.canPlayType' is undefined)

**Comment by annulen** [comment]
In your cmakeconfig.h I see that ENABLE_VIDEO is 1, so `canPlayType` must be defined. Have you rebuilt QtWebKit from scratch when switching to GStreamer?

**Comment by Phoenox** [comment]
Yes, I've even deleted the whole build directory.

**Comment by annulen** [comment]
In build directory find file `DerivedSources/WebCore/JSHTMLMediaElement.cpp`, if it exists ensure that line defining `canPlayType` is compiled e.g. by placing `#error` preprocessor directive near

**Comment by annulen** [comment]
I still suspect you are compiling with VIDEO disabled, but don't see how could it happen

**Comment by Phoenox** [comment]
The file ``DerivedSources/WebCore/JSHTMLMediaElement.cpp`` does exist, but it does not contain a line defining ``canPlayType``.

**Comment by annulen** [comment]
Could you post contents of that file? This is not right

**Comment by Phoenox** [comment]
Strange, I've removed the ``DerivedSources`` directory and rebuilt WebKit. Unfortunately, I didn't make a copy of the previously mentioned ``JSHTMLMediaElement.cpp``.
Now, the ``JSHTMLMediaElement.cpp`` defines ``canPlayType`` as expected. However, the resulting libraries show the same JavaScript error ('canPlayType' undefined).

I also followed your advise and added a ``#error`` preprocessor directive in in the ``JSHTMLMediaElement.cpp``. As expected, the build process aborts, so it seems the file is being compiled.

Here is the ``JSHTMLMediaElement.cpp``:
[JSHTMLMediaElement.cpp.txt](https://github.com/annulen/webkit/files/536206/JSHTMLMediaElement.cpp.txt)

**Comment by annulen** [comment]
Your JSHTMLMediaElement.cpp is identical to what I have here. Make sure that both MediaEnabled and MediaSourceEnabled attributes are turned on in qwebsettings

**Comment by Phoenox** [comment]
Yes, ``MediaEnabled`` and ``MediaSourceEnabled`` have already been set to ``true``.

Here's the full ``main.cpp`` I use for the application, although there's not much interesting in there:
[main.cpp.txt](https://github.com/annulen/webkit/files/536271/main.cpp.txt)

**Comment by annulen** [comment]
If in Inspector console you run `vid = document.createElement('video')`, does `vid` have any properties or methods related to media element, e.g. "play"?

https://dev.w3.org/html5/spec-preview/media-elements.html

**Comment by annulen** [comment]
(for the record, MediaEnabled is true by default, I just asked to make sure if you not changed it accidentally)

**Comment by Phoenox** [comment]
``vid`` has not the ``play`` property, but it has ``onplay``, ``onpause``, ``oncanplay``, ...

**Comment by annulen** [comment]
`vid.play` should return `function`...

**Comment by Phoenox** [comment]
Yes, it should be. However, it returns ``undefined``.

**Comment by annulen** [comment]
Maybe gstreamer or glib header pull in some macros that somehow break stuff, and it happens only on Windows. Obtain preprocessed sources for HTMLMediaElement.cpp and JSHTMLMediaElement.cpp and compare them with Qt Multimedia build (or just post them here and I'll try to compare with my Linux gstreamer build, and builds that other people have).

If this is not the case, I'm totally puzzled and would resort to plain step by step debugging

**Comment by annulen** [comment]
@Phoenox Could you share instructions how do you build QtWebKit with GStreamer on Windows, so other interested people could continue investigation? I can grant you access to wiki if you want

**Comment by Phoenox** [comment]
I'll just post the instructions here:

* Install GStreamer (a devel package from [here](https://gstreamer.freedesktop.org/data/pkg/windows/)) into a directory that does NOT contain spaces
* Checkout the QtWebKit repo into a directory that does NOT contain spaces
* Replace the FindGStreamer.cmake in Source/cmake with [this cmake file](https://github.com/annulen/webkit/files/618479/FindGStreamer.cmake.txt)
* Now this part is a bit hacky and could probably be optimized: I defined a lot of CMake variables so cmake finds GStreamer, e.g.
GSTREAMER_APP_INCLUDE_DIRS:PATH=D:/gstreamer/1.0/x86/include/gstreamer-1.0
GSTREAMER_APP_LIBRARIES:FILEPATH=D:/gstreamer/1.0/x86/lib/gstapp-1.0.lib
GSTREAMER_BASE_INCLUDE_DIRS:PATH=D:/gstreamer/1.0/x86/include/gstreamer-1.0
GSTREAMER_BASE_LIBRARIES:FILEPATH=D:/gstreamer/1.0/x86/lib/gstbase-1.0.lib
...
* Also set USE_GSTREAMER=1 and USE_QT_MULTIMEDIA=0
* The rest is the usual cmake + make build steps.

**Comment by rlatapy-gpsw** [comment]
Are these instructions still relevant ? I've trouble to build QtWebkit 5.212 with GStreamer backend.

**Comment by bagong** [comment]
Maybe contributing to a well defined build-environment is a more promising approach to get this going. I've made a PR to MSYS2 that allows to build QtWebkit alpha2 with mediasource extensions pretty easily (https://github.com/Alexpux/MINGW-packages/pull/2672), I've heard of somebody using MXE successfully. If you need a msvc environment, providing gstreamer as part of vcpkg first might be a promising first step (https://github.com/Microsoft/vcpkg/issues/1474)

**Comment by annulen** [comment]
@rlatapy-gpsw What trouble?

**Comment by rlatapy-gpsw** [comment]
I'll take a look at the PR thanks.
Calling build-webkit modified FindGStreamer.cmake and every cmake variables give me this error.
> -- Found GLIB: C:/gstreamer/1.0/x86_x64/include;C:/gstreamer/1.0/x86_x64/include (Required is at least version "2.36")
-- Checking for module 'gstreamer-1.0'
--
-- Checking for module 'gstreamer-base-1.0'
--
-- Checking for module 'gstreamer-app-1.0'
--
-- Checking for module 'gstreamer-audio-1.0'
--
-- Checking for module 'gstreamer-fft-1.0'
--
-- Checking for module 'gstreamer-GL-1.0'
--
-- Checking for module 'gstreamer-mpegts-1.0'
--
-- Checking for module 'gstreamer-pbutils-1.0'
--
-- Checking for module 'gstreamer-tag-1.0'
--
-- Checking for module 'gstreamer-video-1.0'
--
-- Found GStreamer: C:/gstreamer/1.0/x86_x64/include (Required is at least version "1.0.3")
CMake Error at Source/cmake/OptionsQt.cmake:667 (message):
  Video playback requires the following GStreamer libraries: app, pbutils,
  tag, video.  Please check your gst-plugins-base installation.
Call Stack (most recent call first):
  Source/cmake/WebKitCommon.cmake:50 (include)
  CMakeLists.txt:135 (include)

**Comment by annulen** [comment]
Did you install all components of GStreamer? At least one component from the list is missing

What does `grep PC_GSTREAMER CMakeCache.txt` show?

**Comment by rlatapy-gpsw** [comment]
I installed the latest devel package (complete). Here is the grep: [PC_GSTREAMER.txt](https://github.com/annulen/webkit/files/1165324/PC_GSTREAMER.txt)
It looks like it doesnt found anything, I guess paths are wrong ?
`perl Tools\Scripts\build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=c:\Qt\Qt5.6.0_msvc2015_64\5.6\msvc2015_64 -DENABLE_API_TEST=OFF -DUSE_GSTREAMER=ON -DUSE_MEDIA_FOUNDATION=OFF -DENABLE_MEDIA_SOURCE=ON -DPKG_CONFIG_EXECUTABLE=C:\pkg-config\pkg-config.exe -DGSTREAMER_APP_INCLUDE_DIRS=C:\gstreamer\1.0\x86_x64\include\gstreamer-1.0 -DGSTREAMER_APP_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstapp-1.0.lib -DGSTREAMER_BASE_INCLUDE_DIRS=C:\gstreamer\1.0\x86_64\include\gstreamer-1.0\gst\base -DGSTREAMER_BASE_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstbase-1.0.lib -DGSTREAMER_PBUTILS_INCLUDE_DIRS=C:\gstreamer\1.0\x86_x64\include\gstreamer-1.0 -DGSTREAMER_PBUTILS_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstpbutils-1.0.lib -DGSTREAMER_VIDEO_INCLUDE_DIRS=C:\gstreamer\1.0\x86_64\include\gstreamer-1.0 -DGSTREAMER_VIDEO_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstvideo-1.0.lib -DGSTREAMER_MPEGTS_INCLUDE_DIRS=C:\gstreamer\1.0\x86_64\include\gstreamer-1.0 -DGSTREAMER_MPEGTS_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstmpegts-1.0.lib -DGSTREAMER_TAG_INCLUDE_DIRS=C:\gstreamer\1.0\x86_64\include\gstreamer-1.0 -DGSTREAMER_TAG_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gsttag-1.0.lib -DGSTREAMER_GL_INCLUDE_DIRS=C:\gstreamer\1.0\x86_64\include\gstreamer-1.0 -DGSTREAMER_GL_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstgl-1.0.lib -DGLIB_INCLUDE_DIR=C:\gstreamer\1.0\x86_x64\include\glib-2.0 -DGLIB_INCLUDE_DIRS=C:\gstreamer\1.0\x86_x64\include\glib-2.0 -DGLIB_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\glib-2.0 -DGLIB_GIO_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib -DGLIB_GOBJECT_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib -DGLIBCONFIG_INCLUDE_DIR=C:\gstreamer\1.0\x86_64\lib\glib-2.0\include -DGSTREAMER_INCLUDE_DIRS=C:\gstreamer\1.0\x86_x64\include -DGSTREAMER_LIBRARIES=C:\gstreamer\1.0\x86_x64\lib\gstreamer-1.0.lib"`

**Comment by annulen** [comment]
Did you install gstreamer into `C:\gstreamer\1.0\x86_64\`? Are path that you pass to CMake correct?

**Comment by rlatapy-gpsw** [comment]
Paths look good to me, DGSTREAMER_XXXX_LIBRARIES are set to XXXX.lib and DGSTREAMER_XXXXX_INCLUDE_DIRS are all set to C:\gstreamer\1.0\x86_64\include\gstreamer-1.0
I'm not sure which path should be set for DGLIB_INCLUDE_DIR, DGLIB_INCLUDE_DIRS, DGLIB_GIO_LIBRARIES, DGLIB_GOBJECT_LIBRARIES variables, but these are required.

**Comment by annulen** [comment]
I guess that setting valid `PKG_CONFIG_EXECUTABLE` and pointing environment variable PKG_CONFIG_PATH to pkgconfig directory in gstreamer installation should just work, without setting all other paths manually

**Comment by rlatapy-gpsw** [comment]
Phoenox said he has to define all these environment variable..
Setting PKG_CONFIG_PATH doesn't change anything for me.

**Comment by annulen** [comment]
Note that it is environment variable, not cmake parameter, and should point to directory where gstreamer's *.pc files are located

**Comment by rlatapy-gpsw** [comment]
Ok my problem was pkg-config installation... Now it's look ok, but I've errors during build: [build_release.txt](https://github.com/annulen/webkit/files/1169478/build_release.txt)

Using MSYS2 it leads to another error for me (https://github.com/Alexpux/MINGW-packages/pull/2672#issuecomment-317365010)

**Comment by annulen** [comment]
> Now it's look ok, but I've errors during build: build_release.txt

Looks like one of situation when MSVC fails to compile some valid C++ code. Can be worked around by fixing the code, e.g. making some member public or adding #include directives

**Comment by rlatapy-gpsw** [comment]
Ok I've fix the code as you said. I also had to modify some visual project files because WebKit was trying to link with the xml2.lib from gstreamer package instead of the one provided and it doesn't have gstabse-1.0.lib in its dependencies. I don't know where it should be modify in cmake files.
[msvc.diff.txt](https://github.com/annulen/webkit/files/1176004/msvc.diff.txt)

**Comment by annulen** [comment]
gstabse-1.0? I don't know such lib

as for linking libxml2 from gstreamer, that maybe a good idea in case gstreamer libraries/plugins that you will ship depend on it

**Comment by rlatapy-gpsw** [comment]
gstbase sorry

Mhh, I think this is not a problem, the libxml2 library provided in the WebKitLibraries package seems static, while the one used by Gstreamer is dynamic and can be deployed next to it if needed.

**Comment by Voskrese** [comment]
@rlatapy-gpsw 
`set PKG_CONFIG_EXECUTABLE=c:/.../.../PKG-CONFIG.exe`
`set PKG_CONFIG_PATH=E:/tools/gstreamer/1.0/x86_64/lib/pkgconfig`

**Comment by izzyonstage** [comment]
I Have started looking at building my QtWebKit with GStreamer backend.

The process I have done so far is:
- Install latest msi develop version of GStreamer [https://gstreamer.freedesktop.org/data/pkg/windows/1.12.4/]
- Add the following in my build bat file:
-- SET "GSTREAMER_INSTALL_DIR={GSTREAMER_INSTALL_DIR}\1.0\x86_64"
-- SET "PATH=%PATH%;%GSTREAMER_INSTALL_DIR%\bin"
-- SET "LIB=%GSTREAMER_INSTALL_DIR%\lib;%LIB%"
-- SET "INCLUDE=%GSTREAMER_INSTALL_DIR%\include;%INCLUDE%"
- Update Source/cmake/OptionsQt.cmake
-- find "find_package(GStreamer 1.0.3 REQUIRED COMPONENTS ${GSTREAMER_COMPONENTS})" line
-- under this wrapp all the "if (...)" blocks inside the else of the following:
...
if (GSTREAMER_FOUND)
    if (ENABLE_WEB_AUDIO)
        SET_AND_EXPOSE_TO_BUILD(USE_WEBAUDIO_GSTREAMER TRUE)
    endif ()
else ()
    // other if blocks here
endif ()
...

Still a few small build errors that I am looking at (other reported issues here; cant remember their numbers though).

**Comment by izzyonstage** [comment]
NOTE: Not sure if this will need a change in the build scripts, but apparently the GStreamer msi installs the "*.lib" files as dynamic ones, but the static libs should be available as "lib*.a" instead. Might need to check this during builds to make sure correct versions are used.

**Comment by annulen** [comment]
I think gstreamer is shipped only as dll's, and .lib's are just import libraries

**Comment by izzyonstage** [comment]
I read somewhere in the docs that the lib*.a files can be used to statically link with VisualStudio builds. Will see if I can dig out the page to reference here. Was just something i read on train home yesterday and thought it might be useful to know.

**Comment by izzyonstage** [comment]
[http://gstreamer-devel.966125.n4.nabble.com/Trying-to-compile-GStreamer-for-windows-for-static-linking-td4670777.html](http://gstreamer-devel.966125.n4.nabble.com/Trying-to-compile-GStreamer-for-windows-for-static-linking-td4670777.html)

**Comment by izzyonstage** [comment]
Another thing to note on here:
When compiling with your own zlib build cmake seems to always find the gstreamer version (regardless of order in INCLUDES env var.

`-- Found ZLIB: S:/gstreamer/1.0/x86_64/lib/z.lib (found version "1.2.11")`

Should this find mechanism check for static vs dynamic build? On windows when I compile the library I get zdll.lib for the dynamic lib (which requires zlib.dll) or zlib.lib for the statically built lib.

**Comment by annulen** [comment]
Unfortunately, when cmake searches for libraries, it always prefers shared when both shared and static are present. I don't know any other ways to avoid this, except 
* setting paths explicitly which suppresses find* stuff. Variation of this approach is using conan, which forces paths to point to the specific version of package that you requested
* Using pkg-config (which finds both static and shared, and it's possible to pick needed), requires modification of cmake project files and definitely isn't ok for everyone on Windows

**Comment by annulen** [comment]
Specifically for zlib, you can set ZLIB_ROOT cmake variable when building, and it should be enough

**Comment by annulen** [comment]
Note that you have to rebuild from scratch or remove zlib entries from CMakeCache.txt, otherwise ZLIB_ROOT or any other cure won't help

**Comment by izzyonstage** [comment]
I always build from scratch. My build system does a clean clone of my local git repo every time a build is fired

**Comment by annulen** [comment]
Make sure you don't have non-default values of unrelated options

**Comment by annulen** [comment]
As of now, it seems that best way of using gstreamer on Windows, as well as static builds on any platform, is by means of Conan. That should resolve most issues with finding dependencies and linking. See also #836.
