### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by BlockMechanic** [qtwebkit/qtwebkit#454]
Hello

I am trying to build this on windows and cannot seem to find instructions anywhere.I intend to build static, so i was happy when i saw the latest tagged release preview support MinGW. However when I try `
qmake Webkit.pro
`  in windows cmd I get :- 
`  'cmake' is not recognized as an internal or external command,
operable program or batch file.

The WebKit build was disabled for the following reasons:
    * Missing cmake from PATH
    * Using cmake version , but at least cmake 2.8.12 is required to build QtWeb
Kit. ` 

How do i instruct it to use mingw32-make instead? 

or alternatively, can i build from msys ?

**Comment by annulen** [comment]
Hi, you need to install cmake in order to build QtWebKit, there is no way around.

In theory we could build cmake ourselves from qmake, like what QtWebEngines does for gyp, but it seems like a gross overkill.

**Comment by BlockMechanic** [comment]
Ok, ii managed that, thanks, now I am stuck here:- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)

Is there anywhere i can get the full list of dependencies and commands for the build so that i do not spam the issues area here with minor issues? I know I have PNG static libs already built (used them for qt ), so do i need to rebuild qt with new jpeg libs or how do i tell it to use system libs // or whatever solution works.

**Comment by annulen** [comment]
* Official MSYS2 package: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qtwebkit/PKGBUILD
* Build instruction for MSYS, incomplete and might say wrong things somewhere: https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows-%28MSYS%29

**Comment by BlockMechanic** [comment]
@annulen Thanks!, I will try that, any answer for my last question? Do I have to reconfig and rebuild Qtbase for jpeg? if so anything else I need to change? I already have deps like ICU and I am using Qt's Sqlite...

This project is a potential life saver, a lot of apps use Webkit and i do not see many devs rushing to make WebEngine compatibility a priority anytime soon.

**Comment by annulen** [comment]
New QtWebKit uses libjpeg and libpng directly, you don't have to enable support for them in QtBase (legacy QtWebKit tried system libraries, and switched to use of Qt plugins if they were not found).

You will also be asked for libhyphen. If you don't need CSS auto hypehation, you can disable it by passing -DUSE_LIBHYPHEN=OFF. For minimal build you may also disable some other features, use ccmake or cmake-gui to browse through them (or look at "PUBLIC" options in https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/cmake/OptionsQt.cmake#L113)

**Comment by BlockMechanic** [comment]
Ah, ok, i am building for two versions, namely 5.5.1 and 5.7.2 , I will update with results. Also, if i get time tonight i will document the process and submit a "how-to" for dummies like myself.

**Comment by annulen** [comment]
Great, I can give you write access to wiki

**Comment by BlockMechanic** [comment]
After downloading quite a few things, i'm starting to believe i may be in trouble. I am now at this point 
`
Could NOT find Fontconfig (missing:  FONTCONFIG_LIBRARIES FONTCONFIG_INCLUDE_DIR) 
Could NOT find WEBP (missing:  WEBP_INCLUDE_DIRS WEBP_LIBRARIES) 
`
Any pointers please? Or is there an existing static pre-build somewhere ? I downloaded the last preview, but it seems to have .dll.a files without the .a files i think i need

**Comment by BlockMechanic** [comment]
The full error just in case :- 

vC:\Qt\webkit>perl Tools\Scripts\build-webkit --qt --release
CMake Error at CMakeLists.txt:6 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:6 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


Error: --system-information failed on internal CMake!
Checking Last-Modified date of qtwebkit-libs-win.zip...
Could not access https://dl.dropboxusercontent.com/u/30021413/qtwebkit-libs-win.
zip:
Content-Type: text/plain
Client-Date: Tue, 28 Feb 2017 23:59:12 GMT
Client-Warning: Internal response

You may not be connected to the internet. Attempting to build without updating.
Not searching for unused variables given on the command line.
-- Checking for module 'icu-uc'
--   No package 'icu-uc' found
-- Checking for module 'icu-i18n'
--   No package 'icu-i18n' found
-- Found ICU header files in C:/deps/icu/dist/include
-- Found ICU libraries: C:/deps/icu/dist/lib/libsicuuc.a
-- Could NOT find Fontconfig (missing:  FONTCONFIG_LIBRARIES FONTCONFIG_INCLUDE_
DIR)
-- Could NOT find WEBP (missing:  WEBP_INCLUDE_DIRS WEBP_LIBRARIES)
CMake Error at C:/Qt/5.5.1/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5Positioning"
  with any of the following names:

    Qt5PositioningConfig.cmake
    qt5positioning-config.cmake

  Add the installation prefix of "Qt5Positioning" to CMAKE_PREFIX_PATH or set
  "Qt5Positioning_DIR" to a directory containing one of the above files.  If
  "Qt5Positioning" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Source/cmake/OptionsQt.cmake:375 (find_package)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Qt/webkit/WebKitBuild/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Qt/webkit/WebKitBuild/Release/CMakeFiles/CMakeError.log".

C:\Qt\webkit>

**Comment by annulen** [comment]
You were starting build via qmake, weren't you? If you continued to do so, cmake would be called with correct generator (MinGW Makefiles) instead of NMake. Use of build-webkit was actually never tested with MinGW.

Your cmake tries to use Visual Studio, so you won't be able to build anything with MinGW. You need to use MinGW Makefiles generator. If you have all dependencies (e.g. installed from MSYS package manager) stand-alone build would look like:

```
mkdir build
cd build
cmake .. -G "MinGW Makefiles" \
   -DUSE_LIBHYPHEN=OFF \
   -DENABLE_GEOLOCATION=OFF \
   -DENABLE_DEVICE_ORIENTATION=OFF \
   -DENABLE_PRINT_SUPPORT=OFF \
   -DENABLE_OPENGL=OFF \
   -DENABLE_VIDEO=OFF \
   -DENABLE_INSPECTOR_UI=OFF
```
This is not an exact list of flags you need, you may want to keep something enabled, or go further and disable more stuff (e.g. ENABLE_XSLT)

**Comment by BlockMechanic** [comment]
Hi

Thanks !! Far more progress now. But it seems I am missing something fundamental :- 

In the above response you have -DENABLE_OPENGL=OFF \ , i did the same but when i do the cmake .. it get this : - 


c:\Qt\webkit\build>cmake .. -G "MinGW Makefiles" -DPORT=Qt -DUSE_LIBHYPHEN=OFF -
DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF -DENABLE_PRINT_SUPPORT=O
FF -DENABLE_OPENGL=OFF -DENABLE_VIDEO=OFF -DENABLE_INSPECTOR_UI=OFF -DBISON_EXEC
UTABLE=C:/deps/GnuWin32/bin/bison.exe -DGPERF_EXECUTABLE=C:/deps/GnuWin32/gperf.
exe -Wno-dev -DJPEG_LIBRARY=C:/deps/libjpeg/libjpeg.a -DJPEG_INCLUDE_DIR=C:/deps
/libjpeg -DZLIB_INCLUDE_DIR=C:/deps/zlib-1.2.11 -DPNG_LIBRARY=C:/deps/libpng/.li
bs/libpng.a -DPNG_PNG_INCLUDE_DIR=C:/deps/libpng -DPKG_CONFIG_EXECUTABLE=C:/MinG
W/bin/pkg-config.exe -DICU_INCLUDE_DIR=C:/deps/icu/dist/include -DICU_LIBRARY=C:
/deps/icu/dist/lib/libsicuuc.a -DLIBXML2_LIBRARIES=C:/deps/libxml/lib/libxml2.a
-DLIBXML2_INCLUDE_DIR=C:/deps/libxml/include -DLIBXSLT_LIBRARIES=C:/deps/libxslt
/lib/libxslt.a -DLIBXSLT_INCLUDE_DIR=C:/deps/libxslt/include -DFONTCONFIG_LIBRAR
IES=C:/deps/fontconfig-dev_2.8.0-2_win32/lib/fontconfig.lib -DFONTCONFIG_INCLUDE
_DIR=C:/deps/fontconfig-dev_2.8.0-2_win32/include -DWEBP_INCLUDE_DIRS=C:/deps/li
bwebp/include -DWEBP_LIBRARIES=C:/deps/libwebp/lib/libwebp.lib -DCMAKE_PREFIX_PA
TH=c:\Qt\5.5.1-w
-- Disabling ENABLE_3D_TRANSFORMS since ENABLE_OPENGL is disabled.
-- Disabling ENABLE_ACCELERATED_2D_CANVAS since ENABLE_OPENGL is disabled.
-- Disabling ENABLE_MEDIA_CONTROLS_SCRIPT since ENABLE_VIDEO is disabled.
-- Disabling ENABLE_VIDEO_TRACK since ENABLE_VIDEO is disabled.
-- Disabling ENABLE_WEBGL since ENABLE_OPENGL is disabled.
-- Checking for module 'icu-uc'
--   No package 'icu-uc' found
-- Checking for module 'icu-i18n'
--   No package 'icu-i18n' found
-- Found ICU header files in C:/deps/icu/dist/include
-- Found ICU libraries: C:/deps/icu/dist/lib/libsicuuc.a
Cannot open C:\Qt\5.5.1-w\lib\libQt5Core.prl: No such file or directory at C:/Qt
/webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
Cannot open C:\Qt\5.5.1-w\lib\libQt5Gui.prl: No such file or directory at C:/Qt/
webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
Cannot open C:\Qt\5.5.1-w\lib\libQt5Network.prl: No such file or directory at C:
/Qt/webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
Cannot open C:\Qt\5.5.1-w\lib\libQt5Sql.prl: No such file or directory at C:/Qt/
webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
Cannot open C:\Qt\5.5.1-w\lib\libQt5Widgets.prl: No such file or directory at C:
/Qt/webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
Cannot open C:\Qt\5.5.1-w\lib\libQt5Test.prl: No such file or directory at C:/Qt
/webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.
CMake Warning at Source/cmake/OptionsQt.cmake:386 (find_package):
  Could not find a package configuration file provided by "Qt5OpenGL"
  (requested version 5.2.0) with any of the following names:

    Qt5OpenGLConfig.cmake
    qt5opengl-config.cmake

  Add the installation prefix of "Qt5OpenGL" to CMAKE_PREFIX_PATH or set
  "Qt5OpenGL_DIR" to a directory containing one of the above files.  If
  "Qt5OpenGL" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)


CMake Error at Source/cmake/OptionsQt.cmake:394 (message):
  Unable to find C:/Qt/webkit/build/QtStaticDependencies.cmake
Call Stack (most recent call first):
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Qt/webkit/build/CMakeFiles/CMakeOutput.log".
See also "C:/Qt/webkit/build/CMakeFiles/CMakeError.log".

**Comment by annulen** [comment]
Real error here is

    Cannot open C:\Qt\5.5.1-w\lib\libQt5Core.prl: No such file or directory at C:/Qt/webkit/Tools/qt/convert-prl-libs-to-cmake.pl line 57.

prl files from Qt are processed to link dependencies of Qt into resulting binary, and QtStaticDependencies.cmake file is produced as a result. CMake prints that it could not load this file, that's why it cannot proceed.

BTW, any specific reason why Qt 5.5.1 is used instead of newer version?

**Comment by bagong** [comment]
@BlockMechanic : a wild guess (from similar libQt5core not finds (not prl, though)): Adding:

`-DCMAKE_PREFIX_PATH=pathToYourQt`

might help.
The path needed is the one to your flavor (e.g. mingw492_32). It has to be the parent to the bin,include,lib etc folders in that folder-branch. On a default install it would be:

`C:\Qt\5.5\mingw492_32`

But I do agree with @annulen's consternation that you want to build for Qt 5.5 - it already has Webkit after all.

**Comment by annulen** [comment]
We have a bug here: actual file is named Qt5Core.prl, not libQt5Core.prl

**Comment by bagong** [comment]
Looks like two problems mixed:
1. Why are Qt install locations not found? Answer: missing CMAKE_PREFIX_PATH
2. Why is cmake looking for prl-file? Answer: no idea, should be looking for .dll ;)

**Comment by annulen** [comment]
>Why are Qt install locations not found?

I assume they are not found just because those Qt modules were disabled when compiling Qt. They are not absolutely necessary though, and missing QtOpenGL does not make an error.

>Why is cmake looking for prl-file?

Because we need to parse it to get dependencies of Qt libraries so they can be linked into application that will use QtWebKit, otherwise application will have unresolved symbols. We have not found cleaner way to get this information into cmake. Also note that there is no dll here, it's a static build of Qt

@BlockMechanic Could you confirm that prl files are named without "lib" prefix?

/me wonders how did it work for @Vitallium

**Comment by bagong** [comment]
Yep, just trying to guess-help as I know that cmake-modules not found error from countless occasions. I don't know of a way how a build that depends on Qt could automatically find stuff in that enormous Qt tree. So setting `-DCMAKE_PREFIX_PATH` seems to be obligatory to me. (if you know a way how to avoid this (except setting it as envir var), I'd be really interested)

**Comment by BlockMechanic** [comment]
Hi, i have changed to 5.7.1 and i still get the same message. Upon investigating the offending folder, i found that it does contain the prl files in both installations, the problem is that they are named Qt5XXX without the "lib" prefix ie, its looks for libQt5Core.prl when in the folder it is called Qt5Core.prl. I made copies and renamed them and it proceeded even further. Now I am stuck here :- 

CMake Error at build/QtStaticDependencies.cmake:2 (set):
  Syntax error in cmake code at

    C:/Qt/webkit/build/QtStaticDependencies.cmake:2

  when parsing string

    -lole32;-luuid;-lws2_32;-ladvapi32;-lshell32;-luser32;-lkernel32;-lmpr;-LC:/
deps/openssl;-LC:/deps/libpng/.libs;-LC:/deps/icu/dist/lib;-lz;-LC:/Qt/5.7.1/lib
;C:/Qt/5.7.1/lib\libqtpcre.a;-LC:/deps/openssl;-LC:/deps/libpng/.libs;-LC:/deps/
icu/dist/lib

  Invalid escape sequence \l
Call Stack (most recent call first):
  Source/cmake/OptionsQt.cmake:396 (include)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Qt/webkit/build/CMakeFiles/CMakeOutput.log".
See also "C:/Qt/webkit/build/CMakeFiles/CMakeError.log".

C:\Qt\webkit\build>

I can see what the offending character is, but since it is not part of the config commands, i tried tracing it in the listed files to no avail. What could be the problem and how to fix it ?

**Comment by BlockMechanic** [comment]
I have been trying for the better part of five hours no and no luck still.  Does anyone know a work around for the above problem ?

**Comment by annulen** [comment]
Please post your prl file contents

**Comment by BlockMechanic** [comment]
Thanks for the hint, the prl file had this :- 

QMAKE_PRL_LIBS = -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -LC:/deps/openssl -LC:/deps/libpng/.libs -LC:/deps/icu/dist/lib -lz -LC:/Qt/5.7.1/lib C:/Qt/5.7.1/lib\\libqtpcre.a -LC:/deps/openssl -LC:/deps/libpng/.libs -LC:/deps/icu/dist/lib

 The offending issue being the double slash. I edited and configuration reached the end, but with one issue :- 

CMake Error: install(EXPORT "WebKitTargets" ...) includes target "WebCore" which
 requires target "qtsqlite" that is not in the export set.
CMake Error: install(EXPORT "WebKitTargets" ...) includes target "WebCore" which
 requires target "qtsqlite" that is not in the export set.
-- Generating done
-- Build files have been written to: C:/Qt/webkit/build

How do i fix this part?
