### ISSUE TITLE
Compilation Error using mingw32-make

### ISSUE THREAD

**Issue by BlockMechanic** [qtwebkit/qtwebkit#457]
Hi 

So i tried compilation and it came to a screeching halt here:- 

[ 27%] Linking CXX executable ..\..\..\bin\jsc.exe
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc7ca): undefined reference to `uc
ol_countAvailable_55'
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc7e1): undefined reference to `uc
ol_getAvailable_55'
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc886): undefined reference to `ud
at_countAvailable_55'
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc89d): undefined reference to `ud
at_getAvailable_55'
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc942): undefined reference to `un
um_countAvailable_55'
../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/runtime/jsgl
obalobject.cpp.obj:JSGlobalObject.cpp:(.text+0xc959): undefined reference to `un
um_getAvailable_55'
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bi
n/ld.exe: ../../../lib/../source/javascriptcore/cmakefiles/javascriptcore.dir/ru
ntime/jsglobalobject.cpp.obj: bad reloc address 0x188 in section `.rdata'
collect2.exe: error: ld returned 1 exit status
Source\JavaScriptCore\shell\CMakeFiles\jsc.dir\build.make:132: recipe for target
 'bin/jsc.exe' failed
mingw32-make[2]: *** [bin/jsc.exe] Error 1
CMakeFiles\Makefile2:663: recipe for target 'Source/JavaScriptCore/shell/CMakeFi
les/jsc.dir/all' failed
mingw32-make[1]: *** [Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/all] Error
2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Has anyone encountered this before ? Is there a work around or a fix?

google seems to allude to the order of -l library links, if that is the case what is the right order ?

**Comment by annulen** [comment]
You are using headers from one ICU version and libraries from another. I remember there were similar cases, but don't remember what caused that. Probably ICU libraries are those installed with Qt SDK (if this is Qt 5.5)
