### ISSUE TITLE
Update build instructions for MacOS

### ISSUE THREAD

**Issue by raff** [qtwebkit/qtwebkit#468]
1) Add a note about installation. I found that following the instructions from the Linux build page work fine:
```
cd WebKitBuild/Release && sudo [make|ninja] install
```
2) I have had problems using the generated webkit with qt installed from brew (qt@5.7). I was able to compile properly, install and build an application that uses webkit (phantomjs) but the resulting binary failed to run with an error referencing qtwebkit version 5.602, that didn't exist.
Rebuilding everything using the official Qt libraries (Qt 5.8 open source version) installed via the official installed worked fine (phantomjs rebuilt with the offical Qt libraries and the generated WebKit frameworks worked fine).

**Comment by annulen** [comment]
Fixed - now we have new macOS build instruction which is easier to use than before
