### ISSUE TITLE
Unable to link with ICU static libs on Windows

### ISSUE THREAD

**Issue by izzyonstage** [qtwebkit/qtwebkit#579]
This seems to be an issue more for the configuration script which fails to find the lib files.

It is probably due to the fact that the default windows build of ICU creates sicu*.lib files instead of icu*.lib files. This is also true for the Qt Port build scripts.

For my build process I used the attached patches to fix the issues I was having.
[static-ICU-fixes.zip](https://github.com/annulen/webkit/files/1104863/static-ICU-fixes.zip)

**Comment by annulen** [comment]
cc @bagong

**Comment by annulen** [comment]
Let's use conan packages instead, see #695 (comment)
