### ISSUE TITLE
Building on Mac OS broken with CMake 3.9

### ISSUE THREAD

**Issue by alexLearner** [qtwebkit/qtwebkit#606]
Hi, I trying to build webkit for Mac OS Sierra (10.12.6) and get an error: 

```ninja: error: 'lib/QtWebKit.framework/QtWebKit', needed by 'Source/WebKit/CMakeFiles/WebKitWidgets_autogen', missing and no known rule to make it```

But in the `/Users/animo/Qt/5.4/clang_64/lib/` there is an QtWebKit.framework
Qt version - 5.4. 
Does anyone know how to solve this problem?

**Comment by annulen** [comment]
Cannot say much without build log.

>Source/WebKit/CMakeFiles/WebKitWidgets_autogen

Weird, AFAIU there should not be such file or directory, instead there should be WebKitWidgets_automoc targret.

What cmake and ninja versions do you use?

> /Users/animo/Qt/5.4/clang_64/lib

Not relevant, as QtWebKit.framework should be building as a part of the same build process.

BTW, if you don't have specific need to use Qt 5.4, please use 5.9 (or use precompiled binaries from release)

**Comment by alexLearner** [comment]
Yes, I'm tried with 5.9.0 and other versions and the same fail. 
ninja version 1.7.2
cmake version 3.9.1

It is suitable? CMakeError.log: 

```
Determining if files features.h exist failed with the following output:
Change Dir: /Users/animo/Programing/webkit/WebKitBuild/Release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/ninja" "cmTC_cc759"
[1/2] Building C object CMakeFiles/cmTC_cc759.dir/CheckIncludeFiles.c.o
FAILED: CMakeFiles/cmTC_cc759.dir/CheckIncludeFiles.c.o 
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -fno-exceptions -fno-strict-aliasing -fcolor-diagnostics -Qunused-arguments -o CMakeFiles/cmTC_cc759.dir/CheckIncludeFiles.c.o   -c CheckIncludeFiles.c
CheckIncludeFiles.c:2:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

Source:
/* */
#include <features.h>


int main(void){return 0;}
```

**Comment by annulen** [comment]
I don't need CMakeError.log. I need your build log.

`build.ninja` and `CMakeCache.txt` may also be useful (please compress the former if you decide to attach it)

**Comment by alexLearner** [comment]
[build.ninja.zip](https://github.com/annulen/webkit/files/1231002/build.ninja.zip)
[CMakeCache.txt](https://github.com/annulen/webkit/files/1231003/CMakeCache.txt)

**Comment by annulen** [comment]
OK, I see that target names indeed have changed to _autogen, should not be a problem. I have no immediate idea, except to try earlier cmake version, 3.6.2 is known to work in CI

**Comment by alexLearner** [comment]
Thanks! That helped!

**Comment by annulen** [comment]
Wow. Could you try latest 3.8.x? It may help to find out what caused regression

**Comment by alexLearner** [comment]
Yes, I did. 
3.8.2 - OK
3.9.1 - Failed

**Comment by annulen** [comment]
3.9.0? (will fail I guess)

**Comment by annulen** [comment]
Are there changes in CMake output between 3.8.2 and 3.9.1 (e.g., new warnings)?

**Comment by annulen** [comment]
>"The Ninja generator has loosened the dependencies of object compilation"

This change may be the culprit

**Comment by annulen** [comment]
Could you attach (compressed) build.ninja generated by 3.8.2?

**Comment by alexLearner** [comment]
3.9.0 also same error.
Yes, I will attach this after builded

**Comment by alexLearner** [comment]
3.8.2: [build.ninja.zip](https://github.com/annulen/webkit/files/1231187/build.ninja.zip)

**Comment by annulen** [comment]
Looks like same file

**Comment by annulen** [comment]
@Vitallium reported that it doesn't reproduce with cmake 3.9.4
