### ISSUE TITLE
Cannot login into Facebook with QtTestBrowser with Qt 5.9.2

### ISSUE THREAD

**Issue by b3nn0** [qtwebkit/qtwebkit#652]
Hi,
I'm having very strange issues with the current qtwebkit-5.212 branch.
When trying to log into facebook with my application (or QtTestBrowser), I can enter my login data and once I hit the login button, the page just reloads and I'm not logged in.
Other cookie based login sessions work just fine, I could only reproduce it with facebook.
I tried it on two different machines, one with Qt 5.9.2 and one with 5.7.0. The error happens only with Qt 5.9.2.
Are you able to reproduce the issue?
If not, any way I can debug this?

**Comment by annulen** [comment]
Logged in successfully

**Comment by annulen** [comment]
Fun, it works with Qt 5.4 but not 5.9, reproduced your observations

**Comment by annulen** [comment]
I guess this may be caused by HSTS which is enabled by default for Qt 5.9, or HTTP/2 which is enabled by default since Qt 5.8

**Comment by annulen** [comment]
And we have a winner... HTTP/2

**Comment by b3nn0** [comment]
Man does it feel good to find out that I'm not insane. You won't imagine how often I recompiled QtWebKit yesterday in various configurations.. ;)
Anyway, is there a way for my application to disable HTTP/2 until Qt 10/9.3 is out?
Or do I just need to live with Qt 5.7 for now?

**Comment by annulen** [comment]
Quick workaround:
```diff
diff --git a/Source/WebCore/platform/network/qt/ResourceRequestQt.cpp b/Source/WebCore/platform/network/qt/ResourceRequestQt.cpp
index b7f9447bcb0..a547737f959 100644
--- a/Source/WebCore/platform/network/qt/ResourceRequestQt.cpp
+++ b/Source/WebCore/platform/network/qt/ResourceRequestQt.cpp
@@ -63,8 +63,8 @@ QNetworkRequest ResourceRequest::toNetworkRequest(NetworkingContext *context) co
 
 #if QT_VERSION >= QT_VERSION_CHECK(5, 8, 0)
     // HTTP2AllowedAttribute enforces HTTP/2 instead of negotiating, see QTBUG-61397
-    if (newurl.scheme().toLower() == QLatin1String("https"))
-        request.setAttribute(QNetworkRequest::HTTP2AllowedAttribute, true);
+    //if (newurl.scheme().toLower() == QLatin1String("https"))
+      //  request.setAttribute(QNetworkRequest::HTTP2AllowedAttribute, true);
 #endif
 
     const HTTPHeaderMap &headers = httpHeaderFields();
```

**Comment by annulen** [comment]
I've reported https://bugreports.qt.io/browse/QTBUG-64359, and Timur found that HTTP/2 implementation of QtNetwork is broken in case when reply contains more than one `Set-Cookie` header - only last header takes effect. So, authorization cookie is lost and you cannot log in.

It seems like we cannot enable HTTP/2 support in QtWebKit before this bug is fixed, as it's not in any way specific to facebook.com

**Comment by annulen** [comment]
After 0acbf52c97d9da8abd497ce292cc8784be74cbd8 it should be safe to use HTTP/2 with Qt >= 5.10.1 on any sites
