### ISSUE TITLE
QTBUG-34738

### ISSUE THREAD

**Issue by sfroberg** [qtwebkit/qtwebkit#737]
Old QtWebKit bug that never got fixed trickered today.

https://bugreports.qt.io/browse/QTBUG-34738
https://bugs.webkit.org/show_bug.cgi?id=105063

ASSERTION FAILED: m_outlineBox == renderer().outlineBoundsForRepaint(renderer().containerForRepaint(), geometryMap)
/root/qtwebkit/Source/WebCore/rendering/RenderLayer.cpp(866) : void WebCore::RenderLayer::updateLayerPositionsAfterScroll(WebCore::RenderGeometryMap*, WebCore::RenderLayer::UpdateLayerPositionsAfterScrollFlags)

} else {
	// Check that our cached rects are correct.
        ASSERT(m_repaintRect == renderer().clippedOverflowRectForRepaint(renderer().containerForRepaint()));
        **ASSERT(m_outlineBox == renderer().outlineBoundsForRepaint(renderer().containerForRepaint(), geometryMap));**
    }

**Comment by annulen** [comment]
Does it lead to any problems in release build?

**Comment by sfroberg** [comment]
Damn, You are right, I forgot the CMAKE_BUILD_TYPE=Release ...
Sorry about the noice.

BTW, I forgot to ask: Does the QtWebKit1 has latest WebKit engine ?
The same that is underneath webkitgtk 2.18.6 ?

**Comment by annulen** [comment]
No, but it will be updated
