### ISSUE TITLE
More frequent, smaller releases

### ISSUE THREAD

**Issue by KAMiKAZOW** [qtwebkit/qtwebkit#743]
Two different LTS Linux distributions, Ubuntu 18.04 and openSUSE Leap 15, are about to be released. Currently both distributions ship Alpha2 with patches from this git applied on top. More frequent releases, even if each release contains a smaller number of changes, would help packagers a lot.

**Comment by annulen** [comment]
Do you want to provide help of any kind?

**Comment by KAMiKAZOW** [comment]
How other than to click on the "Create a new release" button?

**Comment by annulen** [comment]
For example, with validation of releases (and bringing unit tests up to the appropriate level)

Otherwise clicking "release" button changes nothing beyond using head of 5.212 git branch (which should be more or less safe though)

**Comment by qutetemp** [comment]
>Otherwise clicking "release" button changes nothing beyond using head of 5.212 git branch (which should be more or less safe though)

Distrobutions will package it.

**Comment by annulen** [comment]
Addressed in #957
