### ISSUE TITLE
Building with Windows Conan instructions

### ISSUE THREAD

**Issue by dougmassay** [qtwebkit/qtwebkit#752]
Been hammering on this for a while with no luck, so I thought I'd just ask.

First off ... a note: the "conan install" commands from the Wiki won't work with the latest conan versions. I had to go all the way back to conan v0.29.2 to get them to work. But that's no big deal. Once that was taken care of, the dependencies were downloaded/installed, the libs were copied to the build directory and the conanbuildinfo.cmake (and .txt) were created there, as well.

The problem I'm having is that after the qmake command (from the wiki) is issued from the build directory, cmake is failing to find the ICU package that conan just installed. I'm assuming the same might happen for libxml2 and libxslt, but I can't get that far. I don't see an easy way to pass cmake arguments via the qmake command, so I'm at a bit of a loss. Any tips?

**Comment by dougmassay** [comment]
Got it to configure finally. There's an error in qt5/qtwebkit/Tools/qmake/projects/run_cmake.pro.

exists($$ROOT_BUILD_DIR/conanbuildinfo.cmake):exists($$ROOT_BUILD_DIR/conanfile.txt) {
        CMAKE_CONFIG` += QT_CONAN_DIR=$$ROOT_BUILD_DIR
}

should be:

exists($$ROOT_BUILD_DIR/conanbuildinfo.cmake):exists($$ROOT_BUILD_DIR/conanbuildinfo.txt) {
        CMAKE_CONFIG += QT_CONAN_DIR=$$ROOT_BUILD_DIR
 }

Now onto compiling! I'll close this if you like (or you can as well).

**Comment by dougmassay** [comment]
How to specify an install prefix other than the Qt5.9 binary installation directory?

**Comment by annulen** [comment]
You should not do this, actually.

**Comment by dougmassay** [comment]
Should not do what? Specify an alternate install prefix or use the Wiki instructions to Build on Windows with Conan?

If it's the latter, why not? I assume the instructions were put there to be used, no?

**Comment by annulen** [comment]
Specify an alternate install prefix. It will make usage harder

**Comment by annulen** [comment]
You should use DESTDIR environment variable to do this

**Comment by dougmassay** [comment]
Thanks! I was messing with that variable without much luck. I'm assuming it probably needs to be set before the whole configure/build process?

A couple of other notes on the process:

1) Ninja didn't want to work in the Release/Debug folders in the build directory. It bailed immediately with complaints about a missing libjpeg dependency. Jom/nmake seemed to work fine, but they were much slower and they needed to be run in the root of the build directory; which meant building both release and debug. I could always manually edit the main .pro file to choose one or the other, I guess.

2) "jom install" wouldn't work, only "nmake install" succeeded.

Other than that, thank you very much for the detailed instructions for building with Conan on Windows. They were most helpful. I'm getting good builds, so now I can focus on updating the dependencies to newer versions of libxml2/libxslt. There's a bug in the conan-supplied libxml2-2.9.4 that bites my project squarely in the butt.

**Comment by annulen** [comment]
> I'm assuming it probably needs to be set before the whole configure/build process?

No, only on installation step. It doesn't affect build at all.

>Ninja didn't want to work in the Release/Debug folders in the build directory. It bailed immediately with complaints about a missing libjpeg dependency.

Nonja doesn't complain about dependencies, it's cmake, and it should do the same independently from used generator. Coin builds use ninja on Windows

>"jom install" wouldn't work, only "nmake install" succeeded.

That's weird, jom install certainly worked in Coin before it was switched to ninja

**Comment by annulen** [comment]
BTW, I've started new approach of using Conan - see `cmake_conan` branch. It should replace instruction that you are using eventually, and allow using more compilers/configurations without hassle

**Comment by annulen** [comment]
>Ninja doesn't complain about dependencies, it's cmake

But arguments passed to cmake matter too, you can see them in log

**Comment by dougmassay** [comment]
> No, only on installation step. It doesn't affect build at all.

Hmmm, I'll have to double check the log, because I was setting the DESTDIR environment variable just before running "nmake install" and it was still installing to the Qt5.9.x installation directory. I checked the environment to make sure the ENV VAR was indeed present. I must've missed something, though.

> BTW, I've started new approach of using Conan - see cmake_conan branch. It should replace instruction that you are using eventually, and allow using more compilers/configurations without hassle

Sounds great. Looking forward to it.

**Comment by MaxRis** [comment]
Hey @annulen , @dougmassay 
Thank you for working on that! I was able to build it finally using Qt 5.9.1 MinGW 32 bit.
Can we update https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows-(Conan) to have all corrections by @dougmassay from this thread? I have faced similar issues.

**Comment by zzm3145** [comment]
Thank you for the instructions，finally build with qt5.6-mingw4.9 successfully (to run on XP). Some hints:
1.  copy conanfiles\qtwebkit.txt from 5.9 branch
2. After conan install -f ...  ,  replace 5.3 with 4.9 in conaninfo.txt & conanbuildinfo.cmake
3. Manually build qtjpeg.pro & qtpng.pro, copy  libqtjpeg.a and libqtpng.a to build\qtwebkit\lib

**Comment by MaxRis** [comment]
@zzm3145 thanks for sharing such hints!

**Comment by drizt** [comment]
@annulen, please update wiki instruction. Set maximum Conan version.

**Comment by dougmassay** [comment]
I also wanted to point out that conan is delivering the x86 version of icudt59.dll with the x86_64 vitallium icu package.

> BTW, I've started new approach of using Conan - see cmake_conan branch. It should replace instruction that you are using eventually, and allow using more compilers/configurations without hassle

Been checking this out.  Is this currently viable at all? Just wondering how best to kick off a build of this development branch.

**Comment by Vitallium** [comment]
>conan is delivering the x86 version of icudt59.dll with the x86_64 vitallium icu package.
That's strange. I will double check that.

**Comment by dougmassay** [comment]
I appreciate it. Also if you get the chance, the wiki specified conan install command for  VS2015 x86_64 fails:

`conan install -f ..\..\qt5\coin\provisioning\qtci-windows-10-x86\conanfiles\qtwebkit.txt -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MD -g cmake`

because there is no x86_64 configuration available for compiler.version 14 (there is for the x86 architecture). Specifying compiler.version=15 (VS2017) with VS2015 still seems to work ok for building QTWebKit VS2015 x86_64, though (except for the x86 icudt dll being delivered, of course). So I'm thinking the config for compiler.version=15; arch=x86_64 is really delivering VS2015 (compiler.version=14) binaries (since I'm not getting any errors barking about missing or mismatched runtimes).

**Comment by dougmassay** [comment]
Not able to install conan packages from https://api.bintray.com/conan/qtproject/conan lately (connection aborted by remote host). Has something changed? It worked as recently as last week.

**Comment by annulen** [comment]
Build instructions were replaced, new https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows installs dependencies from conan without any complexities involving qmake stuff and qt5 repo
