### ISSUE TITLE
Any new release plan?

### ISSUE THREAD

**Issue by xeoshow** [qtwebkit/qtwebkit#761]
Hello,

Just new to this fork, and would like to know: If it is still actively maintained? Any new release plan?

Thanks a lot.

Best regards, Jason

**Comment by DamianCz** [comment]
+1 I am also would like to know

**Comment by sizeofvoid** [comment]
Friendly reminder

**Comment by annulen** [comment]
Coming in a few days - there is one remaining issue, and CI system is down at the moment

**Comment by sizeofvoid** [comment]
Thanks for the quick answer. Awesome to read this good news. I hope it will not be mark as "beta" ;)

**Comment by annulen** [comment]
> I hope it will not be mark as "beta" 

I guess this means you will be fine with "alpha3" mark :)
Seriously, I can't just recommend using product with lots of known security issues as recommended for wide use.

**Comment by sizeofvoid** [comment]
Let's look at the use-cases for annulen/webkit. It is an updated webkit version and I guess the main use-case here is to run your old software which has a dependency to webkit. 

If we look at the big linux distributions and BSDs we see a lot of old software which depends on webkit. Software that cannot be easily deleted because there is no replacement available. And in this cases it's an security advance. 

I can't imagine someone starting a new project based on Webkit

**Comment by annulen** [comment]
>I can't imagine someone starting a new project based on Webkit

One of our supported is just starting new project based on QtWebKit. If you can't imagine something, it's not the end of the world.

**Comment by annulen** [comment]
>If we look at the big linux distributions and BSDs we see a lot of old software which depends on webkit. Software that cannot be easily deleted because there is no replacement available. And in this cases it's an security advance.

If we look at the big linux distributions and BSDs we see that almost everyone is on already alpha2+patches, and likely update to alpha3 as soon as it's available

**Comment by annulen** [comment]
And if we achieve planned schedule of 2 releases with up-to-date webkit per year, I'm sure there will be more new projects started

**Comment by sizeofvoid** [comment]
> And if we achieve planned schedule of 2 releases with up-to-date webkit per year, I'm sure there will be more new projects started

You might be right. ;)

**Comment by annulen** [comment]
We've released alpha3 and will continue making releases periodically. Closing this as fixed.
