### ISSUE TITLE
QtWebkit in debug mode

### ISSUE THREAD

**Issue by ReshmaMonica** [qtwebkit/qtwebkit#783]
Hi,

I have created the qtwebkit dlls in debug mode using below steps. 
**1. SET SQLITE3SRCDIR=C:\Qt\Qt5112_Src\qtbase\src\3rdparty\sqlite
2. C:\Qt\Qt5112_Src\qtbase\bin\qmake -r CONFIG+=debug
3. mingw32-make -j8**

Now the debug dlls are of _**1.2GB**_ size. And with that huge size i am not able to run my code in debug mode. So I reduced the size of the dlls using **_strip_** command then the size came down to **_88MB_** and i am able to start my code in debug mode. **_BUT NOW THE CRASH IS COMING IN ntdll_**. Please help me to resolve this problem. Please find the attached screenshots of the crash.

![ntdll_crash](https://user-images.githubusercontent.com/45161734/48691776-d358db00-ebf9-11e8-9ce3-cc71918c5054.PNG)
![ntdll_crash_thread1](https://user-images.githubusercontent.com/45161734/48692072-c7214d80-ebfa-11e8-943b-f39d3cb0d712.PNG)

Thank you.

**Comment by annulen** [comment]
There are two things to keep in mind:
1. Using `strip` removes all debug information, which makes debug build useless (you should better run release build in debugger instead with the same effect, and if you want to debug your code, just add `-g` to QMAKE_CXXFLAGS, assuming you are using mingw)
2. In debug mode QtWebKit is biuild with asserts enabled, it can be that assert is triggered on your content

So, recommendation is to use release mode

**Comment by ReshmaMonica** [comment]
Hi annulen,

Thank you for your quick response.
I am really new to these commands. Could you please elaborate more on the options you have asked me to do. 

**_My requirement is to successfully debug my code with breakpoints enabled._**

Thanks a lot for your help and support.

### **_Between I have a suggestion for the QtWebkit code._** In the below two files, the "#if USE(COORDINATED_GRAPHICS)" should be placed before include statements. With the original code i got an error. When i moved the #if above then it worked fine.

QtWebkit\Source\WebCore\page\scrolling\coordinatedgraphics\ScrollingStateNodeCoordinatedGraphics.cpp
and
QtWebkit\Source\WebCore\page\scrolling\coordinatedgraphics\ScrollingCoordinatorCoordinatedGraphics.cpp

Hope it helps.

**Comment by annulen** [comment]
What error did you get? Could you share cmakeconfig.h from QtWebKit buil directory?

**Comment by ReshmaMonica** [comment]
Sorry, i couldn't remember the exact error. I should have noted it, but i forgot.
As i am not able to attach the requested file, i have pasted the contents of the file as below, please find the same. Besides even i feel that #if should be before #include, because no point in include files without that use(coordinated_graphics). Please correct me if i am wrong.

#ifndef CMAKECONFIG_H
#define CMAKECONFIG_H

#define ENABLE_3D_TRANSFORMS 1
#define ENABLE_ACCELERATED_2D_CANVAS 1
#define ENABLE_ACCELERATED_OVERFLOW_SCROLLING 0
#define ENABLE_ACCESSIBILITY 0
#define ENABLE_ALLINONE_BUILD 1
#define ENABLE_API_TESTS 1
#define ENABLE_ASSEMBLER_WX_EXCLUSIVE 0
#define ENABLE_ASYNC_SCROLLING 0
#define ENABLE_ATTACHMENT_ELEMENT 0
#define ENABLE_AVF_CAPTIONS 0
#define ENABLE_BATTERY_STATUS 0
#define ENABLE_CACHE_PARTITIONING 0
#define ENABLE_CANVAS_PATH 1
#define ENABLE_CANVAS_PROXY 0
#define ENABLE_CHANNEL_MESSAGING 1
#define ENABLE_CONTENT_FILTERING 0
#define ENABLE_CONTEXT_MENUS 1
#define ENABLE_CREDENTIAL_STORAGE 0
#define ENABLE_CSP_NEXT 0
#define ENABLE_CSS3_TEXT 0
#define ENABLE_CSS3_TEXT_LINE_BREAK 0
#define ENABLE_CSS_BOX_DECORATION_BREAK 1
#define ENABLE_CSS_COMPOSITING 0
#define ENABLE_CSS_DEVICE_ADAPTATION 0
#define ENABLE_CSS_GRID_LAYOUT 1
#define ENABLE_CSS_IMAGE_ORIENTATION 0
#define ENABLE_CSS_IMAGE_RESOLUTION 0
#define ENABLE_CSS_IMAGE_SET 1
#define ENABLE_CSS_REGIONS 1
#define ENABLE_CSS_SCROLL_SNAP 0
#define ENABLE_CSS_SELECTORS_LEVEL4 1
#define ENABLE_CSS_SHAPES 1
#define ENABLE_CURSOR_VISIBILITY 0
#define ENABLE_CUSTOM_ELEMENTS 0
#define ENABLE_CUSTOM_SCHEME_HANDLER 0
#define ENABLE_DASHBOARD_SUPPORT 0
#define ENABLE_DATABASE_PROCESS 1
#define ENABLE_DATACUE_VALUE 0
#define ENABLE_DATALIST_ELEMENT 1
#define ENABLE_DATA_TRANSFER_ITEMS 0
#define ENABLE_DETAILS_ELEMENT 1
#define ENABLE_DEVICE_ORIENTATION 1
#define ENABLE_DFG_JIT 1
#define ENABLE_DOM4_EVENTS_CONSTRUCTOR 1
#define ENABLE_DOWNLOAD_ATTRIBUTE 1
#define ENABLE_DRAG_SUPPORT 1
#define ENABLE_ENCRYPTED_MEDIA 0
#define ENABLE_ENCRYPTED_MEDIA_V2 0
#define ENABLE_ES6_ARROWFUNCTION_SYNTAX 1
#define ENABLE_ES6_CLASS_SYNTAX 1
#define ENABLE_ES6_GENERATORS 1
#define ENABLE_ES6_MODULES 0
#define ENABLE_ES6_TEMPLATE_LITERAL_SYNTAX 1
#define ENABLE_FETCH_API 1
#define ENABLE_FILTERS_LEVEL_2 0
#define ENABLE_FONT_LOAD_EVENTS 0
#define ENABLE_FTL_JIT 0
#define ENABLE_FTPDIR 0
#define ENABLE_FULLSCREEN_API 1
#define ENABLE_GAMEPAD 0
#define ENABLE_GAMEPAD_DEPRECATED 0
#define ENABLE_GEOLOCATION 1
#define ENABLE_GRAPHICS_CONTEXT_3D 1
#define ENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING 0
#define ENABLE_ICONDATABASE 1
#define ENABLE_IMAGE_DECODER_DOWN_SAMPLING 0
#define ENABLE_INDEXED_DATABASE 1
#define ENABLE_INDEXED_DATABASE_IN_WORKERS 0
#define ENABLE_INDIE_UI 0
#define ENABLE_INPUT_TYPE_COLOR 1
#define ENABLE_INPUT_TYPE_COLOR_POPOVER 1
#define ENABLE_INPUT_TYPE_DATE 0
#define ENABLE_INPUT_TYPE_DATETIMELOCAL 0
#define ENABLE_INPUT_TYPE_DATETIME_INCOMPLETE 0
#define ENABLE_INPUT_TYPE_MONTH 0
#define ENABLE_INPUT_TYPE_TIME 0
#define ENABLE_INPUT_TYPE_WEEK 0
#define ENABLE_INSPECTOR_UI 1
#define ENABLE_INTL 1
#define ENABLE_IOS_AIRPLAY 0
#define ENABLE_IOS_TEXT_AUTOSIZING 0
#define ENABLE_JIT 1
#define ENABLE_LEGACY_CSS_VENDOR_PREFIXES 0
#define ENABLE_LEGACY_NOTIFICATIONS 0
#define ENABLE_LEGACY_VENDOR_PREFIXES 1
#define ENABLE_LEGACY_WEB_AUDIO 0
#define ENABLE_LETTERPRESS 0
#define ENABLE_LINK_PREFETCH 1
#define ENABLE_MAC_LONG_PRESS 0
#define ENABLE_MATHML 1
#define ENABLE_MEDIA_CAPTURE 0
#define ENABLE_MEDIA_CONTROLS_SCRIPT 1
#define ENABLE_MEDIA_SOURCE 0
#define ENABLE_MEDIA_STATISTICS 0
#define ENABLE_MEDIA_STREAM 0
#define ENABLE_MEMORY_SAMPLER 0
#define ENABLE_METER_ELEMENT 1
#define ENABLE_MHTML 1
#define ENABLE_MINIBROWSER 0
#define ENABLE_MOUSE_CURSOR_SCALE 0
#define ENABLE_NAVIGATOR_CONTENT_UTILS 0
#define ENABLE_NAVIGATOR_HWCONCURRENCY 1
#define ENABLE_NETSCAPE_PLUGIN_API 1
#define ENABLE_NOSNIFF 0
#define ENABLE_NOTIFICATIONS 1
#define ENABLE_OPENGL 1
#define ENABLE_OPENTYPE_MATH 1
#define ENABLE_ORIENTATION_EVENTS 0
#define ENABLE_PDFKIT_PLUGIN 0
#define ENABLE_PERFORMANCE_TIMELINE 0
#define ENABLE_POINTER_LOCK 0
#define ENABLE_PRINT_SUPPORT 1
#define ENABLE_PROXIMITY_EVENTS 0
#define ENABLE_PUBLIC_SUFFIX_LIST 0
#define ENABLE_QT_GESTURE_EVENTS 1
#define ENABLE_QT_WEBCHANNEL 1
#define ENABLE_QUOTA 0
#define ENABLE_REMOTE_INSPECTOR 0
#define ENABLE_REQUEST_ANIMATION_FRAME 1
#define ENABLE_RESOLUTION_MEDIA_QUERY 0
#define ENABLE_RESOURCE_TIMING 0
#define ENABLE_RESOURCE_USAGE 0
#define ENABLE_RUBBER_BANDING 0
#define ENABLE_SAMPLING_PROFILER 1
#define ENABLE_SECCOMP_FILTERS 0
#define ENABLE_SERVICE_CONTROLS 0
#define ENABLE_SHADOW_DOM 0
#define ENABLE_SMOOTH_SCROLLING 1
#define ENABLE_SPEECH_SYNTHESIS 0
#define ENABLE_SPELLCHECK 1
#define ENABLE_STREAMS_API 1
#define ENABLE_SUBTLE_CRYPTO 0
#define ENABLE_SVG_FONTS 1
#define ENABLE_SVG_OTF_CONVERTER 0
#define ENABLE_TELEPHONE_NUMBER_DETECTION 0
#define ENABLE_TEMPLATE_ELEMENT 1
#define ENABLE_TEXT_AUTOSIZING 0
#define ENABLE_THREADED_COMPOSITOR 0
#define ENABLE_TOUCH_ADJUSTMENT 1
#define ENABLE_TOUCH_EVENTS 1
#define ENABLE_TOUCH_ICON_LOADING 0
#define ENABLE_TOUCH_SLIDER 0
#define ENABLE_USERSELECT_ALL 1
#define ENABLE_USER_MESSAGE_HANDLERS 0
#define ENABLE_USER_TIMING 0
#define ENABLE_VIBRATION 0
#define ENABLE_VIDEO 1
#define ENABLE_VIDEO_TRACK 1
#define ENABLE_VIEW_MODE_CSS_MEDIA 1
#define ENABLE_WEBASSEMBLY 0
#define ENABLE_WEBGL 1
#define ENABLE_WEBKIT2 1
#define ENABLE_WEBVTT_REGIONS 0
#define ENABLE_WEB_ANIMATIONS 0
#define ENABLE_WEB_AUDIO 0
#define ENABLE_WEB_REPLAY 0
#define ENABLE_WEB_SOCKETS 1
#define ENABLE_WEB_TIMING 1
#define ENABLE_X11_TARGET 0
#define ENABLE_XSLT 1
#define HAVE_FEATURES_H 0
#define HAVE_QTPOSITIONING 1
#define HAVE_QTPRINTSUPPORT 1
#define HAVE_QTSENSORS 1
#define PLUGIN_ARCHITECTURE_UNSUPPORTED 1
#define PLUGIN_ARCHITECTURE_X11 0
#define USE_COORDINATED_GRAPHICS 1
#define USE_COORDINATED_GRAPHICS_MULTIPROCESS 1
#define USE_GSTREAMER 0
#define USE_LIBHYPHEN 0
#define USE_MEDIA_FOUNDATION 0
#define USE_QT_MULTIMEDIA 1
#define USE_SYSTEM_MALLOC 1
#define USE_TEXTURE_MAPPER 1
#define USE_TEXTURE_MAPPER_GL 1
#define USE_WOFF2 1
#define WTF_CPU_ARM64_CORTEXA53 0
#define WTF_PLATFORM_X11 0

#endif /* CMAKECONFIG_H */

**Comment by annulen** [comment]
`QMAKE_CXXFLAGS += -g` in project file or as qmake argument allows you to debug your code with breakpoints

**Comment by ReshmaMonica** [comment]
Ok done. What could be the side effects of this command.

Thank you.

**Comment by annulen** [comment]
Breakpoint may be triggered on a neighbour line instead of where you put it, because code is optimized like in release mode. To avoid this, you can use stronger spell `QMAKE_CXXFLAGS_RELEASE = $$QMAKE_CXXFLAGS_DEBUG`

**Comment by ReshmaMonica** [comment]
Would you please take some time to explain, what exactly this strong spell is doing and how it will effect my program execution. 

Thank you

**Comment by annulen** [comment]
It uses all debug build flags in a build which is nominally release, in particular it disables optimization

**Comment by ReshmaMonica** [comment]
Will it effect the executable size and the final build.?

Thank you.

**Comment by annulen** [comment]
Yes, just like with debug build. You should use it for debugging, and for release use normal release flags. Alternatively, you can use `QMAKE_CXXFLAGS += -g` and strip binaries for final release

**Comment by ReshmaMonica** [comment]
Ok Annulen, Thank you for your help. I will try the suggested options and come back if any more help required.

Mean while please do let me know whether the the suggestion which i have given for the code is valid or not.

Thank you.

**Comment by ReshmaMonica** [comment]
Hi Annulen,

After using the below two options in release mode, i am not able to hit the breakpoint. Please suggest.

QMAKE_CXXFLAGS += -g
QMAKE_CXXFLAGS_RELEASE = $$QMAKE_CXXFLAGS_DEBUG

Thank you.
