### ISSUE TITLE
Building with the MinGW 7.3.0 64-bit toolchain included with Qt5.12.2

### ISSUE THREAD

**Issue by dougmassay** [qtwebkit/qtwebkit#806]
Thought I'd take a stab at this this weekend. I mostly used the Windows Conan build instructions  in the wiki as a guide.

After the much higher hurdle of getting all the deps (icu, libxnl2, etc...) built with the same 7.3.0 64-bit toolchain, the actual QtWebkit build went surprisingly well. I only ran into two snags:

1. the 64-bit mingw that comes with Qt5.12.2 does not grok the "_set_FMA3_enable" function used in Source/JavaScriptCore/jsc.cpp at line 1723. I changed the #ifdef above it from:

`#if OS(WINDOWS) && (defined(_M_X64) || defined(__x86_64__))`

to:

`#if OS(WINDOWS) && !COMPILER(GCC) && (defined(_M_X64) || defined(__x86_64__))`

... to get around it.

2. MinGW 7.3.0 64-bit doesn't grok GetTickCount64 in Source/WTF/wtf/CurrentTime.cpp at line 113. I was lazy and just changed it to GetTickCount, but I imagine that #ifdef could be modified similarly to my first issue to accommodate 64-bit mingw on Windows.

Other than that, it went great! Now to see if I can use it in a project.

**Comment by annulen** [comment]
64-bit mingw is not fully supported, in particular there is no JIT

**Comment by dougmassay** [comment]
Understood. Was mainly just seeing if compilation was even possible at this point.

**Comment by annulen** [comment]
Yes, for example there are 64-bit binary packages in msys2 repository

**Comment by annulen** [comment]
Fixed in alpha4
