### ISSUE TITLE
Decide on Windows build

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#836]
* Do we want to support build-webkit on WIndows?
    * If yes, it should use the same dependencies as CI
    * Also it should support MinGW if we are going to have it at all
    * Use ninja or VS?
* Do we need `vswhere.exe` code path? `Tools/Scripts/update-vswhere.py` etc

**Comment by DamianCz** [comment]
Yes we should. I can help with that..

**Comment by annulen** [comment]
In CI builds we use Conan, which corresponds to instruction https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows-%28Conan%29. Qt is considering switching their processes to Conan, so for now plan is to make it the only way of installing dependencies. We also need an automated way to rebuild those binary conan packages, until Coin can do it for us

**Comment by annulen** [comment]
Any help with this will be highly appreciated

**Comment by herbmillerjr** [comment]
@DamianCz Are you running with this one? If so, let me know where I can help. Otherwise I'll take it.

Either way, I'm going to spend next week getting myself familiar with Conan and Coin.

**Comment by vitallium** [comment]
Just a side note. You can always ping me here or on irc.

**Comment by annulen** [comment]
Here is an overview of the process: https://github.com/annulen/webkit/wiki/Conan

**Comment by annulen** [comment]
* We should use recipes maintained by Conan central or Bincrafters, if they allow to achieve our goals. For libxslt we don't use any custom build options, for ICU it would be great to have a choice of data format and that's all, libxml2 is the only package that has many differences with default configuration.
* Process of building packages needs to be as fully automated as possible, it must be easy to add new compiler or update library version (at least if there are no compatibility issues between new library and recipe)
* We need a script which would install all required conan packages based on compiler used by end user. It should build things from sources if there are no binary packages

**Comment by annulen** [comment]
Q: ~Why so serious?~ Why can't we just make a simple script that builds all these 3 damn libraries with 3 damn compilers and be done with it?
A: Qt is now considering replacement of whole online repository system with Conan. This means that all Qt modules will become Conan packages, and Coin will support building Conan packages natively. 
* If this is accepted, we have to do tasks above
* If this is not accepted, we continue with setup that we have now and don't need to reimplement provisioning logic inside Coin, because we already have necessary Conan bits there and they work

**Comment by annulen** [comment]
Q: What's the deal with MinGW? Nobody uses it
A: It still has some audience, and Qt WebEngine is not available for these people at all. It's not hard to support it, and if tasks above are fixed, it should be quite easy

**Comment by DamianCz** [comment]
@herbmillerjr I am a newbie here so I can help but I can't be a leader since I don't have knowledge

**Comment by annulen** [comment]
@ashkulz If you are power user of Conan you may want to add your input here as well

**Comment by annulen** [comment]
For example, @DamianCz could take integration of https://github.com/conan-io/cmake-conan so that it could install the same packages as in https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows-(Conan), and @herbmillerjr could work on automation of package builds and extraction of their manifests into qt5.git

**Comment by DamianCz** [comment]
I am fine with that.

**Comment by ashkulz** [comment]
For the Windows build, it's much easier to start with [mxe](https://mxe.cc) -- they already have a [qtwebkit package](https://github.com/mxe/mxe/blob/master/src/qtwebkit.mk) with dependencies, and it'll be quite similar to the Linux approach. A plus of this approach is that the binaries work on Windows XP/2003, which isn't the case with Visual Studio.

Meanwhile, the conan builds can be worked on in parallel.

**Comment by vitallium** [comment]
I don't think that supporting Windows XP is a good idea since it reached its EOL date. The best approach is conan right now.

**Comment by annulen** [comment]
@Emdek uses mxe. But Coin does native builds, and it cannot use mxe packages

In the meantime, we now have kinda working https://github.com/qtwebkit/conan-icu and https://github.com/qtwebkit/conan-libxml2 which support both MSVC and MinGW and build packages automatically, and https://github.com/qtwebkit/conan-libxslt is work in progress.

We also need separate CI job for making commits to qt5.git with updated Conan manifests

@DamianCz, @herbmillerjr So remaining bits of work are 1) end user integration, e.g. conan_cmake installing all needed packages from https://bintray.com/qtproject/conan, and 2) that separate CI repo which is mentioned above. And I'll continue with libxslt package

**Comment by annulen** [comment]
Note that Windows XP is not supported by Qt > 5.6, and Qt 5.6 is EOL as well

**Comment by annulen** [comment]
BTW, there are Conan packages for GStreamer (https://github.com/Panopto/gst-conan and https://github.com/bincrafters/conan-gstreamer), so it should be possible to have Windows builds with MSE and WebAudio and other advanced stuff

**Comment by annulen** [comment]
Found my old experiment with cmake_conan: https://github.com/qtwebkit/qtwebkit/commit/7ed7e1632e279882a739490009b7547e86e1be6e

**Comment by annulen** [comment]
Current status of Conan packages:
* ICU 64.2: https://ci.appveyor.com/project/annulen/conan-icu/builds/25642978 - all needed packages are compiling successfully, test failure needs to be fixed
* libxml2 2.9.9: https://ci.appveyor.com/project/annulen/conan-libxml2/builds/25643658 - missing ICU symbols with MSVC2017 - possibly issue on ICU side
* libxslt 1.1.33: https://ci.appveyor.com/project/annulen/conan-libxslt/builds/25642580 - missing libxml2 package for MSVC2017, error with ICU include paths with MinGW

**Comment by annulen** [comment]
"Separate CI repo": https://github.com/qtwebkit/coin-provisioning

It's also serves as a testing environment for powershell scripts which run in Coin. Manifests are produced as downloadable artifact (making commits to qt5 would require setting up credentials inside build environment, I didn't investigate it)

**Comment by annulen** [comment]
All issues on "conan side" are resolved. The only remaining part is "user side", i.e. integration of cmake_conan into project

**Comment by annulen** [comment]
This is finally fixed now. It's possible to build QtWebKit on Windows with up-to-date dependencies and without relying on any precompiled library archives. See new build instructions at https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows. They are both simple (unlike old Conan-based instructions), and they are verified in automatic CI system (so they won't break silently)
