### ISSUE TITLE
Fix C++ API tests

### ISSUE THREAD

**Issue by Emdek** [qtwebkit/qtwebkit#850]
Failing tests:
- [x] tst_QGraphicsWebView::widgetsRenderingThroughCache()
- [x] tst_QWebFrame::progressSignal()
- [x] tst_QWebFrame::requestedUrl()
- [x] tst_QWebFrame::requestedUrlAfterSetAndLoadFailures()
- [x] tst_QWebFrame::setHtmlWithBaseURL()
- [x] tst_QWebFrame::inputFieldFocus()
- [ ] tst_QWebFrame::baseUrl(null)
- [x] tst_QWebFrame::setUrlHistory()
- [x] tst_QWebFrame::setUrlSameUrl()
- [x] tst_QWebFrame::loadFinishedAfterNotFoundError()
- [x] tst_QWebPage::contextMenuPopulatedOnce()
- [x] tst_QWebPage::userStyleSheetFromLocalFileUrl()
- [ ] tst_QWebPage::backActionUpdate()
- [x] tst_QWebPage::errorPageExtensionLoadFinished()
- [ ] tst_QWebPage::undoActionHaveCustomText()
- [ ] tst_QWebPage::changeVisibilityState()
- [x] tst_QWebPage::originatingObjectInNetworkRequests()
- [x] tst_QWebPage::supportedContentType()
- [x] tst_QWebPage::navigatorCookieEnabled()
- [ ] tst_QWebPage::openWindowDefaultSize()
- [ ] tst_QWebView::crashTests()

Related: #364.

**Comment by Emdek** [comment]
`tst_QWebFrame::progressSignal()` seems to be affected by usage of qrc:/ URL in preceding test (`tst_QWebFrame::horizontalScrollAfterBack()`).

**Comment by Emdek** [comment]
`tst_QWebFrame::requestedUrlAfterSetAndLoadFailures()` doesn't make sense with default error pages.

**Comment by annulen** [comment]
Why? At least waiting for loadFinished(false) and comparison of requestedUrl makes sense

**Comment by Emdek** [comment]
@annulen, adjusting it will make it too close to this:
https://github.com/qtwebkit/qtwebkit/commit/cb42d39d3e62ad331eb38bcd511aa32db0d5a494#diff-de5f49e15b8b5d9cac09eed1cae54369R1476

**Comment by annulen** [comment]
Replaced with #913

**Comment by annulen** [comment]
Failing tests were skipped/XFAIL'ed in 79d07bf76e03faa38b67f2e39537a6a61e856630

**Comment by annulen** [comment]
Seems like all pro files must have CONFIG += testcase in order to be executed in Coin. However, this makes an easy way to skip some test project without removing it's .pro file
