### ISSUE TITLE
background-blend-mode: color-dodge produces wrong result

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#866]
LayoutTests/css3/blending/background-blend-mode-image-color.html

**Comment by annulen** [comment]
![z9xE](https://user-images.githubusercontent.com/102544/61364217-11dc8d80-a88e-11e9-86fc-8c12ff2853b0.png)

See pixelated duck in row 2 column 2

**Comment by annulen** [comment]
Weird thing is that the same composition mode works fine in css3/blending/background-blend-mode-image-image.html and css3/blending/blend-mode-simple.html, so it can be bug on GraphicsContextQt side, not QPainter issue

**Comment by polter-rnd** [comment]
It is a bug in QPainter, in some corner cases ColorDodge and ColorBurn composition modes work incorrectly.
I have made a patch for it and will create pull request to mainstream.

**Comment by annulen** [comment]
Fixed in Qt as https://bugreports.qt.io/browse/QTBUG-77231
