### ISSUE TITLE
unknown module in QT : webkit webkitwidgets on Windows

### ISSUE THREAD

**Issue by kaamui** [qtwebkit/qtwebkit#867]
Hi all ! 

After building qtwebkit from the ["Building-QtWebKit-on-Windows" wiki page](https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows). I didn't see any command to install the libs in my Qt installation. I copied the two generated libs in it manually, but I still have this message "unknown module in QT : webkit webkitwidgets" where I did not have the problem on Mac and Ubuntu.

What am I missing ?

Thanks for the help !

**Comment by annulen** [comment]
Hi! You need to re-run `build-webkit` with `--install` option, it should install everything needed into your Qt directory

**Comment by kaamui** [comment]
Thanks.

Just to know : does it do something else than copying the *.lib in my "C:\Qt\5.9.5\msvc2017_64\lib" ?

**Comment by annulen** [comment]
Yes, it copies headers, mkspec file for qmake integration, cmake files for cmake integration, binaries for multiprocess mode, etc.

**Comment by kaamui** [comment]
The following command results in the same issue than #758 : 

`perl Tools/Scripts/build-webkit --qt --release --install --cmakeargs="-Wno-dev -G \"Visual Studio 16 2019\" -DENABLE_WEBKIT2=OFF -T \"v141\" -A \"x64\" -DCMAKE_PREFIX_PATH=C:\Qt\5.9.5\msvc2017_64"`

**Comment by annulen** [comment]
Hm. Do you have to use Visual Studio generator? If you are just building qtwebkit, you should better use Ninja

**Comment by annulen** [comment]
Visual Studio generator should also have a way to execute install target, but I don't know how to do it from command line

**Comment by annulen** [comment]
It should probably work if you manually activate install target in Visual Studio, or run separate msbuild command

**Comment by kaamui** [comment]
Yep I'll try it thank you. I'm also trying with the Conan wiki page.

**Comment by annulen** [comment]
FWIW, I've pushed patch 9de6deb935a2347d9b2aace6ea1a94169ad4b569 which should make `--install` working correctly for all CMake generators
