### ISSUE TITLE
Fix or deprecate QWebSecurityOrigin::localSchemes()

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#877]

**Comment by annulen** [comment]
cc @Emdek

**Comment by Emdek** [comment]
@annulen, what exactly is broken there?
That they are hardcoded in some places (like `URL::isLocalFile()`) or something else?

**Comment by annulen** [comment]
Broken is that corresponding getter was removed. Though it seems to be easy to reintroduce it

**Comment by annulen** [comment]
6c77ab3586809a2deef093ee2581057b17cdb917

**Comment by Emdek** [comment]
@annulen, OK, but what about these hardcoded cases like `URL::isLocalFile()`?
Any changes in upstream in this regard?
Above method was used just few times (counting just direct usage, there might be more indirect ones) in 5.212 branch.

**Comment by annulen** [comment]
Should isLocalFile be true for qrc://?

**Comment by Emdek** [comment]
@annulen, it is now, but as hardcoded using `#ifdef`, while defaults hardcode just `file`.
Our tests either don't care about it (which is more likely) or expect it to be local.

**Comment by annulen** [comment]
Question is what is the right thing

**Comment by annulen** [comment]
Fixed in cbbb2009953c80ee52d87036bb4a105e18829512.

**Comment by Emdek** [comment]
@annulen, my guess is that depends on the context, in the case touched in f056197cae94647b4d15fbb443a47cf52f626895 it turned out to be not needed at all, thanks to `URL::protocolIsInHTTPFamily()`.
I guess that we should review all usage of that method in Qt port and do no touch the rest for now.
