### ISSUE TITLE
Building on Windows (Conan) : Could not find ICU

### ISSUE THREAD

**Issue by kaamui** [qtwebkit/qtwebkit#881]
Hi,

First of all, I could not install conan with Python 2.7 (errors installing pip if I remember well). I installed python 3.7 which contains conan (and after conan install -f, I changed for python 2.7)

- Visual Studio 2019 (Community) (with msvc2017 x64)
- Perl 5.26
- ninja 1.9.0
- Conan 0.24

after : 
```
conan install -f ..\..\qt5\coin\provisioning\qtci-windows-10-x86\conanfiles\qtwebkit.txt -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD -g cmake

[Result]
Requirements
    icu/59.1@vitallium/stable from local
    libxml2/2.9.4@vitallium/stable from local
    libxslt/1.1.29@vitallium/stable from local
Packages
    icu/59.1@vitallium/stable:970e773c5651dc2560f86200a4ea56c23f568ff9
    libxml2/2.9.4@vitallium/stable:3c9b592a3dd15507b8a6d90a8fcc34d2b4de2260
    libxslt/1.1.29@vitallium/stable:8c83c725f7fefe466a2c6c18ff17d3b0b91202c6

icu/59.1@vitallium/stable: Already installed!
libxml2/2.9.4@vitallium/stable: Already installed!
libxslt/1.1.29@vitallium/stable: Already installed!
PROJECT: Generated cmake created conanbuildinfo.cmake
PROJECT: Generated txt created conanbuildinfo.txt
PROJECT: Generated cmake created conanbuildinfo.cmake
PROJECT: Generated conaninfo.txt
PROJECT imports(): Copied 5 '.dll' files
```

I make this : 
```
C:\Users\dev\qt5-build\qtwebkit>qmake -r ../../qt5/qtwebkit

[Result]

Cannot read C:/Users/dev/qt5-build/qtwebkit/release/Source/WebKit/qt_lib_webkit.pri: Le chemin d?accÞs spÚcifiÚ est introuvable.
Cannot read C:/Users/dev/qt5-build/qtwebkit/release/Source/WebKit/qt_lib_webkitwidgets.pri: Le chemin d?accÞs spÚcifiÚ est introuvable.
Reading C:/Users/dev/qt5/qtwebkit/Tools/qmake/projects/qtpng/qtpng.pro [C:/Users/dev/qt5-build/qtwebkit/Tools/qmake/projects/qtpng]
Reading C:/Users/dev/qt5/qtwebkit/Tools/qmake/projects/generate_cmake_toolchain_file.pro [C:/Users/dev/qt5-build/qtwebkit/Tools/qmake/projects]

Generating CMake toolchain file C:/Users/dev/qt5-build/qtwebkit/qmake_toolchain.cmake

set(CMAKE_C_COMPILER "cl")
set(CMAKE_CXX_COMPILER "cl")

Reading C:/Users/dev/qt5/qtwebkit/Tools/qmake/projects/generate_forwarding_pris.pro [C:/Users/dev/qt5-build/qtwebkit/Tools/qmake/projects]
Project MESSAGE: Writing C:/Users/dev/qt5-build/qtwebkit/mkspecs/modules/qt_lib_webkit.pri
Project MESSAGE: Writing C:/Users/dev/qt5-build/qtwebkit/mkspecs/modules/qt_lib_webkitwidgets.pri
Reading C:/Users/dev/qt5/qtwebkit/Tools/qmake/projects/run_cmake.pro [C:/Users/dev/qt5-build/qtwebkit/Tools/qmake/projects]

Running  cmake C:/Users/dev/qt5/qtwebkit -G Ninja -DPORT=Qt -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Users\dev\qt5-build\qtwebkit\qmake_toolchain.cmake -DUSE_LIBHYPHEN=OFF -DQt5_DIR="C:/Qt/5.9.5/msvc2017_64/lib/cmake/Qt5" -DUSE_LIBJPEG=OFF -DQT_BUNDLED_PNG=1 -DPNG_INCLUDE_DIRS=C:/Users/dev/qt5/qtwebkit/../qtbase/src/3rdparty/libpng -DPNG_LIBRARIES=C:/Users/dev/qt5-build/qtwebkit/lib/qtpng.lib -DQT_BUNDLED_ZLIB=1 -DZLIB_INCLUDE_DIRS=C:/Users/dev/qt5/qtwebkit/../qtbase/src/3rdparty/zlib/src

-- Could NOT find Ruby (missing: RUBY_LIBRARY) (found suitable version "2.4.6", minimum required is "1.9")
CMake Warning (dev) at Source/cmake/OptionsCommon.cmake:167 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  Source/cmake/WebKitCommon.cmake:52 (include)
  CMakeLists.txt:137 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at Source/cmake/OptionsQt.cmake:450 (message):
  USE_LIBJPEG is disabled, will attempt using QImageReader to decode JPEG
  with possible degradation of user experience
Call Stack (most recent call first):
  Source/cmake/WebKitCommon.cmake:53 (include)
  CMakeLists.txt:137 (include)


-- Checking for module 'icu-uc'
--   No package 'icu-uc' found
CMake Error at Source/cmake/FindICU.cmake:82 (message):
  Could not find ICU
Call Stack (most recent call first):
  Source/cmake/OptionsQt.cmake:474 (find_package)
  Source/cmake/WebKitCommon.cmake:53 (include)
  CMakeLists.txt:137 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/dev/qt5-build/qtwebkit/release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/dev/qt5-build/qtwebkit/release/CMakeFiles/CMakeError.log".
Project ERROR: Running cmake failed
```

for these errors : 
```
Cannot read C:/Users/dev/qt5-build/qtwebkit/release/Source/WebKit/qt_lib_webkit.pri: Le chemin d?accÞs spÚcifiÚ est introuvable.
Cannot read C:/Users/dev/qt5-build/qtwebkit/release/Source/WebKit/qt_lib_webkitwidgets.pri: Le chemin d?accÞs spÚcifiÚ est introuvable.
```
I just have a "JavascriptCore" folder in it.

I don't know if the "Could not find ICU" is related but I guess it is not expected that these folder aren't there, isn't it ?

---
Possibly related issues :
https://bugreports.qt.io/browse/QTBUG-61728?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel

**Comment by kaamui** [comment]
Update : this version of python has pip pre installed. Could you add this link to the wiki ? (that's the latest version of 2.7 (4 March))

https://www.python.org/downloads/release/python-2716/

**Comment by annulen** [comment]
Please make sure that conanbuildinfo.cmake and conanfile.txt are present in the directory from where you run qmake. In case of success there will be QT_CONAN_DIR variable in the line "Running  cmake ..."

**Comment by kaamui** [comment]
did you mean conaninfo.txt ?

![image](https://user-images.githubusercontent.com/11720903/62694617-fd933880-b9d4-11e9-8b43-b532e5eff8b5.png)

**Comment by annulen** [comment]
No, it checks for conanfile.txt
Please copy `..\..\qt5\coin\provisioning\qtci-windows-10-x86\conanfiles\qtwebkit.txt` to `conanfile.txt`

**Comment by kaamui** [comment]
It worked (but when the file is supposed to be copied automatically ?). 

Now Qt5Gui private headers are not found .... 

![image](https://user-images.githubusercontent.com/11720903/62696162-210bb280-b9d8-11e9-9326-33e391920731.png)

I have qt5 at the same level, with remote.origin.url=https://code.qt.io/cgit/qt/qt5.git, pointing on 5.9 branch, and Qt 5.9.5 installed.. where the private headers it is searching for are supposed to be ?

(sorry to ask you for anything, but I'm completely lost with the Windows build)

**Comment by kaamui** [comment]
I think the wrong compiler is used (1421...). I think this one is msvc 2019. Is it OK ?

**Comment by annulen** [comment]
>It worked (but when the file is supposed to be copied automatically ?
Probably only Coin does this automatically

>And why every other file is copied
They are not copied but generated in this place

>where the private headers it is searching for are supposed to be ?

There should be Qt5GuiConfig.cmake file in Qt\5.9.5 and it should set Qt5Gui_PRIVATE_INCLUDE_DIRS variable with path

**Comment by annulen** [comment]
Don't use msvc 2019, it has bug with building Qt

**Comment by kaamui** [comment]
I use msvc 2017 (but I have VS 2019 installed with msvc 2017)

I ran `conan install -f ..\..\qt5\coin\provisioning\qtci-windows-10-x86\conanfiles\qtwebkit.txt -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD -g cmake`

**Comment by annulen** [comment]
```
Remarque : inclusion du fichier :  C:\Qt\5.9.5\msvc2017_64\include\QtGui\5.9.5\QtGui\private/qhexstring_p.h
Remarque : inclusion du fichier :   C:\Qt\5.9.5\msvc2017_64\include\QtGui\5.9.5\QtGui/private/qtguiglobal_p.h
Remarque : inclusion du fichier :    C:\Qt\5.9.5\msvc2017_64\include\QtGui/qtguiglobal.h
[...]
ninja: build stopped: subcommand failed.
```
What happens in [...]? Was  `C:\Qt\5.9.5\msvc2017_64\include\QtGui\5.9.5\QtGui\private/qhexstring_p.h` included successfully? What was error message?

**Comment by kaamui** [comment]
the only error messages : 
```
C:\Qt\5.9.5\msvc2017_64\include\QtCore/qalgorithms.h(847): error C3615: la fonction constexpr 'qCountLeadingZeroBits' ne peut pas produire une expression constante
C:\Qt\5.9.5\msvc2017_64\include\QtCore/qalgorithms.h(858): note: échec en raison de l'appel d'une fonction indéfinie ou 'constexpr' non déclarée
C:\Qt\5.9.5\msvc2017_64\include\QtCore/qalgorithms.h(858): note: voir l'utilisation de 'qPopulationCount'
```

no "success" message for the "rem : file including ..." and the file is indeed there (C:\Qt\5.9.5\msvc2017_64\include\QtGui\5.9.5\QtGui\private/qhexstring_p.h) but I see nothing in qt5-build (where the file should be copied ?)

[CMakeError.log](https://github.com/qtwebkit/qtwebkit/files/3481579/CMakeError.log)

**Comment by kaamui** [comment]
> There should be Qt5GuiConfig.cmake file in Qt\5.9.5 and it should set Qt5Gui_PRIVATE_INCLUDE_DIRS variable with path

In C:\Qt\5.9.5\ I have nothing but the msvc2017_64 folder

**Comment by annulen** [comment]
Well,your compiler fails to build qalgorithms.h so it's not a qtwebkit issue. Also, 2019 will likely miscompile code if you use it

**Comment by annulen** [comment]
I believe you can get msvc 2017 from https://www.microsoft.com/ru-ru/download/details.aspx?id=56046

**Comment by annulen** [comment]
>Please tell me that one day there will be qtwebkit libraries (for qt5.9.5 mscv 2017) to install in one command

No. There are binaries for 5.13 only

**Comment by kaamui** [comment]
> I believe you can get msvc 2017 from https://www.microsoft.com/ru-ru/download/details.aspx?id=56046

your link is for VSTA. The Visual Studio 2017 (IDE) is no loger available, but I just found that it is indeed possible to download VS build tools 2017 from here : 
https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017

(or download on click : https://aka.ms/AA363al)

Please add this link to the wiki (it could save a lot of time to a lot of people, as the build is currently not possible to use Visual Studio 2019 build tools (EVEN with msvc 2017))

After installing it, and restart instructions from the beginning, I was able to finish the "qmake -r .." command.

> No. There are binaries for 5.13 only

So it becomes really important for the build instructions on Windows to be the more precise possible.

Thank you for you reactivity and your help. (But stay close I now have errors when I execute ninja :))

**Comment by kaamui** [comment]
Ok it might be possible in the end to download vs 2017 by changing vs-2019 by vs-2017 in this url and to click on vs_community.exe in the page

https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019

**Comment by kaamui** [comment]
@annulen just to know : is the conanfile.txt supposed to be copied during the `conan install -f ...` command ?

Because if so, it is not the case actually.

[conan-install.log](https://github.com/qtwebkit/qtwebkit/files/3482052/conan-install.log)

**Comment by annulen** [comment]
No, copying should be added to instruction

**Comment by kaamui** [comment]
Is it possible for me to submit an up-to-date wiki page when I'm done with building it from a to z on windows ? by cloning the wiki and make a pull request ?

**Comment by annulen** [comment]
New instruction based on up-to-date Conan and dependencies is coming soon, so there is no need to bother

**Comment by kaamui** [comment]
OK ! great news ! :)

**Comment by annulen** [comment]
New approach is implemented in d603a4d4091c258d0b6fc6e2047a338d473626dd (conan_cmake branch). Idea is that you build QtWebKit with cmake similarly to Linux instruction, but adding `-DRUN_CONAN=ON`. When doing this you need to have `conan` executable in PATH. As a result, cmake should initate installation of all libraries automatically.

**Comment by annulen** [comment]
Important note: conan needs to be of latest version, not 0.24.0

**Comment by kaamui** [comment]
Ok I'll try it. Thank you.
