### ISSUE TITLE
Smoke testing of release binaries

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#884]
Before uploading release archives we should check them
Following steps can be done using some free CI service, e.g. Travis can cover all of Linux, Windows, Mac:
* Compare list of files in archive with expected
* Build test applications for wk1 and wk2 with qmake and cmake (if we build tests with qmake in CI, we can check only cmake here), create self-contained application package as artifact with tools like windeployqt 

Artifact then needs to be checked manually, e.g. as described in https://trac.webkit.org/wiki/QtWebKitCheckList

**Comment by annulen** [comment]
cc @Emdek

**Comment by Emdek** [comment]
@annulen, right now I only have access to Linux and Windows systems.

**Comment by annulen** [comment]
That's quite enough for the start.
Qt SDK needs to be installed from official binaries with approach like https://stackoverflow.com/a/56922159
Then unpack QtWebKit binaries into SDK

**Comment by annulen** [comment]
I've create prototype here: https://github.com/annulen/travis-qtsdk-install
It installs Qt SDK 5.13.0 on Linux and macOS, installs corresponding QtWebKit binaries, and tries to build Otter against them. For Windows either install scripts need to be rewritten, or msys shell should be used to run them

**Comment by annulen** [comment]
Oh, Travis uses git bash as a shell on Windows.

**Comment by annulen** [comment]
So, Windows is kind of working, but there is issue with cmake failing to find QtWebKit, even though it was unpacked into correct place.

**Comment by annulen** [comment]
Richard Weickelt of Qbs project has come up with more lightweight solution: https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh

Seems like it doesn't perform binary patching which is required at least for qmake to work properly, however as we use cmake it may work for us too

**Comment by annulen** [comment]
Current solution is not too bad (except that Windows issue which is probably irrelevant to installer), but it takes some 8-12 minutes to install Qt on Win and Mac, and Linux could be faster as well.

**Comment by annulen** [comment]
There is a number of alternative scripts at https://bugreports.qt.io/browse/QTIFW-166, e.g. https://github.com/engnr/qt-downloader

**Comment by annulen** [comment]
I've created new repo at https://github.com/qtwebkit/release-tests which uses https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh. Qt is installed almost instantly, while online/offline installers take several minutes to complete.

Plan is to create fully self-contained artifacts of otter-browser for all supported platforms, so that users could do some manual checking. Also we can build PyQt5 and do the same for qutebrowser, and run its tests.
We can also build phantomjs and splash and run their tests

**Comment by annulen** [comment]
@Emdek are you planning to fix macOS compilation error?

**Comment by Emdek** [comment]
@annulen, once I'll regain access to macOS machine, it's hard to tell when it will happen. :-/
For now you can simply disable platform integration for macOS, this should do the trick:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6663be116..c4a9ff34f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -500,8 +500,8 @@ elseif (APPLE)
        set(MACOSX_BUNDLE_COPYRIGHT "Copyright (C) 2013-2019 Otter Browser Team. All rights reserved.")
        set(otter_src
                ${otter_src}
-               src/modules/platforms/mac/MacPlatformIntegration.mm
-               src/modules/platforms/mac/MacPlatformStyle.cpp
+#              src/modules/platforms/mac/MacPlatformIntegration.mm
+#              src/modules/platforms/mac/MacPlatformStyle.cpp
                resources/icons/otter-browser.icns
        )

```
It's all unrelated to basic browsing anyway, it adds native notifications, populates list of applications for opening files etc.

**Comment by annulen** [comment]
According to `git log -S getCreationTime src/core/NotificationsManager.h`, Notification::getCreationTime never existed so this code could never be working. It doesn't require macOS to figure this out.

Anyway, I don't want to maintain fork, and it would make more sense to apply this patch to master of Otter

**Comment by annulen** [comment]
Oops, I was looking at shallow clone :/

**Comment by annulen** [comment]
Now qtwebkit/release-tests can test all 5 binary products produced by Coin (Mac, Linux and 3 Windows variants). 64-bit MinGW needs to be added in both places.

**Comment by annulen** [comment]
Travis vs Appveyor comparison

### Travis
:heavy_check_mark: Linux, Windows, macOS - all platforms in one place
:heavy_check_mark: Unlimited parallel jobs for free
:white_check_mark: Uses bash on Windows allowing to use same scripts on all platforms; however this causes troubles with tools expecting cmd shell
:x: No pre-configured MSVC environment, and it's not easy to set up one because of aforementioned bash. Only CMake works flawlessly
:x: Only MSVC 2017 is available on Windows
:x: No artifacts storage

### AppVeyor
:heavy_check_mark: Images with various MSVC versions are available
:heavy_check_mark: Artifacts storage which is easy to use (artifacts expire after 6 months, which is quite enough for projects like qtwebkit/coin-provisioning and qtwebkit/release-tests)
:white_check_mark: Direct integration of PowerShell into appveyor.yml (handy when PowerShell used)
:x: No preinstalled MinGW or MSYS
:x: On free plan only one job may be running in a moment of time

**Comment by annulen** [comment]
Implemented.
