### ISSUE TITLE
alpha3: changed behavior for urls with bad protocol

### ISSUE THREAD

**Issue by kmike** [qtwebkit/qtwebkit#887]
I'm using qtwebkit alpha3 release, via PyQT. 

It seems behavior changed for pages with bad protocol, or without protocol (e.g. "non-existing", or "abcd://foo.bar": loadFinished signal is fired with ok=True, and error page is not triggered, so such cases are detected as successful. 

Previously error page was shown, and 301 error code was passed (https://doc.qt.io/qt-5/qnetworkreply.html#NetworkError-enum)

I'm setting a custom error page.

**Comment by annulen** [comment]
Cc @Emdek

**Comment by Emdek** [comment]
@kmike, any chance to retest with current version of qtwebkit-5.212 branch?
It sounds like something already fixed, this is what I'm getting in my test application (modified for testing regressions related to introduction of default error pages):

> "21:17:30.392" QWebPage::loadStarted()
> "21:17:30.392" QWebFrame::loadStarted()
> "21:17:30.397" "QWebFrame::urlChanged(dfdfdffd://dfdff)"
> "21:17:30.410" "QWebView::loadProgress(100)"
> "21:17:30.410" "QWebPage::loadProgress(100)"
> "21:17:30.411" "QWebPage::loadFinished(FALSE)"
> "21:17:30.411" "QWebFrame::loadFinished(FALSE)"

**Comment by kmike** [comment]
@Emdek hm, thanks for checking it! It could be some mistake on my side, because tests now pass on CI; they were failing locally.
