### ISSUE TITLE
yandex.ru doesn't load in alpha3 + qt 5.13

### ISSUE THREAD

**Issue by kmike** [qtwebkit/qtwebkit#889]
Fetching yandex.ru fails in alpha3 + qt 5.13 + Ubuntu 18.04 fails with error 399; it succeeds in alpha2 + qt 5.9.1. 
It seems to be some problem with http2: 

> qt.network.http2: stream 1 finished with error: "Flow control error"

is logged by default. If http2 is disabled via QNetworkRequest::HTTP2AllowedAttribute, rendering works.

I'm not sure if this should be reported here or in QT issue tracker. I've opened a ticket here, because maybe it affects a decision on whether to have http2 on or off by default. Also, maybe you know the fix for it :)

**Comment by annulen** [comment]
This is a known issue, fixed in 0acbf52

**Comment by kmike** [comment]
Awesome, thanks! 
Do you have a timeline for alpha4? :)

**Comment by annulen** [comment]
Coming soon
