### ISSUE TITLE
Context menu actions for images in Resources tab of inspector use blob: instead of original URL

### ISSUE THREAD

**Issue by Emdek** [qtwebkit/qtwebkit#899]
Doing so breaks action that copies URL to clipboard (`blob:` is useless outside of WebKit) and breaks windows opened from inspector.
Also it breaks drag and drop.
We can also consider these two items:
 - allow to set policy for opening these resources, similar to `QWebPage::​LinkDelegationPolicy`;
 - add action to copy image data as `data:` URI (available in Chromium).

**Comment by annulen** [comment]
Fixed in 8e66134d46b699bbf76f60a0be94c914c990879c and 20fd1114cc4b94f468055cfa6c60fde6c29019f1

**Comment by annulen** [comment]
If something remain plese open new issue
