### ISSUE TITLE
Update list of User-Agent strings

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#901]
There is a list of UA strings in `Tools/QtTestBrowser/useragentlist.txt`. It should be updated to include modern versions of desktop and mobile browsers, and remove obsolete stuff like Symbian

**Comment by annulen** [comment]
This site may be useful: https://developers.whatismybrowser.com/useragents/explore/

**Comment by Emdek** [comment]
@annulen, is it important to have exactly the same amount?
Also I'm wondering what is the point of using `QtTestBrowser/0.1` in some strings, perhaps these were produced by QtTestBrowser itself.

**Comment by annulen** [comment]
>is it important to have exactly the same amount?

AFAIU, no

>what is the point of using QtTestBrowser/0.1 in some strings, perhaps these were produced by QtTestBrowser itself

To imitate UA of QtTestBrowser on other supported platforms, obviously

**Comment by annulen** [comment]
Fixed in #1016
