### ISSUE TITLE
Some dependencies missing in "Build on Linux" wiki (on a fresh install of Ubuntu 18.04)

### ISSUE THREAD

**Issue by kaamui** [qtwebkit/qtwebkit#906]
Hello,

I am trying the new wiki page [Build on Linux](https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Linux) and have some trouble to finish the cmake operation (`cmake -DPORT=Qt -DCMAKE_BUILD_TYPE=Release ../..`).

First of all, using system-wide Qt doesn't work for me (cmake cannot find Qt5Config.cmake)

When adding the option to specify Qt path (`-DQt5_DIR=/usr/lib/x86_64-linux-gnu/qt5/5.9.8/gcc_64/lib/cmake/Qt5`), I encounter some errors due to missing packages. 

1. libpng12-dev is no longer available on repositories
- I had to download it here => http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
- And install it via `dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb`
2. some packages were missing in order to achieve the cmake command : 
```
sudo apt install mesa-common-dev libxcomposite-dev libxrandr-dev libgstreamer-plugins-base1.0-dev
```

With these packages installed, the cmake command has terminated successfully. 

Maybe these packages should be added to the wiki in this part : 

```
For Ubuntu use the next command

sudo apt-get install build-essential perl python ruby flex gperf bison cmake \
ninja-build libfontconfig1-dev libicu-dev libsqlite3-dev zlib1g-dev libpng12-dev \
libjpeg-dev libxslt1-dev libxml2-dev libhyphen-dev
```

For libpng, libpng16 is available in Ubuntu 18, but I don't know if it is supported on your side. 

Hope it will help.

**Comment by annulen** [comment]
>First of all, using system-wide Qt doesn't work for me (cmake cannot find Qt5Config.cmake)

That's weird, you're probably missing dev packages 

>libpng12-dev is no longer available on repositories

Use latest available version

**Comment by annulen** [comment]
BTW, you can find ubuntu dependencies from package description of respective Ubuntu version, e.g. for 18.04 see https://packages.ubuntu.com/bionic/libqt5webkit5 -> "[qtwebkit-opensource-src_5.212.0~alpha2-7ubuntu1.dsc]" link -> http://archive.ubuntu.com/ubuntu/pool/universe/q/qtwebkit-opensource-src/qtwebkit-opensource-src_5.212.0~alpha2-7ubuntu1.dsc

**Comment by annulen** [comment]
Actually, `sudo apt-get build-dep libqt5webkit5` should work as well

**Comment by kaamui** [comment]
Do you mean instead of building it on my own ? Is this package up-to-date ?

**Comment by annulen** [comment]
>Is this package up-to-date ?

No it isn't, but it may be okay for your purposes

**Comment by annulen** [comment]
If you want to avoid building from sources and be up-to-date, it shouldn't be hard to set up PPA for qtwebkit using existing Ubuntu package with newer sources

**Comment by kaamui** [comment]
Ok, thank you for your help.

**Comment by annulen** [comment]
Oh, indeed.
