### ISSUE TITLE
build qtwekit by vs2017

### ISSUE THREAD

**Issue by xusai** [qtwebkit/qtwebkit#919]
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at Source/cmake/WebKitMacros.cmake:130 (if):
  if given arguments:

    "NOT" "_file" "MATCHES" "E:/C++/qtwebkit-svn/webkit_svn/WebKitBuild/release/DerivedSources/WebCore"

  Regular expression
  "E:/C++/qtwebkit-svn/webkit_svn/WebKitBuild/release/DerivedSources/WebCore"
  cannot compile
Call Stack (most recent call first):
  Source/WTF/wtf/CMakeLists.txt:513 (WEBKIT_WRAP_SOURCELIST)

-- Configuring incomplete, errors occurred!
---------------------------------------------------------------------------------
I don't know what to do。

**Comment by annulen** [comment]
Huh, I guess you are the first person which tried building webkit inside a directory named "C++" :)

**Comment by fujii** [comment]
Not the first. 
Bug 203564 – WEBKIT_WRAP_SOURCELIST does not escape filesystem paths when compiling regex
https://bugs.webkit.org/show_bug.cgi?id=203564

**Comment by xusai** [comment]
hi!, I tried to use your method, but now there are new problems. I attach the specific compiled output to the email。
 -------------------------------------------------------------------------------------------------------------------------------------------
 -- Configuring done
-- Generating done
CMake Warning:
&nbsp; Manually-specified variables were not used by the project:
 &nbsp;&nbsp;&nbsp; CMAKE_EXPORT_COMPILE_COMMANDS
 
-- Build files have been written to: F:/QTWebkit/webkit_svn/WebKitBuild/release
ninja: error: loading 'build.ninja': 系统找不到指定的文件。
 &nbsp;
 ===== BUILD FAILED ======
 Please ensure you have run ..\..\Tools\Scripts/update-webkit to install dependencies.
 You can view build errors by checking the BuildLog.htm files located at:
F:\QTWebkit\webkit_svn\WebKitBuild/obj/<project&gt;/<config&gt;.
  ---------------------------------------------------------------------------------------------------------------------------------------------

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Fujii Hironori"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月7日(星期四) 上午9:55
 收件人:&nbsp;"qtwebkit/qtwebkit"<qtwebkit@noreply.github.com&gt;;
 抄送:&nbsp;"幽径行者"<1585521991@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [qtwebkit/qtwebkit] build qtwekit by vs2017 (#919)

 

 
Not the first.
Bug 203564 – WEBKIT_WRAP_SOURCELIST does not escape filesystem paths when compiling regex
https://bugs.webkit.org/show_bug.cgi?id=203564

**Comment by xusai** [comment]
I tried to compile the 64 bit qtwekit using the command:
 perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -G \"Visual Studio 15 2017 Win64\" -DCMAKE_PREFIX_PATH=D:\Qt\Qt5.9.7\5.9.7\msvc2017_64"
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Fujii Hironori"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月7日(星期四) 上午9:55
 收件人:&nbsp;"qtwebkit/qtwebkit"<qtwebkit@noreply.github.com&gt;;
 抄送:&nbsp;"幽径行者"<1585521991@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [qtwebkit/qtwebkit] build qtwekit by vs2017 (#919)

 

 
Not the first.
Bug 203564 – WEBKIT_WRAP_SOURCELIST does not escape filesystem paths when compiling regex
https://bugs.webkit.org/show_bug.cgi?id=203564

**Comment by xusai** [comment]
hi! This is my console output：
F:\QTWebkit\webkit_svn>perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=D:\Qt\Qt5.9.7\5.9.7\msvc2017_64"
Use of uninitialized value $expectedVersion in scalar chomp at Tools/Scripts/update-webkit-support-libs line 113.
Falling back to existing version of WebKitSupportLibrary.
Checking for newer version of WebKitAuxiliaryLibrary.zip...
Located a file of type application/zip of size 1526267.
Downloading WebKitAuxiliaryLibrary.zip...

https://developer.apple.com/opensource/internet/WebKitAuxiliaryLibrary.zip

Installing WebKitAuxiliaryLibrary...
The WebKitAuxiliaryLibrary has been sucessfully installed in
 F:\QTWebkit\webkit_svn\WebKitLibraries\win
Removing old F:\QTWebkit\webkit_svn\WebKitLibraries\win\lib32\icuin.lib.
Removing old F:\QTWebkit\webkit_svn\WebKitLibraries\win\lib32\icuuc.lib.
*************************************************************
Mathematical fonts, such as Latin Modern Math are needed to
use the MathML feature.  You do not appear to have these fonts
on your system.

You can download a suitable set of fonts from the following URL:
https://trac.webkit.org/wiki/MathML/Fonts
*************************************************************
Installed tools are correct for the WebKit build.
Setting the Environment Variable 'PreferredToolArchitecture' to 'x64'


成功: 指定的值已得到保存。
+  cmake -DPORT="AppleWin" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -G Ninja -DENABLE_EXPERIMENTAL_FEATURES=ON -Wno-dev -DCMAKE_PREFIX_PATH=D:\Qt\Qt5.9.7\5.9.7\msvc2017_64 "F:/QTWebkit/webkit_svn"
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CMake build type is: Release
-- Found Perl: C:/Perl64/bin/perl.exe (found suitable version "5.26.1", minimum required is "5.10.0")
-- Found PerlModules_JSON::PP: TRUE
-- Found PerlModules: TRUE  found components:  JSON::PP
-- Found PythonInterp: C:/Program Files (x86)/Python36-32/python.exe (found suitable version "3.6.5", minimum required is "2.7.0")
-- Could NOT find Ruby (missing: RUBY_LIBRARY) (found suitable version "2.6.5", minimum required is "1.9")
-- Performing Test C_COMPILER_SUPPORTS_-fcolor-diagnostics
-- Performing Test C_COMPILER_SUPPORTS_-fcolor-diagnostics - Failed
-- Performing Test C_COMPILER_SUPPORTS_-fdiagnostics-color=always
-- Performing Test C_COMPILER_SUPPORTS_-fdiagnostics-color=always - Failed
-- Performing Test CXX_COMPILER_SUPPORTS_-fcolor-diagnostics
-- Performing Test CXX_COMPILER_SUPPORTS_-fcolor-diagnostics - Failed
-- Performing Test CXX_COMPILER_SUPPORTS_-fdiagnostics-color=always
-- Performing Test CXX_COMPILER_SUPPORTS_-fdiagnostics-color=always - Failed
-- Looking for features.h
-- Looking for features.h - not found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for langinfo.h
-- Looking for langinfo.h - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - not found
-- Looking for pthread_np.h
-- Looking for pthread_np.h - not found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for sys/param.h
-- Looking for sys/param.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - not found
-- Looking for sys/timeb.h
-- Looking for sys/timeb.h - found
-- Looking for linux/memfd.h
-- Looking for linux/memfd.h - not found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - found
-- Looking for IsDebuggerPresent
-- Looking for IsDebuggerPresent - found
-- Looking for localtime_r
-- Looking for localtime_r - not found
-- Looking for malloc_trim
-- Looking for malloc_trim - not found
-- Looking for strnstr
-- Looking for strnstr - not found
-- Looking for timegm
-- Looking for timegm - not found
-- Looking for vasprintf
-- Looking for vasprintf - not found
-- Looking for regexec
-- Looking for regexec - not found
-- Looking for pthread_main_np
-- Looking for pthread_main_np - not found
-- Looking for SIGTRAP
-- Looking for SIGTRAP - not found
-- Performing Test HAVE_STAT_BIRTHTIME_value
-- Performing Test HAVE_STAT_BIRTHTIME_value - Failed
-- Performing Test HAVE_TM_GMTOFF_value
-- Performing Test HAVE_TM_GMTOFF_value - Failed
-- Performing Test HAVE_TM_ZONE_value
-- Performing Test HAVE_TM_ZONE_value - Failed
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of __int128_t
-- Check size of __int128_t - failed
-- Performing Test C_COMPILER_SUPPORTS_/W4
-- Performing Test C_COMPILER_SUPPORTS_/W4 - Success
-- Performing Test CXX_COMPILER_SUPPORTS_/W4
-- Performing Test CXX_COMPILER_SUPPORTS_/W4 - Success
-- Using multithreaded, static version of the run-time library
-- Looking for AVFoundationCF/AVCFBase.h
-- Looking for AVFoundationCF/AVCFBase.h - found
-- Looking for AVCFPlayerItemLegibleOutputSetCallbacks
-- Looking for AVCFPlayerItemLegibleOutputSetCallbacks - not found
-- Looking for AVCFAssetResourceLoaderSetCallbacks
-- Looking for AVCFAssetResourceLoaderSetCallbacks - not found
-- Looking for AVCFURLAssetIsPlayableExtendedMIMEType
-- Looking for AVCFURLAssetIsPlayableExtendedMIMEType - not found
-- Performing Test HAVE_AVCFPLAYERITEM_CALLBACK_VERSION_2_value
-- Performing Test HAVE_AVCFPLAYERITEM_CALLBACK_VERSION_2_value - Failed
-- Looking for CACFLayerSetContentsScale
-- Looking for CACFLayerSetContentsScale - not found
-- Found Gperf: D:/Qt/Qt5.9.7/5.9.7/Src/gnuwin32/bin/gperf.exe (Required is at least version "3.0.1")
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/WTF/wtf/PlatformWin.cmake
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/ml64.exe
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/JavaScriptCore/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/JavaScriptCore/shell/PlatformWin.cmake
-- Using source list file: Sources.txt
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/ThirdParty/gtest/PlatformWin.cmake
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-undef
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-undef - Failed
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-stringop-truncation
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-stringop-truncation - Failed
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-suggest-attribute=format
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-suggest-attribute=format - Failed
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/WebCore/PAL/pal/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/WebCore/PlatformWin.cmake
-- Using source list file: Sources.txt
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/WebKitLegacy/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Source/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Tools/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Tools/ImageDiff/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Tools/DumpRenderTree/PlatformWin.cmake
-- Using platform-specific CMakeLists: F:/QTWebkit/webkit_svn/Tools/TestWebKitAPI/PlatformWin.cmake
CMake Warning at PerformanceTests/CMakeLists.txt:5 (message):
  MallocBench is not available on this platform


-- Platform-specific CMakeLists not found: F:/QTWebkit/webkit_svn/PerformanceTests/PlatformWin.cmake
-- Enabled features:
--  ENABLE_3D_TRANSFORMS .......................... ON
--  ENABLE_ACCELERATED_2D_CANVAS                    OFF
--  ENABLE_API_TESTS .............................. ON
--  ENABLE_ATTACHMENT_ELEMENT                       ON
--  ENABLE_CHANNEL_MESSAGING ...................... ON
--  ENABLE_CSS3_TEXT                                OFF
--  ENABLE_CSS_BOX_DECORATION_BREAK ............... ON
--  ENABLE_CSS_COMPOSITING                          OFF
--  ENABLE_CSS_SELECTORS_LEVEL4 ................... ON
--  ENABLE_CURSOR_VISIBILITY                        ON
--  ENABLE_CUSTOM_SCHEME_HANDLER .................. OFF
--  ENABLE_DATALIST_ELEMENT                         OFF
--  ENABLE_DEVICE_ORIENTATION ..................... OFF
--  ENABLE_DRAG_SUPPORT                             ON
--  ENABLE_FETCH_API .............................. ON
--  ENABLE_FTL_JIT                                  OFF
--  ENABLE_FULLSCREEN_API ......................... ON
--  ENABLE_GAMEPAD                                  OFF
--  ENABLE_GEOLOCATION ............................ ON
--  ENABLE_INDEXED_DATABASE                         ON
--  ENABLE_INDEXED_DATABASE_IN_WORKERS ............ ON
--  ENABLE_INPUT_TYPE_COLOR                         OFF
--  ENABLE_INPUT_TYPE_DATE ........................ OFF
--  ENABLE_INPUT_TYPE_DATETIMELOCAL                 OFF
--  ENABLE_INPUT_TYPE_DATETIME_INCOMPLETE ......... OFF
--  ENABLE_INPUT_TYPE_MONTH                         OFF
--  ENABLE_INPUT_TYPE_TIME ........................ OFF
--  ENABLE_INPUT_TYPE_WEEK                          OFF
--  ENABLE_INTL ................................... OFF
--  ENABLE_LEGACY_CSS_VENDOR_PREFIXES               ON
--  ENABLE_LEGACY_ENCRYPTED_MEDIA ................. ON
--  ENABLE_MATHML                                   ON
--  ENABLE_MEDIA_CONTROLS_SCRIPT .................. ON
--  ENABLE_MEDIA_SOURCE                             OFF
--  ENABLE_MEDIA_STATISTICS ....................... ON
--  ENABLE_METER_ELEMENT                            ON
--  ENABLE_MOUSE_CURSOR_SCALE ..................... ON
--  ENABLE_NOTIFICATIONS                            OFF
--  ENABLE_OVERFLOW_SCROLLING_TOUCH ............... OFF
--  ENABLE_QUOTA                                    OFF
--  ENABLE_STREAMS_API ............................ ON
--  ENABLE_SVG_FONTS                                ON
--  ENABLE_VIDEO .................................. ON
--  ENABLE_VIDEO_TRACK                              ON
--  ENABLE_WEBGL .................................. OFF
--  ENABLE_WEB_AUDIO                                OFF
--  ENABLE_XSLT ................................... ON
-- Configuring done
-- Generating done
-- Build files have been written to: F:/QTWebkit/webkit_svn/WebKitBuild/release
ninja: error: '../../WebKitLibraries/win/lib64/libicuuc.lib', needed by 'bin64/WTF.dll', missing and no known rule to make it


===== BUILD FAILED ======

Please ensure you have run ..\..\Tools\Scripts/update-webkit to install dependencies.

You can view build errors by checking the BuildLog.htm files located at:
F:\QTWebkit\webkit_svn\WebKitBuild/obj/<project>/<config>.


Something went wrong. I don't know what to do now.

**Comment by annulen** [comment]
@fujii thanks, I can submit patch for WEBKIT_WRAP_SOURCELIST then to escape variable value with recipe from https://gitlab.kitware.com/cmake/cmake/issues/18580#note_483128

**Comment by xusai** [comment]
&nbsp;
 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Konstantin Tokarev"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月7日(星期四) 晚上6:45
 收件人:&nbsp;"qtwebkit/qtwebkit"<qtwebkit@noreply.github.com&gt;;
 抄送:&nbsp;"幽径行者"<1585521991@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [qtwebkit/qtwebkit] build qtwekit by vs2017 (#919)

 

 
@fujii thanks, I can submit patch for WEBKIT_WRAP_SOURCELIST then to escape variable value with recipe from https://gitlab.kitware.com/cmake/cmake/issues/18580#note_483128

**Comment by xusai** [comment]
When I compiled the 64 bit qtwebkit, another error occurred. Here is my output：
 ---------------------------------------------------------------------------------------------------------------------------------------------
 -- Configuring done
CMake Error at Tools/DumpRenderTree/CMakeLists.txt:102 (add_dependencies):
&nbsp; The dependency target "DumpRenderTreeLib" of target "DumpRenderTree" does
&nbsp; not exist.
 
CMake Error in Tools/DumpRenderTree/CMakeLists.txt:
&nbsp; The dependency target "DumpRenderTreeLib" of target
&nbsp; "DumpRenderTree_autogen" does not exist.
 
WARNING: Target "WebCore" requests linking to directory "E:/qt1/qtwebkit-qtwebkit-dev/WebKitLibraries/win/lib64".&nbsp; Targets may link only to libraries.&nbsp; CMake is dropping the item.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Konstantin Tokarev"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月7日(星期四) 晚上6:45
 收件人:&nbsp;"qtwebkit/qtwebkit"<qtwebkit@noreply.github.com&gt;;
 抄送:&nbsp;"幽径行者"<1585521991@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [qtwebkit/qtwebkit] build qtwekit by vs2017 (#919)

 

 
@fujii thanks, I can submit patch for WEBKIT_WRAP_SOURCELIST then to escape variable value with recipe from https://gitlab.kitware.com/cmake/cmake/issues/18580#note_483128

**Comment by herbmillerjr** [comment]
@annulen Tools/DumpRenderTree/CMakeLists.txt has the following condition:
`if (WIN32)
    add_dependencies(DumpRenderTree DumpRenderTreeLib)
endif ()`

Should this have an 'and not Qt' type of condition added to it?

**Comment by xusai** [comment]
qtwebkit-dev-wip/Source/WTF/wtf/qt/RunLoopQt.cpp
Why does this function have no return value？

RunLoop::CycleResult RunLoop::cycle(const String&)
{
    QCoreApplication::processEvent(QEventLoop::WaitForMoreEvents);
}

**Comment by annulen** [comment]
Fixed in #920
