### ISSUE TITLE
Officially support Python3

### ISSUE THREAD

**Issue by htgoebel** [qtwebkit/qtwebkit#924]
Python 2 will be end-of-life in 6 weeks. GNU/Linux distributions work hard to remove it.

Please support Python 3 officially! Thanks

**Comment by annulen** [comment]
qtwebkit-dev-wip branch should be building fine with Python 3. I'm not planning to add support in 5.212.x series, however it's probably possible to achieve by backporting b9c30ad3b3d04a089f2f16ea1162da74b0553592, 4f3ea9b811c1217198a5edb2aada199c178ae872, 97be5f01f21e4ad99f64eb8e730bfb2f1a4847f4, abc7f04d448ac075833ec4796ed559a38b2b2d47

**Comment by annulen** [comment]
Fixed in 887b98440a46eb30f8a1998e930ddd9218934e1e
