### ISSUE TITLE
QtWebkit-5.212.3-alpha3 binary packt for mingw gcc 73

### ISSUE THREAD

**Issue by chupito01** [qtwebkit/qtwebkit#925]
Hello!
¿It is possible generate the binary packt for mingw gcc 73?
Thanks!

**Comment by chupito01** [comment]
OK, i answer myself. I found the binaries at http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/

**Comment by annulen** [comment]
@chupito01 Don't use that link. Instead, use latest numbered build from http://download.qt.io/snapshots/ci/qtwebkit/5.212/, i.e. right now it's http://download.qt.io/snapshots/ci/qtwebkit/5.212/1571922148/

**Comment by chupito01** [comment]
Thank you very much!! :)
