### ISSUE TITLE
Correct way to install built QtWebKit to Qt installation directory

### ISSUE THREAD

**Issue by Ujifman** [qtwebkit/qtwebkit#935]
Hello. Installation to Qt bin dir is not clear for me
Build environment:

- Windows 10 x64
- Qt 5.13.2
- MinGW 7.3 x86
- Python 2.7

Build script:

```
cd qt5-build\qtwebkit
conan install  .\conanfile.txt -pr webkit -g cmake --build=missing 
qmake -r ../../qt5/qtwebkit
cd debug
mingw32-make -j4
mingw32-make install DESTDIR=../install_release
cd ../release
mingw32-make -j4
mingw32-make install DESTDIR=../install_debug
```
After that I have two paks of dlls, one for debug with _d_ at the end and another one for release without _d_ , the names are different so this dlls can be put in one directory, but `QtWebProcess,  QtWebStorageProcess, QtWebNetworkProcess` have the same names, but at least different size, so they differ, but I have to put them to one directory. My purpose to build QtWebKit one time and spread binaries accross team, because they have the same environment.
What is the correct way to combine debug and release binaries for Qt installation directory?

**Comment by annulen** [comment]
>What is the correct way to combine debug and release binaries for Qt installation directory?

Use release binaries for `QtWebProcess` et. al.

**Comment by Ujifman** [comment]
Thank you for such fast answer.
