### ISSUE TITLE
Is there any prebuilt libraries for linux/macos/windows available so as not need to build it myself?

### ISSUE THREAD

**Issue by faywong** [qtwebkit/qtwebkit#939]

**Comment by ZicoRio** [comment]
For Windows:
http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/
Use Qt5.13.
Qt5.14.1 you can't use:
z_inflateValidate: not found enter poin in Qt5Core.dll

**Comment by faywong** [comment]
@ZicoRio Got it, many many thx.
