### ISSUE TITLE
Evaluate GitHub Actions

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#948]
GitHub Actions is relatively new cloud CI solution which has quite remarkable features, available **for free** for public repositories:
* A lot of resources available for build: 2-core CPU, 7 GB of RAM memory, 14 GB of SSD disk space
* ~~Unlimited build time~~ 6 hours per build job
* ~~Cache (up to 5 GB)~~ it's possible to use gihub releases or other free binary hosting to save cache
* 20 concurrent jobs for Windows and Linux (even more on paid plans) and 5 concurrent jobs for macOS

### For building and running various tests after every push, or even for PRs before merge
IOW, for things which WebKit upstream is doing with buildbot (see also #847, which is only partially done for now)

:warning: Build cache != incremental build, also re-provisioning vm for each build takes some time. OTOH, we don't need to build as many patches per hour as upstream
:warning: Only 2 CPU cores so build from cold cache is going to be long
:warning: We need to upload build artifacts and test results to our server by using HTTP which requires proper setup with security considerations.
* We can't upload to GitHub (or other cloud), as we need these artifacts to be accessible by visualization dashboards in the form of unpacked local files

:question: What about core dumps from tests? According to https://gist.github.com/kudaba/53f68340bd28cd1e8824ac1e6ba8cf88 it's possible, but tests must be run as root...
:bangbang: We cannot run performance tests in GHA (at least, non-hosted), because reproducible results are required

### For testing build system changes on Windows and macOS before pushing to Coin
This is a subset of above, and should be a clear win - if builds are infrequent, caching is not an issue, and it's still faster than trying out different fixes in Coin directly until some of them works

### For making sure that static builds are not accidentally broken
Something that we don't have in Coin at the moment at all, but requires building all Qt modules as well...
* Static Qt can be used from pre-built Conan packages

### For building https://github.com/qtwebkit/release-tests instead of Travis CI
Looks like a clear win, provided that Windows support is quite raw in Travis (e.g., everything is run from Git Bash shell, making things unnecessary cumbersome when you want to use vcvarsall.bat)

### For building Conan packages instead of Appveyor
Looks like a clear win, provided that someone will port build configurations. Appveyor has only one free build job and it really becomes a bottleneck when you need to rebuild all packages in the same day

## References
* Qt Creator build configuration: https://github.com/qt-creator/qt-creator/blob/master/.github/workflows/build_cmake.yml
* Build configuration of some conan packages: https://github.com/bincrafters/conan-qt/tree/testing/5.14.1/.github/workflows, https://github.com/bincrafters/conan-swig_installer/tree/testing/4.0.1/.github/workflows, and possibly other packages maintained by Croydon

cc @Emdek, @ashkulz, @vitallium Any comments/ideas/experiences with GH Actions?

**Comment by annulen** [comment]
OK, looks like I've been seriously mistaken about "Unlimited build time" point. While it's true that public repos have unlimited build time per month, each job has maximum 6 hours.

Right now in Coin mingw builds take more than 2 hours on 8 cores, so they'll likely time out on 2 cores. Other builds are 1h20m or under that, so 6 hours can be enough.

**Comment by annulen** [comment]
UPD: Seems like there is no incentive to get rid of Coin anymore, as I've finally found workflow which alllows me to do almost everything that I want. Nevertheless, GitHub Actions will probably help a lot, especially for platforms which can use ccache

**Comment by annulen** [comment]
Cool things about GH Actions:
* It's possible to fork "built-in" action, do adjustment like https://github.com/annulen/cache-action/commit/ca7e98a59e650e707b2848bfa8fad48913bc7c8e, and immediately use it in workflow

Bad things:
* UI for log monitoring is an utter crap with regards to searching. Normal search on page doesn't work, you have no access to raw log until workflow finishes, and their search box UI works slow as hell on large logs even in Chrome

**Comment by annulen** [comment]
Seems like ccache caches are compressing really good, so 5 Gb might actually be quite enough. For example compressed cache for macOS release build currently takes 110-120 MB.

**Comment by annulen** [comment]
Incremental build without any changes takes ~ 5 minutes - quite enough for our commit frequency. 

250M for cache per build config should be enough - gives us space for 20 different build configs for 2 branches (5.212 and dev need separate caches). Waiting how much debug build will take.

**Comment by annulen** [comment]
1.7 GB for debug :/ Not surprising given that normal debug build directory is about 7GB, but I hoped for miraculous compression too much.

So in 5GB cache we can have one debug build, and 3GB left for other confs.

**Comment by annulen** [comment]
There is a simple workaround for issue with caching in debug build. We are going to use Docker for layout tests (because we need a chroot of some sort, and  Docker comes with repository-"registry" thingy, which is even supported in GitHub packages). When can use the same Docker tag for each build and at the end commit complete build directory (in case of push - for PR builds result should be discarded).

This approach will also solve problem of slow git checkout - current no-test builds use sparse checkout, but for layout testing files need to be checked out sooner or later.

For builds without LayoutTests we continue relying on ccache, and we can really get away without debug as it can be checked later in Coin.

**Comment by annulen** [comment]
What needs to be checked if large Docker images can be handled in reasonable time and without troubles. At least DockerHub allows to store images up to 100GB.

**Comment by yurikoles** [comment]
@annulen do you mean adding whole repo and cache in docker image?

**Comment by yurikoles** [comment]
Also, please consider using homebrew for macOS build, as we [do in homebrew-kde](https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/qt-webkit.rb). You may just patch revision on the fly to point to the latest commit, or even just local path as repo url.

**Comment by annulen** [comment]
>@annulen do you mean adding whole repo and cache in docker image?

There is an idea is to make docker image with whole repo and all its build artifacts, so contributor could just modify one file and get working modified QtWebKit via incremental rebuild. This is tracked at #964.

>Also, please consider using homebrew for macOS build, as we do in homebrew-kde

Homebrew was used to install dependencies but was replaced with Conan which is more convenient and allows to install static libraries.

**Comment by annulen** [comment]
Closing this as GitHub Actions was successfully evaluated and is in use now

**Comment by annulen** [comment]
FWIW, there is yet another interesting cloud CI service, Cirrus CI. For Linux they provide up to 8 cores and 24 GB of RAM in container, and it's possible to build on tmpfs. Maximum build time is 2 hours, but it should be quite enough for building QtWebKit in these conditions.

https://cirrus-ci.org/guide/linux/
https://cirrus-ci.org/faq/#are-there-any-limits
