### ISSUE TITLE
Alpha 4 (qt5.14) with older qt versions ?

### ISSUE THREAD

**Issue by kaamui** [qtwebkit/qtwebkit#958]
Hello,

Can the new release (built with qt5.14) be used with qt5.13.2 for example ? If not, do you plan on providing other binaries like 5.13 ?

This question could probably hit the FAQ wiki :)

**Comment by annulen** [comment]
No, these binaries exclusively for Qt 5.14.1

**Comment by kaamui** [comment]
The provided binaries will always follow the latest non LTS release available I guess (with the recent changes of Qt regarding LTS distribution) ? I think there is a lot of questions like the dummy one I asked above (provided binaries, compatibility, supported features, ENABLE_* options list by platform and what they are aiming for, etc) that suffer an entry in the main README. 

I'm always embarrassed to pollute the issus' thread about all these questions, so I hope you'll prioritize a bit more on comm' soon. 

Btw, it is great to see how fast this project is evolving. Keep up the awesome work !

**Comment by annulen** [comment]
>The provided binaries will always follow the latest non LTS release of qt available I guess (with the recent changes of Qt regarding LTS distribution) ?

Yes. In the past it was the only way I could reasonably operate. Now I have technical ability to build with different Qt versions, but it still requires some effort, and builds won't be from the same git commit. Also, adding more binaries to release will make file list even more confusing.

**Comment by annulen** [comment]
In fact, I would see more reason in building against LTS instead of 5.13 which is already EOL or will be there soon. But with recent policy changes in Qt (i.e., no more free LTS) this concern will disappear in the near future

**Comment by annulen** [comment]
If you have questions, you can ask them in the mailing list, Qt forum, IRC channel, or just create new issue here - whatever medium works better for you.

**Comment by annulen** [comment]
If you have additions to wiki, I can give you access. As for readme, you can submit PRd.

**Comment by kaamui** [comment]
I have a lot of questions, but essentially regarding qtwebkit, I'm also using Qt forums and bug tracker. 

The fact is that I would love to help in improving the wiki and FAQ to smash the most common questions people can have here, but I can't. For instance finding in the source code the default values of ENABLE_* options took me hours (I could only search in github and was searching for default values for NPAPI support :)). And I'm unable to affirm anything about web features currently supported, by platform. Also, it may be more relevant to have a "supported features" table in the wiki after the big WebKit upgrade is achieved, I don't know... 

So, if you can give me these answers, I can totally help writing.

**Comment by annulen** [comment]
>For instance finding in the source code the default values of ENABLE_* options took me hours

Err... what? O_o

If you run cmake without arguments (except required -DPORT=Qt), it sets all options to default. You can review them with ccmake, cmake-gui, Qt Creator or any other tool of your choice. These tools show public options of project by default, unless you explicitly go into "advanced" mode, which you shouldn't do without a good reason. Alternatively, you can find most of defaults in Source/cmake/OptionsQt.cmake, looking for those with "PUBLIC" mark, and if some options aren't there, you probably don't want to touch them.

>Also, it may be more relevant to have a "supported features" table in the wiki after the big WebKit upgrade is achieved, I don't know...

#861. Help would be very much welcome.

**Comment by kaamui** [comment]
> Err... what? O_o

As I said I could only search using the github view (I had no dev env with cmake installed or webkit downloaded, etc). Btw I think it could be helpful to find these answers without having to download and build anything. 

I personally found my answers here [here](https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/Source/WTF/wtf/FeatureDefines.h)

**Comment by annulen** [comment]
I'm not sure what answers can you get from FeatureDefines.h. It's by far not a complete list of WebKit features, it doesn't reflect what things are supported in Qt port at all, it doesn't reflect default values in Qt port per-platform, and it doesn't reflect what features are consider user-customizable in Qt port

BTW, instead of GitHub you may also use code.woboq.com, it has decent code navigation.

**Comment by kaamui** [comment]
Does this not reflect perfectly why qtwebkit totally needs more documentation on the points I quoted ? :p 

Thank you for the tip, I'll look at it.

(Concerning the ENABLE_NETSCAPE_PLUGIN_API it seemed to correspond to my expectations btw (defaulted to 0 for mac, enabled for windows and linux)). I'm going to look at the npapi_mac_v2 branch this month.

**Comment by annulen** [comment]
>And I'm unable to affirm anything about web features currently supported, by platform. 

Most web platform features are cross-platform. But there are exceptions, look at https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/Source/cmake/OptionsQt.cmake#L205-L366 - `WEBKIT_OPTION_DEFINE` lines which end with a variable instead of `ON` or `OFF` are these options.

CSS hyphenation is platform dependent just because of distribution issues - proper bundling for libhyphen dictionaries is yet to implemented, while using system library is totally fine. With other options situation is more complicated.

**Comment by annulen** [comment]
>Does this not reflect perfectly why qtwebkit totally needs more documentation on the points I quote

Patches are welcome

**Comment by annulen** [comment]
For now I have to be C++ developer, devops, project manager/team leader, release engineer, and tech support, just for QtWebKit. If I could spare myself from being technical writer, at least sometimes, I would be more than happy.

**Comment by annulen** [comment]
FWIW, binaries made with 5.12.8 branch can be found at http://download.qt.io/snapshots/ci/qtwebkit/5.212/1584484205/qtwebkit/
