### ISSUE TITLE
Why I can't download packages via conan client

### ISSUE THREAD

**Issue by ZicoRio** [qtwebkit/qtwebkit#960]
Why I can't download packages via conan client

OS: Windows 7 x64
Visual Studio 2017 v15.9.14
Conan: 1.23.0
Python: 3.7.7

Unfortunately at the cache directory no package binaries, no one :((

Log:

```
Configuration:
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
[options]
[build_requires]
[env]

icu/65.1@qtproject/stable: Not found in local cache, looking in remotes...
icu/65.1@qtproject/stable: Trying with 'conan-center'...
icu/65.1@qtproject/stable: Trying with 'bincrafters'...
icu/65.1@qtproject/stable: Trying with 'qtproject'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [2.77k]
Downloading conan_export.tgz completed [2.60k]
Decompressing conan_export.tgz completed [0.00k]
icu/65.1@qtproject/stable: Downloaded recipe revision 0
libxml2/2.9.10@qtproject/stable: Not found in local cache, looking in remotes...
libxml2/2.9.10@qtproject/stable: Trying with 'conan-center'...
libxml2/2.9.10@qtproject/stable: Trying with 'bincrafters'...
libxml2/2.9.10@qtproject/stable: Trying with 'qtproject'...
Downloading conanmanifest.txt completed [0.14k]
Downloading conanfile.py completed [11.24k]
libxml2/2.9.10@qtproject/stable: Downloaded recipe revision 0
WARN: libxml2/2.9.10@qtproject/stable: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.11@qtproject/stable
zlib/1.2.11@qtproject/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@qtproject/stable: Trying with 'conan-center'...
zlib/1.2.11@qtproject/stable: Trying with 'bincrafters'...
zlib/1.2.11@qtproject/stable: Trying with 'qtproject'...
Downloading conanmanifest.txt completed [0.34k]
Downloading conanfile.py completed [8.54k]
Downloading conan_export.tgz completed [1.07k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.11@qtproject/stable: Downloaded recipe revision 0
libiconv/1.15: Not found in local cache, looking in remotes...
libiconv/1.15: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.19k]
Downloading conanfile.py completed [5.47k]
Downloading conan_export.tgz completed [0.25k]
Decompressing conan_export.tgz completed [0.00k]
libiconv/1.15: Downloaded recipe revision 0
libxslt/1.1.34@qtproject/stable: Not found in local cache, looking in remotes...
libxslt/1.1.34@qtproject/stable: Trying with 'conan-center'...
libxslt/1.1.34@qtproject/stable: Trying with 'bincrafters'...
libxslt/1.1.34@qtproject/stable: Trying with 'qtproject'...
Downloading conanmanifest.txt completed [0.19k]
Downloading conanfile.py completed [7.48k]
Downloading conan_export.tgz completed [0.74k]
Decompressing conan_export.tgz completed [0.00k]
libxslt/1.1.34@qtproject/stable: Downloaded recipe revision 0
libjpeg-turbo/2.0.3@qtproject/stable: Not found in local cache, looking in remotes...
libjpeg-turbo/2.0.3@qtproject/stable: Trying with 'conan-center'...
libjpeg-turbo/2.0.3@qtproject/stable: Trying with 'bincrafters'...
libjpeg-turbo/2.0.3@qtproject/stable: Trying with 'qtproject'...
Downloading conanmanifest.txt completed [0.16k]
Downloading conanfile.py completed [5.27k]
Downloading conan_export.tgz completed [0.75k]
Decompressing conan_export.tgz completed [0.00k]
libjpeg-turbo/2.0.3@qtproject/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    icu/65.1@qtproject/stable from 'qtproject' - Downloaded
    libiconv/1.15 from 'conan-center' - Downloaded
    libjpeg-turbo/2.0.3@qtproject/stable from 'qtproject' - Downloaded
    libxml2/2.9.10@qtproject/stable from 'qtproject' - Downloaded
    libxslt/1.1.34@qtproject/stable from 'qtproject' - Downloaded
    zlib/1.2.11@qtproject/stable from 'qtproject' - Downloaded
Packages
    icu/65.1@qtproject/stable:a5c32d8359b2ed138201651a9d9e10305dcc3819 - Missing
    libiconv/1.15:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download
    libjpeg-turbo/2.0.3@qtproject/stable:9b721b63e452039565ba8417e25a183d1bbcb4df - Download
    libxml2/2.9.10@qtproject/stable:7290a063dd51fa46e746a28f1ebe96773b4d565b - Missing
    libxslt/1.1.34@qtproject/stable:b513110d5352c30bcffe6bb99bffff82349100b6 - Missing
    zlib/1.2.11@qtproject/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: icu/65.1@qtproject/stable:a5c32d8359b2ed138201651a9d9e10305dcc3819
ERROR: Missing binary: libxml2/2.9.10@qtproject/stable:7290a063dd51fa46e746a28f1ebe96773b4d565b
ERROR: Missing binary: libxslt/1.1.34@qtproject/stable:b513110d5352c30bcffe6bb99bffff82349100b6

icu/65.1@qtproject/stable: WARN: Can't find a 'icu/65.1@qtproject/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=15, os=Windows
- Options: data_packaging=archive, shared=False, silent=True, with_unit_tests=False
- Dependencies:
- Package ID: a5c32d8359b2ed138201651a9d9e10305dcc3819

ERROR: Missing prebuilt package for 'icu/65.1@qtproject/stable'
Try to build it from sources with "--build icu"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

**Comment by annulen** [comment]
>data_packaging=archive

You are trying to install ICU with this option, while I'm only building binary packages for data_packaging=library. So, you need to compile missing packages on local machine with `--build=missing`

**Comment by annulen** [comment]
What are you actually trying to do? There is new build instruction at https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows-%28Conan-%232%29 but it should not lead to such issues.

**Comment by ZicoRio** [comment]
I'm kettle :)
All ok, but.
For normal build I commented out (at conanfile.py):
# if not tools.which("gperf"):
# if not tools.which("bison"):
# if not tools.which("flex"):

**Comment by annulen** [comment]
Why? This code checks if tools are present in $PATH, and if not, they are installed into Conan's cache and can be used in build, without installing anything into system

**Comment by ZicoRio** [comment]
You are right, but no :)
In my case without this CMake says - I don't see BISON or ...
Thank you for your work, Konstantin.

**Comment by annulen** [comment]
You have to run activate.sh or activate.bat before running cmake

**Comment by annulen** [comment]
That's why I had to ditch idea of using [cmake-conan](https://github.com/conan-io/cmake-conan) - variables are also needed on build step after cmake run.

**Comment by annulen** [comment]
BTW note that you can easily customize options (data_packaging of ICU, static/shared for anything, etc.) of any conan package either by changing conanfile or simply passing `-o` arguments in command line. You'll need to build packages for chosen options combination at least once, then they will be stored in your local Conan cache, and you can even reupload it to your Bintray account or Artifactory instance.

**Comment by ZicoRio** [comment]
I try use single bat file, but process stops several times.
Can I do:
SET CC=cl
SET CXX=cl
before
conan install ../Tools/qt/conanfile.py

**Comment by annulen** [comment]
No. They are needed for cmake only

**Comment by ZicoRio** [comment]
Why? I run commands in same cmd window.
I see conanfile.py does't use CC or CXX - or uses ?

**Comment by annulen** [comment]
conan itself uses these vars, and if they are set, it ruins things

**Comment by ZicoRio** [comment]
Can I delete process stop (by any way) after:
conan install ../Tools/qt/conanfile.py - ?

**Comment by annulen** [comment]
What does it mean - "delete process stop"?

**Comment by ZicoRio** [comment]
I'm use single bat file with all commands.
In cmd window after success command:
conan install ../Tools/qt/conanfile.py
process is stoped

**Comment by annulen** [comment]
Does it happen if you run commands one by one?

**Comment by ZicoRio** [comment]
I run my bat file via specifying path to him in cmd window.
My bat file:
...
SET CC=cl
SET CXX=cl
conan install ../Tools/qt/conanfile.py
activate.bat
cmake -DQT_CONAN_DIR=. -DCMAKE_BUILD_ ...
ninja
===
but after conan install ../Tools/qt/conanfile.py - stop and it wait next command

**Comment by annulen** [comment]
You should do `SET CC=cl` and `SET CXX=cl` **after** conan install!

**Comment by ZicoRio** [comment]
I understood, but I'm trying :)

**Comment by annulen** [comment]
try removing .conan in your home directory and try again

**Comment by ZicoRio** [comment]
maybe another way ?
for example any command ...

**Comment by annulen** [comment]
No. Instruction from https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows-%28Conan-%232%29 is definitely working

**Comment by ZicoRio** [comment]
All work fine. No problem.
I already built several releases.
I want make it by running alone command (bat file)

**Comment by annulen** [comment]
cc @RAJAGOPALAN-GANGADHARAN

**Comment by ZicoRio** [comment]
By the way:
very useful add -DCMAKE_INSTALL_PREFIX and
cmake --build . --config Release --target install

**Comment by ZicoRio** [comment]
Now I try to work about add function:
display page number during print of html page.
Maybe you know way ?

**Comment by annulen** [comment]
There are patches on printing in PhantomJS, which can be upstreamed, see e.g. #288

**Comment by annulen** [comment]
If you could collect all that changes and submit as a pull request, it would be very much welcome.

**Comment by annulen** [comment]
It should be working now
