### ISSUE TITLE
QtWebKit does not compile on Mac OS Catalina with Qt 5.12.7

### ISSUE THREAD

**Issue by fichte** [qtwebkit/qtwebkit#976]
[1112/4514] Building CXX object Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o
FAILED: Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -DBUILDING_QT__=1 -DBUILDING_WITH_CMAKE=1 -DHAVE_CONFIG_H=1 -DQT_ASCII_CAST_WARNINGS -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DYNAMIC_CAST -DQT_NO_EXCEPTIONS -DQT_USE_QSTRINGBUILDER -DSTATICALLY_LINKED_WITH_JavaScriptCore -DSTATICALLY_LINKED_WITH_WTF -ISource/JavaScriptCore/shell -I../../Source/JavaScriptCore/shell -I../../Source/JavaScriptCore/shell/. -I. -I../../Source/JavaScriptCore -I../../Source/JavaScriptCore/.. -I../../Source/JavaScriptCore/API -I../../Source/JavaScriptCore/ForwardingHeaders -I../../Source/JavaScriptCore/assembler -I../../Source/JavaScriptCore/b3 -I../../Source/JavaScriptCore/b3/air -I../../Source/JavaScriptCore/bindings -I../../Source/JavaScriptCore/builtins -I../../Source/JavaScriptCore/bytecode -I../../Source/JavaScriptCore/bytecompiler -I../../Source/JavaScriptCore/dfg -I../../Source/JavaScriptCore/disassembler -I../../Source/JavaScriptCore/disassembler/udis86 -I../../Source/JavaScriptCore/ftl -I../../Source/JavaScriptCore/heap -I../../Source/JavaScriptCore/debugger -I../../Source/JavaScriptCore/inspector -I../../Source/JavaScriptCore/inspector/agents -I../../Source/JavaScriptCore/inspector/augmentable -I../../Source/JavaScriptCore/inspector/remote -I../../Source/JavaScriptCore/interpreter -I../../Source/JavaScriptCore/jit -I../../Source/JavaScriptCore/llint -I../../Source/JavaScriptCore/parser -I../../Source/JavaScriptCore/profiler -I../../Source/JavaScriptCore/replay -I../../Source/JavaScriptCore/runtime -I../../Source/JavaScriptCore/tools -I../../Source/JavaScriptCore/wasm -I../../Source/JavaScriptCore/yarr -IDerivedSources -IDerivedSources/ForwardingHeaders -IDerivedSources/JavaScriptCore -IDerivedSources/JavaScriptCore/inspector -I../../Source/WTF -isystem ../../Source/WebCore/icu -isystem ../../Source/JavaScriptCore/icu -isystem ../../Source/WTF/icu -iframework /usr/local/opt/ibet/qt/5.12.7/5.12.7/clang_64/lib -isystem /usr/local/opt/ibet/qt/5.12.7/5.12.7/clang_64/lib/QtCore.framework/Headers -isystem /usr/local/opt/ibet/qt/5.12.7/5.12.7/clang_64/./mkspecs/macx-clang -fvisibility=hidden -fvisibility-inlines-hidden  -fno-exceptions -fno-strict-aliasing -fno-rtti -std=c++11 -fcolor-diagnostics -Qunused-arguments -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -fPIC -std=gnu++11 -MD -MT Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o -MF Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o.d -o Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o -c ../../Source/JavaScriptCore/jsc.cpp
../../Source/JavaScriptCore/jsc.cpp:192:37: error: reference to 'Handle' is ambiguous
    bool isReachableFromOpaqueRoots(Handle<JSC::Unknown> handle, void*, SlotVisitor& visitor) override
                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/MacTypes.h:249:41: note: candidate found by name lookup is 'Handle'
typedef Ptr *                           Handle;
                                        ^
../../Source/JavaScriptCore/heap/Handle.h:110:29: note: candidate found by name lookup is 'JSC::Handle'
template <typename T> class Handle : public HandleBase, public HandleConverter<Handle<T>, T> {
                            ^
1 error generated.
[1123/4514] Building CXX object Source/JavaScriptCore/shell/CMakeFiles/testb3.dir/__/b3/testb3.cpp.o
ninja: build stopped: subcommand failed.

**Comment by annulen** [comment]
Fixed in 5c272a21e621a66862821d3ae680f27edcc64c19

cc @herbmillerjr
