### ISSUE TITLE
Few questions about QtWebKit internal ...

### ISSUE THREAD

**Issue by sfroberg** [qtwebkit/qtwebkit#983]
Hello.

I can't find info for the following:

1) If I build QtWebKit on Linux with WebKit=OFF and WebKit2=ON it will be multithreaded right?
    That is, the main GUI thread won't get blocked by any network activity and so on ?

2) I want to manipulate few JavaScript objects after DOM tree has been loaded from page but before any JavaScript is executed. 

Specifically, I want to add sandbox attribute to HTMLIFrameElement  before any JavaScript execution happens. Is this possible and how?
https://www.javascripture.com/HTMLIFrameElement

3) For playing videos in QtWebKit, which one is better in terms of video format support and/or performance and features: using gstreamer directly or throught QtMultimedia? What advantage does QtMultimedia exactly offer versus direct gstreamer use?

**Comment by annulen** [comment]
>If I build QtWebKit on Linux with WebKit=OFF and WebKit2=ON it will be multithreaded right? That is, the main GUI thread won't get blocked by any network activity and so on ?

It's multiprocess mode with entirely different API. BTW, network activity happens in a separate thread even in WebKit1 since Qt 4.8, main performance advantage of WebKit2 is that JS execution and UI rendering do not block each other

>I want to manipulate few JavaScript objects after DOM tree has been loaded from page but before any JavaScript is executed.

Did you try using `QWebFrame::javaScriptWindowObjectCleared()` signal?

>For playing videos in QtWebKit, which one is better in terms of video format support and/or performance and features: using gstreamer directly or throught QtMultimedia?

GStreamer directly.

>What advantage does QtMultimedia exactly offer versus direct gstreamer use?

Possibility to use non-GStreamer backends

**Comment by annulen** [comment]
Please reopen if anything is not still clear
