### ISSUE TITLE
ES6 support on QtWebKit

### ISSUE THREAD

**Issue by XankurX** [qtwebkit/qtwebkit#984]
Hello @annulen et al,

First off, thanks for all your efforts on this project.
I am interested in understanding the state of ES6 support on the latest recommended version of QtWebKit available here "http://code.qt.io/cgit/qt/qtwebkit.git/".

The Javascript core for this available branch seems to be running on 602.1.20 version though when I build this version on Windows with Qt 5.12.x, I could not use most of the ES6 features. "https://html5test.com/" hinted that most of the ES6 features are disabled.
Here is more detail:
https://stackoverflow.com/questions/61358893/cant-use-es6-features-with-qtwebkit-running-on-webkit-602-1-20

**Comment by annulen** [comment]
QtWebKit 5.212.x doesn't support ES6 modules. This feature will be available in upcoming release from qtwebkit-dev branch.

**Comment by XankurX** [comment]
Thanks for the prompt response, @annulen.
Does the qtwebkit-dev already support it? or is it work in progress?
Is the qtwebkit-dev branch buildable?

**Comment by annulen** [comment]
>Does the qtwebkit-dev already support it? or is it work in progress?

It should work, though for now there are other known issues which don't allow using it in many cases

>Is the qtwebkit-dev branch buildable?

No, currently only qtwebkit-dev-wip is buildable

**Comment by XankurX** [comment]
Thanks, @annulen ,

It is ok I suppose, to not have the ES6 modules, but I am not even able to use the pretty old ES6 constructs such as arrow functions, Classes, templates etc. on the qtwebkit-dev-wip branch.
When I run the html5tests on it, all the ES6 features other than the "Typed arrays" are states as unsupported.
Do, I need to do something specific at the build time to enable them?

**Comment by XankurX** [comment]
Never mind. I was accidentally using an older binary. CLosing it now.
