### ISSUE TITLE
Better installation of Qt binary packages in CI systems

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#985]
Right now we are using two different methods for Qt installation:
* In https://github.com/qtwebkit/release-tests/blob/master/.travis.yml we use script https://github.com/qtwebkit/release-tests/blob/master/3rdparty/install-qt.sh which originates from QBS project with some modifications. 
* In https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/.github/workflows/build_cmake.yml we use cmake code coming from Qt Creator project which does +/- the same but lacks some features, notably it doesn't support installation of mingw component

On the other hand, there is python script at https://github.com/engnr/qt-downloader. We need to investigate if we could replace both install-qt.sh and cmake code with calls to that script (with necessary changes to make it feature-complete)

**Comment by annulen** [comment]
Note that install-qt.sh supports "old repository formats" for Qt older than 5.10 - we don't actually need that

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
On it! 👍

**Comment by annulen** [comment]
Fixed
