### ISSUE TITLE
undefined reference of ResolveLocaleName function (This issue contains the complete steps for creating webkit libs for mingw compiler)

### ISSUE THREAD

**Issue by ReshmaMonica** [qtwebkit/qtwebkit#986]
Hi,

I am trying to build qtwebkit and landed into the below errors. Please help me, this is very urgent.

**_icu/65.1@qtproject/stable: windtfmt.o:windtfmt.cpp:(.text+0x157): undefined reference to `_imp__ResolveLocaleName@12'
icu/65.1@qtproject/stable: winnmfmt.o:winnmfmt.cpp:(.text+0xa04): undefined reference to `_imp__ResolveLocaleName@12'
icu/65.1@qtproject/stable: collect2.exe: error: ld returned 1 exit status
icu/65.1@qtproject/stable: make[1]: *** [Makefile:204: ../lib/icuin65.dll] Error 1
icu/65.1@qtproject/stable: make: *** [Makefile:153: all-recursive] Error 2
icu/65.1@qtproject/stable:
icu/65.1@qtproject/stable: ERROR: Package '023f11b852faf0b83c4842316dfe47e8020202d3' build failed
icu/65.1@qtproject/stable: WARN: Build folder C:\.conan\5eb268\1
ERROR:
        ConanException: Error 2 while executing make --silent -j 8
Exit code: 1_**

Build environment information:
1. 64-bit machine
2. GCC compiler - **_mingw53_32_**
3. Qt version - **_5.11.2_**
3. command used to build the qtwebkit
**_Tools\qt\build-qtwebkit-conan.py --qt=C:\Qt\Qt5.11.2\Tools\mingw530_32 --install --profile=C:\Users\E499370\.conan\profiles\qtwebkit_gcc_x86 --arch=x86_**

**Comment by annulen** [comment]
I guess this error should disappear if you switch to MinGW 7.3 which you can install from Qt online installer as well. Qt 5.11 binaries should be fully compatible with it.

**Comment by annulen** [comment]
From quick googling it seems like this error is related to new Windows API used in ICU so upgrading compiler may be the cleanest solution.

**Comment by ReshmaMonica** [comment]
But I got MinGW 5.3 along with Qt 5.11.2 installer. Is that ok if I manually download 7.3 and use that ? And besides, we have some third party libraries which were built using 5.3 compiler.

Can we have some alternative which works for both compilers, because for qtwebkit, the instructions did not mention that I need only 7.3 compiler.

Please suggest.

**Comment by annulen** [comment]
>But I got MinGW 5.3 along with Qt 5.11.2 installer.

You probably use offline installer, which won't be available for newer Qt versions. With online installer you can get 7.3

> Is that ok if I manually download 7.3 and use that ? 

Yes.

>Can we have some alternative which works for both compilers, because for qtwebkit, the instructions did not mention that I need only 7.3 compiler.

Older ICU version were known to work with 5.3, or it might be possible to find some workaround for latest ICU.

BTW, what is the reason to use Qt 5.11? That's ancient version which is long since EOL.

**Comment by annulen** [comment]
What cmake arguments are you using for build? In particular, are you building release or debug?

**Comment by ReshmaMonica** [comment]
Hi annulen,

After removing ENABLE_ALLINONE_BUILD flag from CMAKE arguments, it is building fine now. I Will let you know if it runs into any other issues.

Thank you.

**Comment by ReshmaMonica** [comment]
Hi annulen,

I am getting the below error now. Could you please help me.

**_C:/Qt/Qt5.12.8/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../lib/../source/webcore/cmakefiles/anglesupport.dir/__/thirdparty/angle/src/compiler/translator/emulateprecision.cpp.obj: not enough memory to allocate space for 0xa6a symbols of size 0x12
C:/Qt/Qt5.12.8/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Memory exhausted
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Source\WebKit\CMakeFiles\WebKit.dir\build.make:2038: bin/Qt5WebKit.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:1847: Source/WebKit/CMakeFiles/WebKit.dir/all] Error 2
mingw32-make: *** [Makefile:162: all] Error 2_**

Thank you

**Comment by annulen** [comment]
Do you have enough memory on build machine?

**Comment by ReshmaMonica** [comment]
Yes, I have around 13 GB of space. Is there any minimum requirement?

**Comment by ReshmaMonica** [comment]
i just made it to 30 GB and tried but still getting the same error.

**Comment by annulen** [comment]
30 GB of RAM?

**Comment by ReshmaMonica** [comment]
mine 8 GB RAM, and that 30GB is hard disk.

and the error comes when the Qt5Webkit.dll went up to 152MB size when the below line is getting executed. Please help me to resolve this error. Why the release dll is going up to that size?

[ 95%] Linking CXX shared library ..\..\bin\Qt5WebKit.dll

Thank you

**Comment by annulen** [comment]
No idea. You may want to switch to using prebuilt binaries instead.

**Comment by ReshmaMonica** [comment]
Hi annulen,

Thank you for the advice, I have taken the prebuilt binaries and placed them in the qt folder. Now when building the code I am getting the below errors. Could you please help.

![image](https://user-images.githubusercontent.com/45161734/80897734-aaf36c80-8d19-11ea-942a-ea64a1aa842e.png)

Thank you

**Comment by ReshmaMonica** [comment]
Hi Annulen,

Can you provide your insights into the issue or direct me to some wiki where I can find some help in using the prebuilt binaries.

**_### It is tiresome to build these binaries, because there is no clear instructions provided anywhere. 
It's been almost 5 days, I am trying to resolve these issues an no where proper instructions are there._**

Thank you

**Comment by annulen** [comment]
https://github.com/qtwebkit/qtwebkit/wiki/Using-QtWebKit-in-your-project

**Comment by ReshmaMonica** [comment]
Hi annulen,

Its not about the usage of the libraries, in the prebuilt libraries zip there are few libraries missing which is causing this error.

Thank you

**Comment by ReshmaMonica** [comment]
Hi Annulen,

Finally, I can create WebKit libs. I have copied the details steps performed to reach the successful state. Hope it will be useful for someone who is struggling.

Thank you for all the help you provided.

**_Detailed Steps_**

     If Perl not installed
-> install Perl - http://strawberryperl.com/

-> install latest python - https://www.python.org/downloads/

-> install pip3 -  (use get-pip.py)

-> upgrade pip (in cmd)
	python -m pip install --upgrade pip
	
-> run below commands for the webkit build preparation (in cmd)
	pip3 install conan
	pip3 install ninja
	pip3 install cmake

-> download webkit code - https://github.com/qtwebkit/qtwebkit/tree/qtwebkit-5.212
	1. Copy the profile - qtwebkit_gcc_x86 to some location and mention the path in the below command (**Step 3**)
[qtwebkit_gcc_x86.txt](https://github.com/qtwebkit/qtwebkit/files/4578969/qtwebkit_gcc_x86.txt)
	2. Run command prompt and change directory to downloaded webkit folder
	3. Command to build the webkit libs (in cmd)
			Tools\qt\build-qtwebkit-conan.py --qt=C:\Qt\Qt5.14.2\5.14.2\mingw73_32 --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.14.2\5.14.2\mingw73_32" --configure --build --install --profile=C:\qtwebkit_gcc_x86 --arch=x86
		
-> Copying the built webkit libs to qt folder
	1. Open C:\Qt\Qt5.14.2\5.14.2
	2. Open C:\Webkit\build\package
	3. Compare both the folders
	4. copy all the available files/libs from **Step 2** folder to **Step 1** folder
