### ISSUE TITLE
Crash in Debug: prototypeChainMayInterceptStoreTo

### ISSUE THREAD

**Issue by evgeny5743** [qtwebkit/qtwebkit#992]
In Debug Mode the Webkit crashes with Segmentation fault. 

In console:

ASSERTION FAILED: !thisObject->structure(vm)->prototypeChainMayInterceptStoreTo(exec->vm(), propertyName)
../Source/JavaScriptCore/runtime/JSObjectInlines.h(54) : static void JSC::JSObject::putInline(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&)

**Comment by annulen** [comment]
Unfortunately, it's not possible to do anything about such assertion failures
