### ISSUE TITLE
How can i get the Executed script in QWebKit?

### ISSUE THREAD

**Issue by dexter4life** [qtwebkit/qtwebkit#998]
I am wondering if is possible to get the script executed in qwebkit and modify the value of the script in it.

**Comment by annulen** [comment]
>I am wondering if is possible to get the script executed in qwebkit

You are probably looking for `QWebFrame::evaluateJavaScript`

>and modify the value of the script in it.

Not sure what do you mean here.

**Comment by dexter4life** [comment]
Sorry for the delay

**Comment by dexter4life** [comment]
I mean a container or something that stores the javascript loaded into webkit. 
e.g <script src="somelocation"></script>

when this URL somelocation is loaded, can i be able to get the script at runtime and change the content? that's what i mean.

**Comment by annulen** [comment]
You can get `QWebElement` corresponding to that `<script>` element and change its `src` attribute

**Comment by dexter4life** [comment]
okay

**Comment by dexter4life** [comment]
Will that evaluate the script when is being changed?

**Comment by annulen** [comment]
I don't understand your question.

**Comment by dexter4life** [comment]
thanks for your support. I appreciate.
